. (Fejlkode: {i:eresult})"
	"Parental_Set_Fail_Timeout"		"Enten er din computer i øjeblikket ikke i stand til at få forbindelse til Steam-serverne, eller også er tjenesten midlertidigt deaktiveret. Prøv venligst igen senere."
	"Parental_Set_Fail_TryAgain"	"Prøv igen"

	"Parental_Set_Success_Title"	"Familievisning er nu slået til!"
	"Parental_Set_Success_Instr"	"For at starte eller forlade familievisning så vælg dette ikon, i toppen af Steams hovedmenu, og indtast derefter din PIN."
	"Parental_Set_Success_FamilyMode"	"Familievisning"
	"Parental_Set_Success_ParentMode"	"Ikke familievisning"
	"Parental_Set_Success_ModifyTitle"	"Ændring af disse indstillinger"
	"Parental_Set_Success_ModifyInstr"	"Alt beskyttet indhold og funktioner kræver din PIN, før det bliver tilgængeligt. For at ændre disse indstillinger så vend tilbage til dette indstillingspanel."
	"Parental_Set_Success_AddGamesTitle"	"At modificere din liste over familiespil"
	"Parental_Set_Success_AddGameInstr"	"Ethvert emne, føjet til dit bibliotek, ekskluderes automatisk fra denne liste, indtil du tilføjer dem. For at tilføje eller fjerne et emne kan du enten vende tilbage til disse indstillinger, eller åbne spillets \"Links og mere\"-panel i dit bibliotek, hvorfra du kan vælge at tilføje eller fjerne det fra listen."
	"Parental_Set_Success_CommTitle"	"Konto-relaterede beskeder"
	"Parental_Set_Success_Comm"		"Bemærk: {s:email} modtager alle beskeder angående konto- og købsoplysninger."
	"Parental_Set_Success_CommInstr"	"For at ændre denne adresse så gennemgå venligst \"Skift kontakt-email\"-guiden, som du finder under Kontoindstillinger."

	"Parental_Disable_Success_Title"	"Familievisning er nu deaktiveret"
	"Parental_Disable_Success_Instr"	"Du kan på ethvert tidspunkt slå familievisning til igen ved at vende tilbage til disse indstillinger."

	"Parental_DisableTitle"		"Deaktiver familievisning"
	"Parental_DisablePrompt"	"Er du sikker på, at du vil deaktivere familievisningen knyttet til denne konto?"
	"Parental_Disable"			"DEAKTIVER"
	"Parental_Disable_Cancel"	"ANNULLER"

	"SiteLicense_LockTitle"		"Begrænset brug"
	"SiteLicense_LockInfo"		"Netværksoperatøren har begrænset brugen af Steam. Nogle funktioner kan være utilgængelige gennem dette netværk."

	"GoOnline_Header"			"DU ER"
	"GoOnline_CurrentMode"		"OFFLINE"
	"GoOnline_Footer"			"VÆLG FOR AT ÆNDRE"

	"GoOnline_Prompt_Title"		"Gå online"
	"GoOnline_Prompt_Info"		"Vil du gå online? Dette kræver, at Steam genstartes."
	"GoOnline_Prompt_YesButton"	"GENSTART ONLINE"

	"GoOffline_Prompt_Title"	"Gå offline"
	"GoOffline_Prompt_Info"		"Vil du gå offline? Dette kræver, at Steam genstartes."
	"GoOffline_Prompt_YesButton"	"GENSTART OFFLINE"

	"Settings_TimeZone"	"Tidszone"
	"SettingsTimeZone_Intro"	"Hvad er denne enheds nuværende tidszone?"
	"SettingsTimeZone_Region"	"Region"
	"SettingsTimeZone_Apply"	"ANVEND"

	"OOBE_TimeZoneSettings_Title"	"Tidszone"
	"OOBE_TimeZoneSettings_Description"	"Hvad er denne enheds nuværende tidszone?"

	"Settings_Interface"	"Grænseflade"
	"SettingsSteamOS_EnableDesktop" "Aktiver adgang til Linux-skrivebordet"
	"SettingsSteamOS_DesktopWarningTitle" "Advarsel"
	"SettingsSteamOS_DesktopWarningBody" "At slå skrivebordstilstand til lader dig tage fuld kontrol over din maskine og ændre systemets opførsel på måder, som ikke er understøttede.\n\nEr du sikker på, du vil fortsætte?"
	"SettingsInterface_SteamClientCheckForUpdates" "Søg efter opdateringer"
	"SettingsInterface_SteamClientChecking"		"Tjekker"
	"SettingsInterface_SteamClientUpdatePending"	"Genstart for at opdatere"
	"SettingsInterface_SteamClientUpdateDownloading"	"Downloader"
	"SettingsInterface_SteamClientUpdateDesc"	"Steam-klientopdateringer"
	"SettingsInterface_EnableScreenSaver"	"Slå pauseskærm til"
	"SettingsInterface_OfflineModeShortcutsEnable"	"Slå offline-tilstandsgenveje til"
	"SettingsInterface_Search_Google"	"Google"
	"SettingsInterface_Search_Bing"	"Bing"
	"SettingsInterface_Search_Custom"	"Tilpasset (avanceret)"
	"SettingsInterface_SearchProvider" "Standardsøgemaskine:"
	"SettingsInterface_SearchProvider_Custom" "Indtast URL:"
	"SettingsInterface_TouchMode"	"Slå touch-tilstand til"

	"Overlay_EnterGameText"	"Indtast tekst som skal sendes til spillet"
	"Overlay_OpenKeyboard"	"Åbn tastatur"
	"Overlay_HowToClose" "Vend tilbage til {s:apptype}"

	"SettingsInterface_SteamOSCheckForUpdatesDesc"	"{s:steamosversion} opdatering {s:steamosupdatelevel}"
	"SettingsInterface_SteamOSCheckForUpdates"	"Tjek for SteamOS-opdateringer"
	"SettingsInterface_SteamOSCheckForUpdatesTitle" "SteamOS-version"

	"MainMenu_NewSteamOSUpdate"	"Genstart for at opdatere {s:osname}"
	"MainMenu_RestartForSteamOSUpdate_Title"	"Genstart {s:osname}"
	"MainMenu_RestartForSteamOSUpdate"	"Der er opdateringer til {s:osname}. Vil du genstarte for at opdatere nu?\n\nOpdateringen vil tage et par minutter; du må ikke manuelt slukke din computer."
	
	"MainMenu_PromptForAlienwareDeepSleepDisable"	"Slå fjernstart til"
	"MainMenu_PromptForAlienwareDeepSleepDisable_Title"	"Fjernstart"
	"MainMenu_PromptForAlienwareDeepSleepDisable_Message"	"Dit system understøtter fjernstart ved hjælp af Steam Controlleren.\n\nVil du slå dette til nu?\n"

	"Overlay_AsyncNotificatoinsRequestedDialog_Title" "Tillad notifikationer?"
	"Overlay_AsyncNotificatoinsRequestedDialog_Allow" "Tillad notifikationer"
	"Overlay_AsyncNotificatoinsRequestedDialog_Disallow" "Forbyd"
	"Overlay_AsyncNotificatoinsRequestedDialog_Desc" "Dette spil understøtter asynkront gameplay, hvilket lader dig lukke spillet mellem dine ture. Vil du gerne modtage notifikationer i Steam-klienten, når det er din tur?"

	"Overlay_QuitApp_Title"		"Luk applikation"
	"Overlay_QuitApp_Desc"		"Ikke gemte data vil gå tabt."
	"Overlay_QuitApp_QuitAnyway"	"LUK"
	"Overlay_QuitApp_FatalTimeout_SteamOS"	"Steam har problemer med at lukke dette spil. Vil du genstarte din maskine?"
	"Overlay_QuitApp_FatalTimeout_Default"	"Steam har problemer med at lukke dette spil. Vil du prøve igen?"
	"Overlay_QuitApp_FatalOK_SteamOS"	"JA, GENSTART"
	"Overlay_QuitApp_FatalOK_Default"	"JA, PRØV IGEN"
	"Overlay_QuitApp_FatalCancel_SteamOS"	"NEJ, PRØV IGEN"
	"Overlay_QuitApp_FatalCancel_Default"	"NEJ, GIV OP"

	"FileSelector_Footer_Select"	"VÆLG"
	"FileSelector_Footer_Cancel"	"ANNULLER"
	"FileSelector_Footer_OpenDirectory" "ÅBN"
	"FileSelector_Footer_Done" "VÆLG"
	"FileSelector_SelectFile" "Vælg fil"
	"FileSelector_SelectDirectory" "Vælg mappe"
	"FileSelector_Up"	"Gå tilbage"
	"FileSelector_NewDirectory" "Opret ny mappe"
	"FileSelector_Select"	"Vælg"
	"FileSelector_DefaultComputername" "Computer"
	"FileSelector_NoPreview" "Ingen forhåndsvisning"

	"MusicAlbum_Album"		"Album"
	"MusicAlbum_Artist"	"Kunstner"
	"MusicAlbum_Play" "Afspil nummer"
	"MusicAlbum_Play_Album" "Afspil album"
	"MusicAlbum_Play_Tracks" "Afspil numre"
	"MusicAlbum_Play_Next"	"Afspil næste"
	"MusicAlbum_Play_Tracks_Next"	"Spil numre som næste"
	"MusicAlbum_Add_To_Queue"	"Føj til kø"
	"MusicAlbum_Add_To_Playlist" "Føj til playliste"
	"MusicAlbum_Play_Track_Subsequent"	"Afspil efterfølgende numre"
	"MusicAlbum_Play_Next_Subsequent"	"Afspil næste efter efterfølgende"
	"MusicAlbum_Add_To_Queue_Subsequent"	"Føj efterfølgende til kø"
	"MusicAlbum_Add_Tracks_To_Queue"	"Føj til kø"
	"MusicAlbum_Show_In_System"	"Vis i system"
	"MusicAlbum_Refresh_Album" "Opdater album"
	"MusicAlbum_Play_Track"	"Afspil nummer"
	"MusicAlbum_Refresh_Track" "Opdater nummer"
	"MusicAlbum_Footer_More" "MERE"
	"MusicAlbum_Footer_Play"	"AFSPIL"
	"MusicAlbum_And_Other_Artists" "og andre kunstnere"
	"MusicAlbum_Show_Entire_Album" "Vis hele albummet"
  "MusicArtist_Play" "Afspil kunstner"
	"MusicArtist_Play_Next"	"Afspil næste"
	"MusicArtist_Add_To_Queue"	"Føj til kø"
	"MusicArtist_Add_To_Playlist"	"Føj til playliste"
	"MusicArtist_All_Play" "Afspil kunstner"
	"MusicArtist_All_Play_Next"	"Afspil kunster efter"
	"MusicArtist_All_Add_To_Queue"	"Føj kunstner til kø"
	"MusicPlaylist_Title"	"Titel"
	"MusicPlaylist_Play_Playlist"	"Afspil playliste"
	"MusicPlaylist_Play_PlaylistItem"	"Afspil nummer"
	"MusicPlaylist_Play" "Afspil playliste"
	"MusicPlaylist_Play_Next" "Afspil efter"
	"MusicPlaylist_Add_To_Queue" "Føj til kø"
	"MusicPlaylist_Move_Begin" "Flyt til toppen"
	"MusicPlaylist_Move_Up" "Flyt op"
	"MusicPlaylist_Move_Down" "Flyt ned"
	"MusicPlaylist_Move_End" "Flyt til bunden"
	"MusicPlaylist_Delete" "Slet playliste"
	"MusicPlaylist_Delete_Header" "Slet playliste"
	"MusicPlaylist_Delete_Text" "Er du sikker på, du vil slette \"{s:PlaylistName}\" ?"
	"MusicPlaylist_Delete_Yes" "Ja"
	"MusicPlaylist_Delete_Cancel" "Annuller"
	"MusicPlaylist_Rename" "Omdøb playliste"
	"MusicPlaylist_Rename_Text" "Omdøb denne playliste"
	"MusicPlaylist_Rename_OK" "OK"
	"MusicPlaylist_Rename_Cancel" "Annuller"
	"MusicPlaylist_Rename_Accept" "ACCEPTER"
	"MusicPlaylist_Add" "Opret ny playliste"
	"MusicPlaylist_Add_Text" "Opret playliste"
	"MusicPlaylist_Add_OK" "OK"
	"MusicPlaylist_Add_Cancel" "Annuller"
	"MusicPlaylist_Add_Accept" "TILFØJ"
	"MusicPlaylist_Library_Add_Playlist" "Tilføj playliste"
	"MusicPlaylist_Defaultname" "Playliste"
	"MusicPlaylist_Footer_More" "MERE"
	"MusicPlaylist_Footer_Play" "AFSPIL"
	"MusicPlaylist_RemoveTracks" "Slet alle numre"
	"MusicPlaylist_RemoveTracks_Header" "Slet alle numre"
	"MusicPlaylist_RemoveTracks_Text" "Er du sikker på, du vil fjerne alle numre fra \"{s:PlaylistName}\" ?"
	"MusicPlaylist_RemoveTracks_Yes" "Ja"
	"MusicPlaylist_RemoveTracks_Cancel" "Annuller"
	"MusicPlaylistItem_Move_Begin" "Flyt til toppen"
	"MusicPlaylistItem_Move_Up" "Flyt op"
	"MusicPlaylistItem_Move_Down" "Flyt ned"
	"MusicPlaylistItem_Move_End" "Flyt til bunden"
	"MusicPlaylistItem_Delete" "Fjern nummer"
	"MusicPlaylistItem_DeleteAll" "Fjern alle numre"
	"MusicPlaylist_Select" "VÆLG"
	"MusicPlaylist_Cancel" "ANNULLER"
	"MusicPlaylist_Select_NewPlaylist" "Opret ny playliste"

	"Music_TracksInfo_NoTracks" "Ingen numre"
	"Music_TracksInfo_OneTrack" "1 nummer / {s:TracksDuration}"
	"Music_TracksInfo_MultipleTracks" "{i:TracksCount} numre / {s:TracksDuration}"

	"Music_Control_Music"	"MUSIK"
	"Music_Control_System"	"SYSTEM"
	"Music_Control_Browse_Music"	"Gennemse musik"
	"Music_Control_Remove_Track_From_Queue"	"Fjern nummer fra køen"
	"Music_Control_Show_Track_In_System"	"Vis nummer i system"
	"Music_Control_Show_Album_In_UI"	"Vis Album"
	"Music_Control_Browse_Queue"	"Vis hele køen"
	"Music_Control_Clear_Queue"	"Ryd kø"
	"Music_Control_Create_Playlist_From_Queue" "Opret playliste"
	"Music_Control_Track_Time"	"{s:track_current_time} / {s:track_total_time}"

	"Music_Transport_Browse_Music"	"Gennemse musik"
	"Music_Transport_View_Queue"		"Vis kø"
	"Music_Transport_X_Of_Y"	"{i:CurrentQueueEntry} af {i:QueueCount} - {s:QueueDuration}"
	"Music_Transport_X_Tracks" "{i:QueueCount} numre - {s:QueueDuration}"
	"Music_Transport_X_Track" "{i:QueueCount} nummer - {s:QueueDuration}"
	"Music_Transport_Footer_Pause" "PAUSE"
	"Music_Transport_Footer_Play" "AFSPIL"
	"Music_Transport_Footer_More" "MERE"
	"Music_Transport_Footer_Repeat" "GENTAG"
	"Music_Transport_Footer_Shuffle" "BLAND"
	"Music_Transport_Footer_Previous" "FORRIGE"
	"Music_Transport_Footer_Next" "NÆSTE"
	"Music_Transport_Footer_Browse_Music" "GENNEMSE MUSIK"
	"Music_Transport_Footer_Now_Playing" "VIS NUVÆRENDE"
	"Music_Transport_Footer_Volume" "LYDSTYRKE"
	"Music_Transport_Footer_Seek" "SØG"
	"Music_Transport_Footer_Done" "FÆRDIG"
	"Music_Transport_Footer_PlayPause" "AFSPIL / PAUSE"

	"Music_Library_Setup"	"Musikbibliotekopsætning"
	"Music_Library_Header"	"Musik"
	"Music_Library_Albums_Sort" 	"Album efter kunstner"
	"Music_Library_AlbumsTitle_Sort" 	"Albummer efter titel"
	"Music_Library_Artists_Sort" 	"Kunstnere"
	"Music_Library_Playlist_Sort" 	"Playlister"
	"Music_Library_Crawling_Header"	"Bygger dit musikbibliotek..."
	"Music_Library_Crawling_Directories" "Mapper"
	"Music_Library_Crawling_DirectoryCount" "{i:DirectoriesCheckedCount}"
	"Music_Library_Crawling_Albums"	"Album"
	"Music_Library_Crawling_AlbumCount"	"{i:AlbumCount}"
	"Music_Library_Crawling_Tracks"	"Numre"
	"Music_Library_Crawling_TrackCount"	"{i:TrackCount}"
	"Music_Library_Crawling_Album_Header" "Gennemsøger album"
	"Music_Library_Crawling_Album_Not_Possible_Label" "... er ikke muligt, da dit musikbibliotek stadig er ved at blive bygget."
	"Music_Library_Crawling_Header_DeletedAlbums_ProgressGathering" "Samler album som ikke længere er tilgængelige"
	"Music_Library_Crawling_Header_DeletedAlbums_ProgressDeleting" "Sletter album som ikke længere er tilgængelige"
	"Music_Library_Crawling_Header_DeletedArtists_ProgressGathering" "Samler kunstnere som ikke længere er tilgængelige"
	"Music_Library_Crawling_Header_DeletedArtists_ProgressDeleting" "Sletter kunstnere som ikke længere er tilgængelige"
	"Music_Library_Crawling_Header_DuplicateAlbums_Progress" "Fjerner gentagne album..."

	"Music_Library_Search" "SØG"
	"Music_Library_Select_Album" "VÆLG"

	"Music_Library_Setup_Menu_Label" "Tilføj musikbibliotek..."
	"Music_Library_Setup_Title"	"Biblioteksopsætning"
	"Music_Library_Setup_Text" "Hvilke mapper ønsker du at inkludere i dit Steam-musikbibliotek?"
	"Music_Library_Setup_Add_Label" "Tilføj en mappe..."
	"Music_Library_Setup_Add_ButtonLabel" "+"
	"Music_Library_Setup_Entry_ButtonLabel" "-"
	"Music_Library_Setup_Select_To_Add_Library" "Vælg for at tilføje bibliotek"
	"Music_Library_Setup_Marked_For_Removal" "Mappe markeret for fjernelse"
	"Music_Library_Setup_Footer_Done"	"FÆRDIG"
	"Music_Library_Setup_Footer_Cancel" "ANNULLER"
	"Music_Library_Setup_Footer_Select" "VÆLG"
	"Music_Library_Setup_Footer_RemoveFromList"	"FJERN FRA LISTE"
	"Music_Library_Setup_Footer_BuildLibrary"	"BYG BIBLIOTEK"

	"Music_Library_Select_Directory_Header" "Musikbibliotek"
	"Music_Library_Select_Directory_Text"	"Vælg en mappe hvor du ønsker at opbevare musik."
	"Music_Library_Footer_More" "VÆLG"
	"Music_Library_Footer_Play"	"AFSPIL"
	"Music_Library_Footer_ContextMenu"	"FLERE"
	"Music_Library_Footer_Cancel_Crawling" "STOP"

	"Music_Albums_Grid_Title"		"Album"
	"Music_Artists_Grid_Title"		"Kunstnere"
	"Music_Playlists_Grid_Title"		"Playlister"
	"Music_Album_View_Title"		"Album"
	"Music_Playlist_View_Title"		"Playliste"

	"Music_Now_Playing_Title"	"SPILLER NU"
	"Music_Now_Playing_Track_Name"	"{s:now_playing_trackname}"
	"Music_Now_Playing_Artist"	"{s:now_playing_artist}"


	"Music_Artist_Grid_ArtistName"			"{s:artistname}"
	"Music_Artist_Grid_ArtistAlbumCount"	"( {d:albumcount} album, {d:trackcount} numre )"

	"Music_Playlist_Grid_ArtistName"		"{s:playlistname}"
	"Music_Playlist_Grid_Duration_Plural"	"{d:trackcount} numre, varighed {s:totaltime}"
	"Music_Playlist_Grid_Duration"			"1 nummer, varighed {s:totaltime}"

	"Music_Artist_Grid_RowCount_plural_plural"	"( {d:albumcount} album, {d:trackcount} numre )"
	"Music_Artist_Grid_RowCount_single_plural"	"( 1 album, {d:trackcount} numre )"
	"Music_Artist_Grid_RowCount_single_single"	"( 1 album, 1 nummer )"

	"Music_Queue_X_Of_Y"	"{i:CurrentQueueEntry} af {i:QueueCount}"
	"Music_Queue_X_Tracks"	"{i:QueueCount} numre"
	"Music_Queue_Is_Empty"	"Køen er tom"
	"Music_Queue_Browse_Music" "Gennemse musik"
	"Music_Queue_Remove_Track_From_Queue" "Fjern nummer fra kø"
	"Music_Queue_Clear_Queue" "Ryd kø"
	"Music_Queue_Create_Playlist_From_Queue" "Opret playliste"
	"Music_Queue_Footer_Play"	"AFSPIL"
	"Music_Queue_Footer_More"	"MERE"
	"Music_Queue_Footer_Done"	"FÆRDIG"

	"Music_Settings_Header"	"Musik"
	"Music_Settings_Database_Header"	"Database"
	"Music_Settings_Crawl_At_Startup"	"Skan ved opstart"
	"Music_Settings_CrawlSteamInstallFolders" "Skan Steam-mapper for soundtracks"
	"Music_Settings_Building_MusicLibrary"	"Bygger musikbiblioteket"
	"Music_Settings_No_Album_Available" "Ingen album tilgængelig."
	"Music_Settings_One_Album_Available" "Ét album tilgængeligt med {i:TrackCount} numre"
	"Music_Settings_X_Albums_With_Y_Tracks"	"{i:AlbumCount} album tilgængelige med {i:TrackCount} numre"
	"Music_Settings_Stop_Crawling_Header" "Stop opbygning af lokal musikdatabase"
	"Music_Settings_Stop_Crawling_Text"	"Er du sikker på, at du ønsker at stoppe opbygningen af biblioteket?"
	"Music_Settings_Stop_Crawling_Yes" "Ja"
	"Music_Settings_Stop_Crawling_Cancel" "Annuller"
	"Music_Settings_Reset_Database_Header" "Nulstil lokal musikdatabase"
	"Music_Settings_Reset_Database_Text" "Er du sikker på, at du vil nulstille musikdatabasen?"
	"Music_Settings_Reset_Database_Yes" "Ja"
	"Music_Settings_Reset_Database_Cancel" "Annuller"

	"Music_Settings_Reset_Database"	"Nulstil database"
	"Music_Settings_Stop_Scanning"	"Stop skanningen"
	"Music_Settings_Setup_Music_Library"	"Opsæt musikbibliotek"
	"Music_Settings_Audio_Header"	"Lydstyrke"
	"Music_Settings_Music_Volume"	"Musik"
	"Music_Settings_Notification_Header"	"Notifikationer"
	"Music_Settings_Playlist_Now_Playing"	"Vis når et nyt nummer begynder"
	"Music_Settings_Music_Notifications_In_Overlay"	"Skjul musiknotifikationer i overlayet"
	"Music_Settings_Logging_Header"	"Logning"
	"Music_Settings_Logging_Crawling"	"Gem skanningsaktivitetslog"
	"Music_Settings_Pause_Music_Header"	"Sæt musik på pause"
	"Music_Settings_Pause_On_Start_An_Application"	"Når et program startes"
	"Music_Settings_Pause_On_Incoming_Voice_Chat"	"Når et opkald om stemmechat modtages"
	"Music_Settings_Pause_On_Initiating_Voice_Chat"	"Når et opkald om stemmechat startes"
	"Music_Settings_Pause_On_Voice_Chat"	"Når der stemmechattes"
	"Music_Settings_MediaKeysEnabled" "Medietaster"
	"Music_Settings_Downloads_Music_Header" "Yderligere downloads"
	"Music_Settings_Downloads_HighQualityAudio"	"Høj kvalitet/lossless lydfiler (når det er tilgængeligt)"

	"Music_Notification_Now_Playing"	"Afspiller nu"
	"Music_Notification_Now_Paused"	"Nu på pause"

	"Music_Overlay_NowPlaying"	"Afspiller nu"
	"Music_Overlay_NoMusicSelected"	"Ingen musik valgt"

	"Music_FilterHeader"	"Filtrer album"
	"KeyboardHeader_AlbumSearch" "Albumssøgning"

	"Music_Filter_Artists_Header"	"Filtrer kunstnere"

	"Music_Explore_Albums"			"Album"
	"Music_Explore_Artists"			"Kunstnere"
	"Music_Explore_Playlists"		"Playlister"

	"Music_Explore_Recently_Added"	"Nyligt tilføjet"
	"Music_Explore_Recently_Played"	"Nyligt afspillet"

	"Library_Details_OptIntoBeta" "Vælg beta..."
	"Library_Details_EditLaunchCommandLine"	"Angiv startparametre..."

	"Library_EditCommandLine_CodeLabel" "Anbefalet til avancerede brugere."
	"Library_EditCommandLine_Title" "Startparametre til {s:gamename}"

	"Library_EditShortcutName_CodeLabel" "Dette ændrer navnet der står i dit bibliotek for denne genvej."
	"Library_EditShortcutName_Title" "Omdøb genvej for {s:gamename}"

	"Library_AddActionSet_Title"	"Tilføj handlingssæt"
	"Library_AddActionSet_CodeLabel" "Dette tilføjet et nyt sæt handlinger, som kan skiftes til. \nHandlingsættets navn må ikke være tomt."

	"Library_AddActionSetLayer_Title"	"TILFØJ HANDLINGSSÆT-LAG"
	"Library_AddActionSetLayer_CodeLabel" "Dette vil tilføje et nyt sæt af handlinger, som vil blive lagt som et lag oven på det nuværende handlingssæt. Nye tilstande og bindinger vil erstatte de eksisterende, men uberørte områder vil forblive, som de er."

	"Library_ManageActionSet_Title"	"Administrer handlingssæt"
	"Library_RenameActionSet_CodeLabel" "Omdøb dette handlingssæt. Handlingsættets navn må ikke være tomt."

	"Library_CursorOnActionSet_CodeLabel"	"Handlingssæt der skal skiftes til, når markøren vises"
	"Library_CursorOffActionSet_CodeLabel"	"Handlingssæt der skal skiftes til, når markøren skjules"

	"Library_DeleteActionSet_Title"	"Slet handlingssæt"
	"Library_DeleteActionSet_CodeLabel" "Er du sikker på, du vil slette {s:actionsetname}?"

	"Library_SelectActionSet_Title"	"Vælg handlingssæt"
	"Library_SelectActionSet_CodeLabel" "Skift til dette handlingssæt, når du trykker på knappen."

	"Library_SelectPlayerNumber_Title" "Skift spillernummer på controller"
	"Library_SelectPlayerNumber_Description" "Vælg det spillernummer, du vil skifte til. Hvis der er en controller på denne plads, byttes den med denne controller."
	"Controller_Player_Number_Setting" "Spillernummer"

	"Library_SelectMousePosition_Title"	"Vælg markørposition"
	"Library_SelectMousePosition_CodeLabel"	"Flyt markøren til den ønskede postion, og t