 Steam VR-overlay"
	"Steam_LaunchOption_Server"						"Start dedikeret server"
	"Steam_LaunchOption_Editor"						"Start spileditor"
	"Steam_LaunchOption_Config"						"Start konfigurationsværktøj"
	"Steam_LaunchOption_Manual"						"Vis manual"
	"Steam_LaunchOption_Benchmark"				"Start benchmark-værktøj"


	"Activate_SubscriptionSuccess_Headline" "Aktivering lykkedes!"
	"Activate_SubscriptionSuccess" "Din produktaktiveringskode er blevet aktiveret. Dette produkt eller produkter er nu permanent tilknyttet din Steam-konto. Du skal logge på denne konto for at få adgang til de produkter, du lige har aktiveret på Steam."
	"Activate_SubscriptionSuccess_ComingSoonOnly" "Din produktaktiveringskode er blevet aktiveret. Dette indhold bliver tilgængeligt for dig, når spillet er blevet udgivet på Steam. Du skal logge på denne konto for at få adgang til de emner, du lige har aktiveret på Steam."
	"Activate_InvalidCode_Headline" "Ugyldig produktkode"
	"Activate_InvalidCode" "Den indtastede produktkode er ikke gyldig. \n\nSe godt efter om du evt. har indtastet koden forkert. I, L, og 1 kan se ens ud, hvilket også gælder V og Y samt 0 og O."
	"Activate_ServiceUnavailable_Headline" "Steam-serveren er utilgængelig"
	"Activate_ServiceUnavailable" "Enten er din computer i øjeblikket ikke i stand til at få forbindelse til Steam-serverne, eller også er tjenesten midlertidigt deaktiveret. Prøv venligst igen senere."
	"Activate_ContactSupport_Headline" "Købsfejl"
	"Activate_ContactSupport" "Der er opstået en uventet fejl. Dit abonnement på {s:subscription} er ikke blevet gennemført. \n\nKontakt venligst Steam Support."
	"Activate_Subscription_Rejected_Headline" "Duplikeret produktkode"
	"Activate_Subscription_Rejected" "Den produktkode, du har angivet, er allerede aktiveret af en eksisterende Steam-konto og er derfor ugyldig. Aktiveringen af {s:subscription} er ikke gennemført."
	"Activate_AlreadyPurchased_Headline" "Produkt ejes allerede"
	"Activate_AlreadyPurchased" "Denne Steam-konto ejer allerede produktet/produkterne knyttet til denne aktiveringskode. Tryk på OK for at fortsætte til installationen."
	"Activate_RateLimited_Headline" "For mange aktiveringsforsøg"
	"Activate_RateLimited" "Der har været for mange nyligt mislykkede aktiveringsforsøg fra denne konto. Vent venligst og prøv din produktkode igen senere."
	"Activate_RestrictedCountry_Headline" "Ikke tilgængelig"
	"Activate_RestrictedCountry" "Beklager, men {s:subscription} er ikke tilgængelig til køb i dette land. Dit køb er blevet annulleret."
	"Activate_MustOwnOtherApp_Headline" "Aktiver venligst først det oprindelige spil"
	"Activate_MustOwnOtherApp" "Den produktkode, du har indtastet, kræver ejerskab af et andet produkt inden aktivering.\n\nHvis du prøver at aktivere en udvidelsespakke eller DLC, skal du først aktivere det oprindelige spil og derefter aktivere dette ekstraindhold."
	"Activate_MustLoginPS3_Headline" "Din konto har ikke spillet {s:gamename} på PlayStation®3-systemet"
	"Activate_MustLoginPS3" "Den produktnøgle, du har indtastet, kræver, at du først spiller {s:gamename} på PlayStation®3-systemet, før den kan registreres.\n\nVenligst:\n\n- Start {s:gamename} på dit PlayStation®3-system\n\n- Tilknyt din Steam-konto til din PlayStation®3-netværkskonto\n\n- Forbind til Steam mens du spiller {s:gamename} på PlayStation®3-systemet\n\n- Registrer denne produktnøgle gennem Steam"

	"Tenfoot_InstallServiceTitle" "Installerer Steam-tjenesten"
	"Tenfoot_InstallServiceText" "For at kunne køre Steam korrekt, på denne version af Windows, skal Steam-tjenestekomponenten installeres.\nInstallation af tjenesten kræver administratorrettigheder."
	"Tenfoot_InstallServiceOk" "INSTALLER TJENESTE"
	"Tenfoot_InstallServiceCancel" "ANNULLER"

	"Profile_Loading" "Indlæser"
	"Profile_Offline" "Beklager, men det ser ud til, vi ikke kan kommunikere med Steam-fællesskabet lige nu!"
	"Profile_OpenFriendActivity" "VENNEAKTIVITET"
	"Profile_OpenMyProfile"	     "PROFIL"
	"Profile_OpenMyInventory"	"INVENTAR"

	"Profile_Profile_Title"		"Profil"
	"Profile_Inventory_Title"	"Inventar"
	"Profile_TradeOffers_Title"	"Byttetilbud"
	"Profile_NewTradeOffer_Title"	   "Byttetilbud"

	"SteamUI_JoinDialog_DataRequest_Text" "Færdiggør installationen... {d:progress}%"

	"Notification_GameInviteBody"		"inviterer dig til at spille {s:gamename}"
	"Notification_TheSteamCommunity"	"Steam-fællesskabet"
	"Notification_AccessWhilePlaying"	"Adgang under spil"
	"Notification_HasFinishedDownload"	"Download færdig"
	"Notification_IsNowOnline"		"er nu online"
	"Notification_IsNowPlaying"		"spiller nu {s:gamename}"
	"Notification_MultipleIsNowPlaying"		"Du har {d:InGameCount} venner, der spiller spil."
	"Notification_BannedFromChat"		"udelukkede dig fra {s:chatname}-chatten"
	"Notification_KickedFromChat"		"smed dig ud fra {s:chatname}-chatten"
	"Notification_VoiceChat"		"inviterer dig til stemmechat"
	"Notification_ChatInvite"		"inviterer dig til en {s:chatname}-chat"
	"Notification_FriendInvite"		"inviterer dig til at være venner"
	"Notification_TradeInvite"		"inviterer dig til at bytte"
	"Notification_HasSentYouAGift"		"har sendt dig en gave"
	"Notification_ItemReceivedSingular"	"Du har 1 ny genstand i dit inventar"
	"Notification_ItemsReceived"		"Du har {d:numItems} nye genstande i dit inventar"
	"Notification_ClanInvite"		"Du er inviteret til at være med i gruppen {s:clanname}"
	"Notification_ClanInviteSimple"		"inviterer dig til at blive medlem af sin gruppe"
	"Notification_StatusUpdate"		"siger: {s:statustext}"
	"Notification_ClanEvent"		"{s:clanname} {s:action}: {s:event}"
	"Notification_AchievementHeadline_Unlocked"	"Præstation låst op!"
	"Notification_AchievementHeadline_Progress"	"Præstationsfremskridt"
	"Notification_AchievementBody_Unlocked"	"{s:achievement}"
	"Notification_AchievementBody_Progress"	"{s:achievement} ({s:cur}/{s:max})"
	"Notification_ScreenshotTaken"			"Skærmbillede taget!"
	"Notification_MultipleScreenshotsTaken"	"{d:numscreenshots} skærmbilleder taget!"
	"Notification_RefreshLogin"				"Denne konto er logget på andetsteds."
	"Notification_RemoteClientTitle"		"Steam Remote Play"
	"Notification_RemoteClientConnected"	"{s:machine} er tilgængelig til streaming"
	"Notification_RemoteClientDisconnected"	"{s:machine} er ikke længere tilgængelig"
	"Notification_StreamingStarted"	"Streamer fra {s:hostname} til {s:machine}"
	"Notification_StreamingStopped"	"Stoppede streaming til {s:machine}"
	"Notification_NewTurns"		"Du har {d:numItems} nye ture, der venter"
	"Notification_NewTurnsSingular"	"Du har 1 ny tur, der venter"
	"Notification_NetworkConnected"			"Netværk tilsluttet"
	"Notification_NetworkDisconnected"		"Netværk afbrudt"
	"Notification_SteamUpdateAvailable"     "Opdatering tilgængelig"
	"Notification_RestartToUpdate"          "Genstart for at opdatere"
	"Notification_FriendsInvites"		"Du har {d:InviteCount} afventende venneinvitationer."
	"Notification_FriendsInviteCount"	"+{d:InviteCount}"
	"Notification_ClanInvites"		"Du har {d:InviteCount} afventende gruppeinvitationer."
	"Notification_ClansInviteCount"	"+{d:InviteCount}"
	"Notification_MultipleIsNowPlayingCount" "+{d:InGameCount}"
	"Notification_SteamLinkAuth_Title"	"Fjernenhed registreret"
	"Notification_SteamLinkAuth_Text"	"Indtast adgangskode for at bekræfte"
	"Notification_Controller_Title"		"{s:controllername}"
	"Notification_Controller_Text"		"Benytter konfigurationer fra {s:accountname}"
	"Notification_Controller_Guest"		"Bruger en gæstekonto."
	"Notification_ControllerConfigActivated_Text1" "KONFIGURATION INDLÆST"
	"Notification_ControllerConfigActivated_Text2" "{s:configname}"
	"Notification_ControllerConfigActivated_Text3" "Rediger det fra Big Picture-overlayet"
	"Notification_LowBattery" "Batteri: {d:BatteryTime} minutter tilbage"

	"Notification_VirtualHere"			"VirtualHere"
	"Notification_PurchaseVirtualHere"	"Tilgængelig i Steam-butikken til USB-deling"
	
	"Notification_Controller_Player_Number_Title"	"Controller har skiftet plads"
	"Notification_Controller_Player_Number_Changed1"	"{s:controller}"
	"Notification_Controller_Player_Number_Changed2"    "er nu spiller {d:player_number}"
	"Notification_NetworkStateChange"	"Netværkstilstand ændret"
	"Friends_GroupEvent_NowStarting"		"har en begivenhed, der starter"

	"Friends_GroupEvent_NewEventScheduled"	"har planlagt en begivenhed"
	"Friends_GroupEvent_NewAccouncement"	"har slået en meddelelse op"

	"Friends_Header_Recent"		"Nylige chats"
	"Friends_Header_Online"		"Online"
	"Friends_Header_Offline"		"Offline"


	"Steam_DeleteCacheConfirmation_Title"		"Afinstaller?"
	"Steam_DeleteCacheConfirmation_Text"		"{s:gamename} forbliver i dit bibliotek, men for at kunne spille det fremover er du nødt til at downloade dets indhold igen."
	"Steam_DeleteApplicationConfirmation_Text"	"Dette vil slette alt applikationsindholdet for {s:gamename} fra denne computer.\n\nApplikationen forbliver i dit bibliotek, men for at kunne køre den fremover er du nødt til at\ndownloade dens indhold igen."
	"Steam_DeleteFreeCacheConfirmation_Text"		"Dette vil slette alt indholdet for {s:gamename} fra denne computer."
	"Steam_CantDeleteCache_Title"			"Steam - Kan ikke slette {s:gamename}"
	"Steam_CantDeleteCache_Info"			"Kan ikke slette {s:gamename}, da dets data bruges i de følgende spil: {s:dependantgames}"
	"Steam_CantDeleteAppItsRunning_Info"		"Kan ikke slette {s:gamename}, da det køres på nuværende tidspunkt. Luk venligst {s:gamename}, før du prøver at slette det."
	"SteamUI_SecuROM_Revoke_Error_Title"	"Steam - Afinstallation mislykkedes"
	"SteamUI_SecuROM_Revoke_Error_Text"		"Afinstallation af dette program kræver en internetforbindelse."
	"SteamUI_OldClient_Title" "Forældet"
	"SteamUI_OldClient" "Din klient skal opdateres for at kunne spille dette spil."
	"SteamUI_ParentalControl_Title" "Windows Forældrekontrol"
	"SteamUI_ParentalControl_Blocked" "Spillet er blokeret for den nuværende bruger af Windows Forældrekontrol."
	"SteamUI_WrongPlatform_Title" "Spillet er ikke tilgængeligt"
	"SteamUI_WrongPlatform" "{s:gamename} er ikke tilgængeligt på din nuværende platform."
	"SteamUI_Game_Requires_NTFS"		"Spillet kræver NTFS"
	"SteamUI_GameRequires_NTFS_Detail"	"Spillet, du prøver at installere, kræver et drev med et NTFS-filsystem og kan ikke installeres på et FAT32-filsystem."
	"SteamUI_OfflineMode_GameNotReady"		"Dette spil er ikke klar til at blive spillet i offline-tilstand."
	"SteamUI_OfflineMode_GameNotReady_Title"	"Spillet er ikke tilgængeligt"

	"Steam_Preload_GameNotReady_Title" "Endnu ikke tilgængeligt"
	"Steam_Preload_GameNotReady" "Spillet er ikke udgivet endnu. Det bliver låst op\nog vil være tilgængeligt, så det kan spilles på dets officielle udgivelsesdato."

	"Steam_RunGame_Title_Error"			"Fejl"
	"Steam_RunGame_AnotherGameIsBeingRan"	"Kan ikke køre spillet. Du er på nuværende tidspunkt i gang med at starte et andet spil, vent venligst, indtil det er færdigt."
	"Steam_RunGame_Title_ConvertingToSteam3Content"		"Steam-indholdssystem"
	"Steam_RunGame_ConvertingToSteam3Content"			"Dette spil er ved at blive konverteret til Steams nye indholdssystem"
	"Steam_ModNeedsFullGame_Title"	"Fejl"
	"Steam_ModNeedsFullGame_Info"	"{s:gamename} er en mod og kræver, at du ejer en version af grundspillet."
	"Steam_ModNeedsFullGame_Button"	"Få flere oplysninger"
	"Steam_ErrorPurchasePending_Title"	"Køb under behandling"
	"Steam_ErrorPurchasePending_Info"	"Dit køb arbejdes stadig på - Steam vil underrette dig, når transaktionen er gennemført.\nIndtil da, vil spillet ikke kunne spilles."
	"Steam_Media_GenericFailure"				"Kunne ikke føje medie til liste."
	"Steam_Media_ErrorNotEnoughDiskSpace"		"Du har ikke tilstrækkelig ledig diskplads til at afspille dette. Frigør venligst noget diskplads og prøv derefter igen."
	"Steam_SteamErrorTitle"				"Fejl"
	"Steam_MediaAdded_Title"					"Succes"
	"Steam_MediaAdded_Info"					"{s:media} er blevet føjet til dit Steam-mediebibliotek."
	"SteamUI_OfflineMode_Title" "Offline-tilstand"
	"Steam_CannotInstallInOfflineMode"		"Steam skal være i online-tilstand for at installere spil."
	"SteamUI_DownloadsDisabled_Title" "Downloads slået fra"
	"Steam_CannotInstallDownloadsDisabled"	"Spil kan ikke installeres når downloads er slået fra."
	"Steam_RegionRestricted_Title"			"Spillet er ikke tilgængeligt"
	"Steam_RegionRestrictedPurchase_Info"				"Dette spil blev aktiveret med en produktkode, som kun er tilgængelig i et specifikt geografisk område. Eftersom du ikke er i dette område på nuværende tidspunkt, kan {s:gamename} ikke spilles."
	"Steam_CannotInstallApp_Title"	"Fejl"
	"Steam_CannotInstallApp_Info"	"Steam var ikke i stand til at installere {s:gamename} ({s:error})."
	"Steam_ErrorNotEnoughDiskSpace_Title"		"Fejl"
	"Steam_ErrorNotEnoughDiskSpace"			"Du har ikke tilstrækkelig ledig diskplads til at installere dette spil. Frigør venligst noget diskplads og prøv derefter igen."
	"Steam_ErrorNotEnoughDiskSpace_Manage"			"ADMINISTRER DISKPLADS"
	"Steam_InstallAborted_Title"	"Fejl"
	"Steam_InstallAborted_InfoAppNoInfo" "Spillet kan ikke installeres."
	"Steam_InstallAborted_InfoAppUnreleased"	"{s:game} kan ikke installeres endnu, da det ikke endnu er udgivet."
	"Steam_InstallAborted_InfoAppNoDemo"		"{s:game} kan ikke installeres, fordi det er en demo, og du ejer den fulde version af dette produkt. Installer venligst den fulde version af spillet."

	"Steam_NoContentServers_Info"		"Ingen Steam-indholsservere er på nuværende tidspunkt konfigureret til at levere indhold til dette spil.\nDette vil snart blive rettet, prøv venligst igen om nogle få minutter."
	"Steam_App_Install_Failed_Title"	"Fejl"
	"Steam_App_Install_Failed_Text"	"Der opstod en fejl under installationen af {s:game} ({s:reason})"
	"Steam_App_Update_Failed_Title"	"Fejl"
	"Steam_App_Update_Failed_Text"	"Der opstod en fejl under opdateringen af {s:game} ({s:reason})."
	"Steam_App_LegacyKey_Denied_Title" "Steam - Advarsel"
	"Steam_App_LegacyKey_Denied_Text" "Noget eller alt indhold i \"{s:game}\" er kun tilgængeligt ved at oprette forbindelse til en tredjepartstjeneste.\nDen oprindelige ejer skal have registreret sig med denne tjeneste for at få adgang til dette indhold."
	"SteamUI_JoinDialog_DataRequestFailed_Title" "Fejl"
	"SteamUI_JoinDialog_DataRequestFailed_Text" "Steam-serverne har for travlt til at håndtere din anmodning for {s:game}. Fejlkode ({d:error})."
	"SteamUI_JoinDialog_KeyRequestFailed_Title" "Fejl"
	"SteamUI_JoinDialog_KeyRequestFailed_Text" "Kunne ikke kontakte nøgleserver"
	"SteamUI_JoinDialog_KeyRequestPending_Text" "Afventer nøgle-anmodning"
	"SteamUI_JoinDialog_ContinueLaunch" 	"Fortsæt opstart"
	"Steam_NoLongerOwnsGame_Title"	"Fejl"
	"Steam_NoLongerOwnsGame_Info"		"{s:game} er ikke længere gratis tilgængeligt."
	"Steam_UnknownErrorLaunchingMedia"		"Ukendt fejl ved start af medie."
	"SteamUI_JoinDialog_ErrorTitle" 	"Fejl"
	"SteamUI_CantRunMediaDueToMediaPlayerVersion"   "Kan ikke starte {s:game}, da Windows Media Player er version [{s:detectedVersion}], men version [{s:requiredVersion}] er krævet for at afspille mediet.\nInstaller venligst den seneste version af Windows Media Player."
	"SteamUI_CantRunMediaDueToMediaPlayerNotInstalled"   "Kan ikke starte {s:game}, da Windows Media Player ikke er installeret.\nInstaller venligst den seneste version af Windows Media Player fra"
	"SteamUI_CantRunMediaDueToMediaPlayerNotInstalledOSX"   "Kan ikke starte {s:game}, da Windows Media Components for QuickTime ikke er installeret.\nInstaller venligst den seneste version af Windows Media Components for QuickTime."
	"Steam_ErrorCantStartGame" "Dette spil er i øjeblikket ikke tilgængeligt.\nPrøv venligst igen på et andet tidspunkt."
	"Steam_ErrorCantStartGameDetailed" "Kunne ikke starte spillet ({s:error})."
	"Steam_ErrorCantStartGameDependency" "Kunne ikke starte spillet med delt indhold. Opdater venligst disse spil først:\n\n {s:dependencies}"
	"Steam_ErrorCantStartGameLink" "Hjælp"
	"Steam_ContentServersBusy_Title"	"Fejl"
	"Steam_ContentServersBusy_Info"		"Steam-serverne har i øjeblikket for travlt til at håndtere din anmodning.\nPrøv venligst igen om nogle få minutter."
	"SteamUI_JoinDialog_PreparingToPlay1" 	"Forbereder start af {s:game}."
	"SteamUI_JoinDialog_PreparingToPlay2" 	"Forbereder start af {s:game}.."
	"SteamUI_JoinDialog_PreparingToPlay3" 	"Forbereder start af {s:game}..."
	"JoinDialog_UpdateAvailable_Title"				"Opdatering tilgængelig"
	"JoinDialog_UpdateAvailable_Text"					"En opdatering er tilgængelig til {s:game}. Ønsker du at starte spillet nu eller downloade opdateringen først?"
	"JoinDialog_UpdateAvailable_LaunchNow"					"Start nu"
	"JoinDialog_UpdateAvailable_WaitForUpdate"			"Download opdateringen"
	"Steam_LaunchShortcutFailed_Title"	"Fejl ved start via genvej"
	"Steam_LaunchShortcutFailed_Info"		"Kunne ikke starte {s:game}."
	"Steam_ErrorCantStartVRGame"	"Kunne ikke starte {s:game} i VR. (Fejl: {s:error})"
	"Steam_WaitingForVRAppQuit"		"Venter på at VR-applikationen afslutter..."
	"SteamUI_LicenseExpired_Title"	"Licens udløbet"
	"SteamUI_LicenseExpired_Body"		"Din licens for {s:game} er udløbet."
	"Steam_AppUpdateError_0"		"ingen fejl"
	"Steam_AppUpdateError_1"		"ukendt fejl"
	"Steam_AppUpdateError_2"		"opdatering afbrudt"
	"Steam_AppUpdateError_3"		"opdatering annulleret"
	"Steam_AppUpdateError_4"		"opdatering afbrudt"
	"Steam_AppUpdateError_5"		"ingen licenser"
	"Steam_AppUpdateError_6"		"ingen internetforbindelse"
	"Steam_AppUpdateError_7"		"forbindelsen udløb"
	"Steam_AppUpdateError_8"		"indhold stadig krypteret"
	"Steam_AppUpdateError_9"		"mangler app-konfiguration"
	"Steam_AppUpdateError_10"		"disklæsningsfejl"
	"Steam_AppUpdateError_11"		"diskskrivningsfejl"
	"Steam_AppUpdateError_12"		"ikke nok diskplads"
	"Steam_AppUpdateError_13"		"beskadigede indholdsfiler"
	"Steam_AppUpdateError_14"		"venter på installationsdisk"
	"Steam_AppUpdateError_15"		"ugyldig installationssti"
	"Steam_AppUpdateError_16"		"app kører allerede"
	"Steam_AppUpdateError_17"		"mangler delt indhold"
	"Steam_AppUpdateError_18"		"ikke installeret"
	"Steam_AppUpdateError_19"		"opdatering påkrævet"
	"Steam_AppUpdateError_20"		"optaget"
	"Steam_AppUpdateError_21"		"indholdsservere er ikke tilgængelige"
	"Steam_AppUpdateError_22"		"ugyldig app-konfiguration"
	"Steam_AppUpdateError_23"		"ugyldig depotkonfiguration"
	"Steam_AppUpdateError_24"		"manglende manifestindhold"
	"Steam_AppUpdateError_25"		"app ikke udgivet"
	"Steam_AppUpdateError_26"		"regionsbegrænset"
	"Steam_AppUpdateError_27"		"beskadiget indholdscache"
	"Steam_AppUpdateError_28"		"mangler eksekverbar fil"
	"Steam_AppUpdateError_29"		"ugyldig platform"
	"Steam_AppUpdateError_30"		"ikke-understøttet filsystem"
	"Steam_AppUpdateError_31"		"beskadigede opdateringsfiler"
	"Steam_AppUpdateError_32"		"downloads slået fra"
	"Steam_AppUpdateError_33"		"delt bibliotek låst"
	"Steam_AppUpdateError_34"		"afventer licens"
	"Steam_AppUpdateError_35"		"en anden session spiller"
	"Steam_AppUpdateError_36"		"beskadiget download"
	"Steam_AppUpdateError_44"		"ingen licenser tilgængelige"
	"Steam_AppUpdateError_45"		"blokeret af forældrekontrol"
	"Steam_AppUpdateError_46"		"oprettelsesproces mislykkedes"
	"Steam_AppUpdateError_47"		"Steam-klienten er forældet"


	"Friends_Tab_Friends"		"VENNER"
	"Friends_Tab_Groups"		"GRUPPER"
	"Friends_Tab_Players"		"SPILLERE"
	"Friends_Tab_Invites"		"INVITATIONER"
	"Friends_ChatWith_X"		"Chat med\n{s:chatfriendname}"
	"Friends_Chat_FriendName"	"{s:chatfriendname}"
	"Friends_Chat_FriendStatus"	"{s:chatfriendstatus}"
	"Friends_Chat_FriendStatusDetail"	"{s:chatfriendstatusdetail}"
	"Friends_GroupChatWith_X"	"Gruppechat med\n{s:chatfriendname}"
	"Friends_Chat_StartVoiceChat"	"START STEMMECHAT"
	"Friends_Chat_AcceptVoiceChat"	"ACCEPTER STEMMECHAT"
	"Friends_Chat_DeclineVoiceChat"	"AFSLÅ STEMMECHAT"
	"Friends_Chat_HoldVoiceChat"	"SÆT STEMMECHAT PÅ PAUSE"
	"Friends_Chat_ResumeVoiceChat"	"GENOPTAG STEMMECHAT"
	"Friends_Chat_EndVoiceChat"		"AFSLUT STEMMECHAT"
	"Friends_Chat_X_IsTy