ter i denne transaktion."

	"Checkout_AddFunds_Title"					"Tilføj penge til din tegnebog"
	"Checkout_AddFunds_Description"				"Penge i din Steam-tegnebog kan bruges til at købe et hvilket som helst spil på Steam, samt i spil, der understøtter Steam-overførsler."
	"Checkout_AddFunds_Minimum"					"Mindst krævet"
	"Checkout_AddFunds_AddAmount"				"Tilføj {s:amount}"

	"Checkout_MicroTxnAuth_Title"				"Steam-transaktioner"
	"Checkout_MicroTxnAuth_Description"			"{s:game} har anmodet om autorisation for følgende transaktion."
	"Checkout_MicroTxnAuth_AddFunds"			"Tilføj penge"
	"Checkout_MicroTxnAuth_UpdateBillingInfo"	"Opdater faktureringsoplysninger"
	"Checkout_MicroTxnAuth_Approve"				"Godkend transaktion"
	"Checkout_MicroTxnAuth_Cancel"				"Annuller transaktion"
	"Checkout_MicroTxnAuth_PayWithWallet"	"Forny med Steam-tegnebog"
	"Checkout_MicroTxnAuth_SubscriptionText"	"Steam opkræver automatisk din gemte betalingsmetode, når dit abonnement fornyes. Hvis du ikke har nogen gemte faktureringsoplysninger, vil Steam forsøge at bruge midlerne i din Steam-tegnebog."

	"Checkout_MicroTxnAuth_Error"				"Der opstod en fejl under indlæsningen af Steam-transaktionsoplysningerne for dette spil. Prøv venligst igen."
	"Checkout_MicroTxnAuth_Quantity"			"ANTAL {i:quantity}"
	"Checkout_MicroTxnSubscription"                                                          "Du vil blive opkrævet {m:cost} hver(t) {d:frequency}. {s:time}"
	"Checkout_MicroTxnSubscriptionGame"                                                      "Faktureret {m:cost} hver(t) {d:frequency}. {s:time}"
	"Checkout_MicroTxnSubscriptionYears"                               "år"
	"Checkout_MicroTxnSubscriptionMonths"                          "måned(er)"
	"Checkout_MicroTxnSubscriptionWeeks"                            "uge(r)"
	"Checkout_MicroTxnSubscriptionDays"                                "dag(e)"

	"Trailer_Slideshow_Error"					"Kunne ikke indlæse trailere på dette tidspunkt"

	"Library_ContentTitle"	"Bibliotek"
	"Library_RecentlyPlayed"	"NYLIGT SPILLET"
	"Library_ViewAll"		"VIS ALLE"
	"Library_Games"			"SPIL"
	"Library_Screenshots"	"SKÆRMBILLDER"
	"Library_ViewAll_Screenshots"	"SE ALLE"
	"Library_Movies"		"FILM"
	"Library_Music"			"MUSIK"
	"Library_Downloads"	"Downloads"
	"Library_ViewAll_Music"	"VIS ALLE"
	"Library_Details_LinksAndMore"	"LINKS OG MERE"
	"Library_Details_Achievements"	"PRÆSTATIONER <span class=\"NumberElement\">{i:num_achievements_completed}/{i:num_achievements}</span>"
	"Library_Details_Guides"	"GUIDER"
	"Library_Details_GuidesWithTotal"	"GUIDER <span class=\"NumberElement\">{i:num_guides}</span>"
	"Library_Details_Play"		"SPIL"
	"Library_Details_Watch"		"SE"
	"Library_Details_PlayVR"		"SPIL I VR"
	"Library_Details_Play2D"		"SPIL PÅ SKRIVEBORD"
	"Library_Details_PlayTheatre" "SPIL I BIOGRAFTILSTAND"
	"Library_Details_Stream"		"STREAM"
	"Library_Details_Controller"	"STEAM CONTROLLERS"
	"Library_Details_SharingStatus" "DELT AF"
	"Library_Details_SharingInUse"	"I BRUG AF"
	"Library_Details_SharingHeader" "{s:sharing_header}"
	"Library_Details_SharingUser" "{s:sharing_user}"

	"Library_Details_ComingSoon"	"KOMMER SNART"
	"Library_Details_Preload"	"FORUDINDLÆS"
	"Library_Details_Preloaded"	"FORUDINDLÆST"
	"Library_Details_PrePurchase"	"FORUDKØB"
	"Library_Details_ActivateGuestPass"	"AKTIVER"
	"Library_Details_Install"		"INSTALLER"
	"Library_Details_Downloading"		"DOWNLOADER"
	"Library_Details_Updating"		"OPDATERER"
	"Library_Details_Validating"	"VALIDERER"
	"Library_Details_Preloading"	"FORUDINDLÆSER"
	"Library_Details_Disabled" "UTILGÆNGELIG"
	"Library_Details_Update"	"OPDATERING"
	"Library_Details_Download"		"DOWNLOAD"
	"Library_Details_CancelValidation"	"ANNULLER"
	"Library_Details_Launch"		"START"
	"Library_Details_LaunchVR"		"KØR I VR"
	"Library_Details_LaunchVROverlay" "START VR-OVERLAY"
	"Library_Details_Launch2D"		  "START PÅ SKRIVEBORD"
	"Library_Details_Launching"		"STARTER"
	"Library_Details_Running"		"AFSLUT SPIL"
	"Library_Details_Purchase"		"KØB"
	"Library_Details_Renew"			"FORNY"
	"Library_Details_FriendsWhoPlay"	"VENNER DER SPILLER"
	"Library_Details_FriendsPlayingNow"	"VENNER, DER SPILLER NU"
	"Library_Details_ViewFriendsWhoPlay"	"VIS ALLE"
	"Library_Details_Workshop"		"VÆRKSTED"
	"Library_Details_Screenshots"		"SKÆRMBILLEDER <span class=\"NumberElement\">{i:sscount}</span>"
	"Library_Details_RecentNews"	"SENESTE NYHEDER"
	"Library_Details_Achievements_MostRecent" "SENESTE"
	"Library_Details_Achievements_SoClose"	"SÅ TÆT PÅ..."
	"Library_Details_Achievements_MoreUnachieved"	"FLERE UOPNÅEDE"
	"Library_Details_Purchased"	"KØBT"
	"Library_Details_PurchasedValue"	"{t:s:purchased_date}"
	"Library_Details_YouvePlayed"	"DU HAR SPILLET"
	"Library_Details_LastPlayed"	"SIDST SPILLET"
	"Library_Details_LastPlayedValue"	"{t:r:s:lastplayed}"
	"Library_Details_YouveWatched"	"DU HAR SET"
	"Library_Details_LastWatched"	"SIDST SET"
	"Library_Details_SteamCloud"	"STEAM CLOUD"
	"Library_Details_SteamCloudValue"	"{s:cloud_status}"
	"Library_Details_RentalRemaining"	"TILBAGEVÆRENDE UDLEJNINGSTID"
	"Library_Details_RentalInfo"	"LEJEOPLYSNINGER"
	"Library_Details_RentalInfo_BodyActivated"	"Lejeperioden er blevet aktiveret. Du har nu indtil {s:expiration} til at se denne video færdig."
	"Library_Details_RentalInfo_Body"	"Du har indtil {s:expiration} til at begynde at se denne video. Når du begynder, har du 48 timer til at se den færdig."
	"Library_Details_RentalRemainingValue"	"{t:r:l:t:timeremaining}"
	"Library_Details_RentalExpiredValue"	"Din udlejningstid for denne video er udløbet"
	"Library_Details_Minutes"	"{i:minutes} minutter"
	"Library_Details_Hours"		"{i:hours} timer"
	"Library_Details_MinutesSingular"	"{i:minutes} minut"
	"Library_Details_HoursSingular"		"{i:hours} time"
	"Library_Details_Synchronized"	"Synkroniseret"
	"Library_Details_Syncing"	"Synkroniserer"
	"Library_Details_NeedsSync"	"Synkronisering krævet"
	"Library_Details_SyncingConflict"	"Konflikt"
	"Library_Details_CloudUnknown"	"Ukendt"
	"Library_Details_DownloadableContent"	"Køb DLC"
	"Library_Details_LibraryDetails"	"Start {s:apptype}"
	"Library_Details_GameStorePage"		"{s:apptype}-butiksside"
	"Library_Details_GameHubPage"		"{s:apptype}-hubside"
	"Library_Details_GameForums"		"Fællesskabsdiskussioner"
	"Library_Details_LegacyCDKey"		"Vis CD-nøgle"
	"Library_Details_Support"		"Support"
	"Library_Details_Settings"			"Administrer {s:apptype}"
	"Library_Details_SetCategory"		"Vælg kategorier..."
	"Library_Details_SetLanguage"		"Angiv sprog..."
	"Library_Details_IncludeInVR"		"Inkluder i VR-bibliotek"
	"Library_Details_DeleteLocalContent"	"Afinstaller..."
	"Library_Details_DeleteShortcut"	"Slet genvej..."
	"Library_Details_ChooseIcon"	"Skift ikon..."
	"Library_Details_ChooseIconHeader"	"Skift genvejsikon"
	"Library_Details_ChooseIconText"	"Vælg et nyt ikon for denne genvej"
	"Library_Details_ChangeShortcutName"	"Rediger genvejsnavn..."
	"Library_Details_DefaultIcon"	"Gendan standard-ikon"
	"Library_Details_RemoveIcon"	"Fjern brugerdefineret ikon..."
	"Library_Details_Confirm_RemoveIconTitle" "Fjern ikon?"
	"Library_Details_Confirm_RemoveIconBody" "Vil du fjerne det brugerdefinerede ikon, du har tildelt?"
	"Library_Details_RemoveIcon_Confirm"	"JA"
	"Library_Details_RemoveIcon_Cancel"	"ANNULLER"
	"Library_Details_Settings_Title"		"{s:appname}-indstillinger"
	"Library_Details_StorePage"		"Vis butiksside"
	"Library_Details_FirmwareRecover" 	"Gendan Steam Controller-firmware"
	"Library_Details_WithOverlay"		"Aktivér overlay i ikke-Steam-spil"

	"Library_Details_CommunityContent_All"				 "Alle"
	"Library_Details_CommunityContent_Screenshots"		 "Skærmbilleder"
	"Library_Details_CommunityContent_Artwork"			 "Illustrationer"
	"Library_Details_CommunityContent_Videos"			 "Videoer"
	"Library_Details_CommunityContent_Broadcasts"		 "Broadcasts"
	"Library_Details_CommunityContent_Workshop"			 "Værksted"
	"Library_Details_CommunityContent_News"				 "Nyheder"
	"Library_Details_CommunityContent_Guides"			 "Guider"
	"Library_Details_CommunityContent_Reviews"			 "Anmeldelser"
	

	"Controller_FirstTimeLaunch_String1"	"Dette er din første gang, du spiller dette"
	"Controller_FirstTimeLaunch_String2"	"spil med en Steam Controller. Tryk på"
	"Controller_FirstTimeLaunch_String3"	"Steam-knappen for at vælge en konfiguration."
	"Controller_NewController_ConnectedToast1"	"En controller er blevet registreret"
	"Controller_NewController_ConnectedToast2"	"og er nu klar til brug."
	"Controller_WirelessIssue1"	"Din Steam Controller lader til"
	"Controller_WirelessIssue2"	"at have nogle forbindelsesproblemer."
	"Controller_WirelessIssue3"	"Tryk på Steam-knappen for hjælp."
	"Controller_WirelessIssue_Footer" "FJERN"

	"Controller_Registration_Title"		"CONTROLLER-REGISTRERING"
	"Controller_Registration_Desc"		"Registrer din controller til din Steam-konto, og så sørger vi for, at dine konfigurationer følger med controlleren, lige meget hvor du medbringer den."
	"Controller_Registration_Name"		"Controller-navn:"
	"Controller_Registration_Submit"	"Registrer til denne konto"
	"Controller_Registration_Cancel"	"Vent, dette er ikke min konto"
	"Controller_Registration_Guest"		"Brug en gæstekonto"
	"Controller_Registration_SubDesc"	"Du kan til enhver tid ændre dette i Big Picture-indstillingerne."
	"Controller_Registration_GuideBrightness"	"Lysstyrke for controller:"
	"Controller_Registration_LEDHue"			"Controller-lysfarve:"
	"Controller_Registration_LEDSaturation"			"Controller-lysmætning:"
	"Controller_Registration_AbortTitle"	"Registrering afbrudt"
	"Controller_Registration_AbortDesc"		"Foreløbigt bruger vi bare konfigurationer fra {s:accountname}. Næste gang, du logger på din egen konto, får vi din controller opsat."
	"Controller_Registration_MigrateFail"		"Flytning mislykkedes"
	"Controller_Registration_MigrateFailDesc"	"Vi stødte på et problem. Prøv venligst at registrere igen senere. For nu, logger vi dig på som en gæst."
	"Controller_Registration_GuestTitle"	"Bruger en gæstekonto"
	"Controller_Registration_GuestDesc"		"Ok, vi bruger konfigurationer fra {s:accountname}."
	"Controller_Registration_ProgressTitle"	"Registrerer..."
	"Controller_Registration_Personalize_Title" "PERSONLIGGØR DIN CONTROLLER"
	"Controller_Registration_Personalize_Submit" "Færdig"
	"Controller_Registration_Personalize_Cancel" "Annuller"
	"Controller_Registration_Migrating_Title" "FLYTTER KONFIGURATIONER..."
	"Controller_Registration_Selecting_Title" "VÆLG CONTROLLER-KONTO"
	"Controller_Registration_Selecting_Desc" "Vi har ikke set din controller på denne konto før. Vil du gerne registrere den eller bruge konfigurationer fra en anden konto?"
	"Controller_Registration_Selecting_Account"	"Brug konfigurationer fra: {s:selaccountname}"
	"Controller_Registration_FirmwareUpdate_Title"	"Firmware-opdatering krævet"
	"Controller_Registration_FirmwareUpdate_Desc" "For at bruge de seneste tilpasnings- og delingsfunktioner til Steam Controlleren er en firmware-opdatering krævet."
	"Controller_Registration_FirmwareUpdateAborted_Desc"	"Næste gang, du bruger din controller med den seneste firmware, får vi din controller opsat. Vi logger dig på som en gæst foreløbigt."
	"Controller_Remigration_Title"		"Remigrering af controller krævet"
	"Controller_Remigration_Desc"		"Vi har løst et problem i controller-migreringsprocessen relateret til ikke-Steam-spil. Vælg OK for at udføre migreringen igen."
	"Controller_Remigration_Cancel"		"Jeg gør det næste gang"

	"Controller_Registration_Firmware_Submit"	"OK"

	"Controller_OptOut_Title"			"Konfigurationsunderstøttelse slået fra"
	"Controller_OptOut_Desc"			"Konfigurationsunderstøttelse for {s:controllertype} er slået fra. Konfigurationsunderstøttelse for {s:controllertype} skal slås til i Steams controllerindstillinger, og understøttelse af dette spil skal slås til i spillets controllerindstillinger."

	"Controller_NotAttached_Title"		"Ingen controller tilsluttet"
	"Controller_NotAttached_Desc"		"Tilslut venligst en controller for at konfigurere den"

	"Controller_Config_Offline_Title"	"Offline konfigurationsredigering"
	"Controller_Config_Offline_Desc"	"Du er i øjeblikket offline. Din sidste indlæste konfiguration er tilgængelig og kan blive redigeret, men ændringer vil blive tabt, når du igen er online. En lokalt gemt fil vil blive skabt til disse ændringer."

	"Controller_Config_FailedLoad"			"Konfigurationsfejl"
	"Controller_Config_FailedLoad_Desc"		"Vi var ikke i stand til at indlæse din konfiguration på nuværende tidspunkt. Prøv venligst igen senere."
	"Controller_Config_CommFailedLoad"		"Download mislykkedes"
	"Controller_Config_CommFailedLoad_Desc"	"Vi var ikke i stand til at downloade fællesskabskonfigurationen på nuværende tidspunkt. Prøv venligst igen senere."

	"Library_Details_ValidateLocalContent"	"Valider indhold"
	"Library_Details_KillApp"		"Afslut {s:apptype}"
	"Library_Details_NewsDate"		"{t:l:date}"
	"Library_Details_NewsByline"	"{s:feed}"
	"Library_Details_ViewNewsPost"	"VIS NYHEDSINDLÆG"
	"Library_Details_ScreenshotHowTo1"	"Spilgenvej tildelt via genvejskonfiguration af Guide-knap"
	"Library_Details_ScreenshotHowTo2"	"Genvejstast til skærmbillede i spillet"
	"Library_Details_ManageScreenshots"	"Administrer skærmbilleder"
	"Library_Details_ViewGameBadge"	"VIS EMBLEM"
	"Library_Details_ViewAllScreenshots"	"Vis alle skærmbilleder ({s:sscount})"
	"Library_Details_ViewAllAchievements"	"VIS ALLE"
	"Library_Details_ViewAllGuides"			"VIS ALLE GUIDER"
	"Library_Details_ViewGuides"			"VIS GUIDER"
	"Library_Details_ViewAllWorkshopItems"		"VIS ALLE"
	"Library_Details_ViewCommunityHub"			"VIS FÆLLESSKABSINDHOLD"
	"Library_Details_CommunityContentHeadline"			"FÆLLESSKABSINDHOLD"
	"Library_Details_NotAvailablePlatform"			"IKKE TILGÆNGELIG PÅ {s:currentos}"
	"Library_Details_AvailableOnPlatforms"		"Tilgængelig på {s:platformlist}"

	"Library_Details_UnavailableOnPlatform_HowToStream_Title"		"STREAM {s:apptype}"
	"Library_Details_UnavailableOnPlatform_HowToStream_Desc"		"Denne/dette {s:apptype_lowercase} kører ikke på {s:currentos}, men hvis du logger ind på Steam på en nærliggende maskine, der kører en af de understøttede platforme ({s:platformlist}), så kan du streame denne/dette {s:apptype_lowercase} over dit kabelnetværk."
	"Library_Details_GameNotDesignedForControllerWarning_Title"		"CONTROLLER-KONFIGURATION PÅKRÆVET"
	"Library_Details_GameNotDesignedForControllerWarning_Desc"		"Dette spil blev ikke designet til controllere, men du kan spille det med din Steam Controller. Spillet viser muligvis tastaturråd under spil."
	"Library_Details_GameNotDesignedForControllerWarning_Desc_Detail"		"Dette spil blev ikke designet til controllere, men du kan spille det med din Steam Controller. Spillet viser muligvis tastaturråd under spil.\n\nMens du spiller, kan du på ethvert tidspunkt trykke på Steam-knappen for at få vist overlayet og tilpasse din controller-konfiguration."
	"Library_Details_GameDesignKeyboardMouseWarning_Title"		"SPIL FOKUSERET PÅ TASTATUR/MUS"
	"Library_Details_GameDesignKeyboardMouseWarning_Desc"		"Gameplay i dette spil er stærkt afhængigt af at have et fysisk tastatur og en fysisk mus til stede."
	"Library_Details_GameRequiresMouseKeyboardInteractionWarning_Title"		"TASTATUR/MUS PÅKRÆVET"
	"Library_Details_GameRequiresMouseKeyboardInteractionWarning_Desc"		"Skaberne af dette spil har lavet en grænseflade, der kræver et tastatur og/eller en mus for at tilgå områder af dette spil."
	"Library_Details_GameRequiresMouseKeyboardInteractionWarning_Desc_Detail"		"Skaberne af dette spil har lavet en grænseflade, der kræver et tastatur og/eller en mus for at tilgå områder af dette spil. For eksempel inkluderer det muligvis en spilopstarter mellem Steam og selve spillet eller en menu i spillet, der ikke kan navigeres med en controller."
	"Library_Details_OverlayDisabledWarning_Title"		"STEAM-OVERLAY SLÅET FRA"
	"Library_Details_OverlayDisabledWarning_Desc"		"Steam-overlayet er slået fra. Konfigurering i spillet og visse Steam Controller-funktioner er utilgængelige."
	"Library_Details_OverlayDisabledWarning_Desc_Detail"		"Steam-overlayet kræves for at kunne konfigurere din Steam Controller i spil og for at visse funktioner, såsom skærmtastaturer, kan fungere. Slå venligst Steam-overlayet til generelt eller udelukkende i dette spil, for at kunne gøre brug af alle controllerens funktioner."
	