ckout_Failed_InitTransaction"							"Det ser ud til, at der er opstået en fejl vedrørende initialiseringen eller opdateringen af transaktionen. Vent venligst et minut, og prøv igen, eller kontakt support for hjælp."
	"Checkout_Failed_InitTransaction_AVS"						"Din faktureringsinformation mislykkedes i adressebekræftelsen. Ret venligst fejlen eller kontakt support for hjælp."
	"Checkout_Failed_InitTransaction_InsufficientFunds"			"Dine faktureringsoplysninger har oplyst, at der ikke er tilstrækkelige midler til rådighed. Ret venligst fejlen, eller kontakt support for hjælp."
	"Checkout_Failed_InitTransaction_Support"					"Der forekom en intern fejl under initialiseringen af transaktionen. Kontakt venligst support for hjælp."
	"Checkout_Failed_InitTransaction_Unavailable"				"Denne betalingsmetode kan ikke benyttes på nuværende tidspunkt. Kontakt venligst support for hjælp eller vælg en anden betalingsmetode og prøv igen."
	"Checkout_Failed_InitTransaction_PaymentMethodInvalid"	"Der opstod et problem med at bruge den valgte betalingsmetode til dit køb. Vælg en anden betalingsmetode, og prøv igen."
	"Checkout_Failed_InitTransaction_PaymentMethodNotAllowed"				"Den valgte betalingsmetode understøttes ikke for et produkt, du er ved at købe. Vælg en anden betalingsmetode, og prøv igen."
	"Checkout_Failed_InitTransaction_ExpiredCard"				"Dit køb kunne ikke gennemføres, da dit kreditkort er udløbet. Opdater venligst dine kreditkortoplysninger og prøv igen."
	"Checkout_Failed_InitTransaction_RequiredApp"				"Din transaktion mislykkedes, fordi du forsøger at købe et spil, der kræver ejerskab af et andet spil, som du ikke ejer på nuværende tidspunkt. Ret venligst fejlen og prøv igen."
	"Checkout_Failed_InitTransaction_AlreadyOwned"				"Dit køb kunne ikke gennemføres, da det ser ud til, at du allerede ejer en af de spil, du prøver på at købe. Tjek venligst din konto og kurv for at bekræfte, at du køber noget, du ikke allerede ejer."
	"Checkout_Failed_InitTransaction_WalletCurrencyMismatch"	"Dit køb kunne ikke gennemføres, fordi det lader til, at valutaen for midlerne i din Steam-tegnebog ikke svarer til valutaen for dette køb."
	"Checkout_Failed_InitTransaction_CannotGift"				"Dit køb kunne ikke gennemføres, da din kurv indeholder emner, som ikke kan gives som en gave."
	"Checkout_Failed_InitTransaction_CannotShipInternationally"	"Dit køb kunne ikke gennemføres, da din indkøbskurv indeholder emner, som ikke kan afsendes uden for USA."
	"Checkout_Failed_InitTransaction_OutOfInventory"			"Din ordre kan ikke gennemføres, da ét eller flere emner i din kurv ikke er på lager på nuværende tidspunkt. Prøv venligst igen senere."
	"Checkout_Failed_InitTransaction_CannotShipToCountry"	"Dit køb kunne ikke gennemføres, da din indkøbskurv indeholder emner, som ikke kan afsendes til din lokation."
	"Checkout_Failed_InitTransaction_PendingTransactions"		"Advarsel: Din seneste transaktion med os afventer stadig! Fuldførte du betalingen med din betalingsformidler? Vi er ikke sikre endnu, og vi venter på at modtage et svar fra dem.\n\nHvis du fortsætter og køber nogle emner for anden gang, risikerer du at blive debiteret to gange."
	"Checkout_Failed_InitTransaction_AccountLocked"				"Dit køb blev ikke gennemført. Din konto er i øjeblikket låst fra at købe. Kontakt venligst Steam Support for at få mere information."
	"Checkout_Failed_SteamLimitExceeded"						"For at beskytte kontohaveren er købet blevet afslået. Yderligere køb vil blive midlertidigt begrænset - kontakt venligst Steam Support for at løse dette problem."
	"Checkout_Failed_OverlappingPackagesInCart"					"Du kan ikke færdiggøre din transaktion, da du prøver på at købe et emne, som allerede er inkluderet i en anden pakke i din kurv. Tjek venligst din kurv for at bekræfte, at du ikke køber det samme emne flere gange. Den mest almene årsag ville være køb af DLC sammen med en deluxe-version af et produkt, som allerede inkluderer det samme DLC."

	"Checkout_Failed_GetFinalPrice_StoreCountry"				"Din faktureringsadresse ser ikke ud til at passe med dit nuværende land. Kontakt venligst support for hjælp eller brug en anden betalingsmetode, som er registreret til din nuværende adresse."
	"Checkout_Failed_Finalize_ExceedWalletMax"					"Dit køb er ikke blevet gennemført.\nBeløbet, som ville blive føjet til din Steam-tegnebog, ville overstige det maksimalt tilladte."
	"Checkout_Failed_Finalize_GenericError"						"Der er opstået en uventet fejl. Dit køb er ikke blevet gennemført. Kontakt venligst Steam Support."
	"Checkout_Failed_CCAVSError"								"Dit køb er ikke blevet gennemført. Dine kreditkortoplysninger er blevet afvist af din kreditkortudbyder, fordi der er blevet angivet en forkert adresse.\n\nVær opmærksom på, at din kreditkortudbyder i visse tilfælde kan \"spærre\" pengene på din konto, uden at du bliver opkrævet penge. Når du har rettet oplysninger nedenfor, forsøg da at foretage dit køb igen."
	"Checkout_Failed_TimeoutError"								"Enten er din computer i øjeblikket ikke i stand til at få forbindelse til Steam-serverne, eller også er tjenesten midlertidigt deaktiveret. Prøv venligst igen senere."
	"Checkout_Failed_CC_DeclinedError"							"Dit køb er ikke blevet gennemført. Dine kreditkortoplysninger er blevet afvist af din kreditkortudbyder\n\nVær opmærksom på, at din kreditkortudbyder i visse tilfælde kan \"spærre\" pengene på din konto, uden at du bliver opkrævet penge. Når du har rettet oplysninger nedenfor, forsøg da at foretage dit køb igen."
	"Checkout_Failed_CC_InsufficientFunds"						"Dit køb er ikke blevet gennemført. Dine kreditkortoplysninger er blevet afvist af din kreditkortudbyder på grund af utilstrækkelige midler på kontoen.\n\nVær opmærksom på, at din kreditkortudbyder i visse tilfælde kan \"spærre\" pengene på din konto, uden at du bliver opkrævet penge."
	"Checkout_Failed_CC_RestrictedCountry"						"Beklager, men en af genstandene, du forsøger at købe, er ikke tilgængelig til køb i dette land. Dit køb er blevet annulleret."
	"Checkout_Failed_ExceedWalletMax"							"Dit køb er ikke blevet gennemført.\\Beløbet, som ville blive føjet til din Steam-tegnebog, ville overstige det maksimalt tilladte."
	"Checkout_Failed_AccountLocked"								"Dit køb blev ikke gennemført. Din konto er i øjeblikket låst fra at købe. Kontakt venligst Steam Support for at få mere information."
	"Checkout_Failed_DeclineError"								"Dit køb blev ikke gennemført.\nBetalingsformidleren har rapporteret en autoriseringsfejl. Vælg venligst en anden betalingsmetode."
	"Checkout_Failed_UseOther"									"Dit køb blev ikke gennemført.\nBetalingsformidleren har rapporteret en autoriseringsfejl. Vælg venligst en anden betalingsmetode."
	"Checkout_Failed_UseOtherFunding"							"Dit køb blev ikke gennemført.\nBetalingsformidleren har rapporteret et problem med finansieringskilden, som er tilknyttet din konto. Du kan enten rette dette problem gennem formidleren eller vælge en anden betalingsmetode."
	"Checkout_Failed_AddressError"								"Dit køb blev ikke gennemført.\nBetalingsformidleren har rapporteret et problem med adressen, som er tilknyttet din konto. Du kan enten rette dette problem gennem formidleren eller vælge en anden betalingsmetode."
	"Checkout_Failed_RegionError"								"Dit køb blev ikke gennemført.\nDin valgte betalingsmetode er ikke tilgængelig på det nuværende tidspunkt i dit land. Vælg venligst en anden betalingsmetode."
	"Checkout_Failed_BlockedAccountError"						"Dit køb blev ikke gennemført.\nBetalingsformidleren har rapporteret et problem med din konto. Kontakt venligst formidleren eller vælg en alternativ betalingsmetode."
	"Checkout_Failed_NotVerified"								"Dit køb er ikke blevet gennemført.\nBetalingsformidleren har rapporteret, at din konto skal bekræftes, eller at der skal indsættes penge, for at købet kan gennemføres. Kontakt formidleren, eller vælg en anden betalingsmetode."
	"Checkout_Failed_Finalize_AccountLocked"					"Dit køb blev ikke gennemført. Din konto er i øjeblikket låst fra at købe. Kontakt venligst Steam Support for at få mere information."

	"Checkout_VerifyEmail_Title"				"E-mailbekræftelse"
	"Checkout_VerifyEmail_Instructions"			"Bekræft din e-mailadresse med Steam."
	"Checkout_VerifyEmail_Description"			"Dette engangstrin hjælper os med at vedligeholde din Steam-kontos sikkerhed og er et krav for at kunne gennemføre dit køb med Steam.\n\nVi har lige sendt en besked fra Steam Support til din registrerede e-mailadresse hos {s:emailaddress}."
	"Checkout_VerifyEmail_CheckEmail"			"Tjek din e-mail hos {s:emailaddress} nu og klik på linket i beskeden fra Steam Support..."
	"Checkout_VerifyEmail_CanCompleteAfter"		"Dit køb kan derefter gennemføres når du vender tilbage til denne skærm."
	"Checkout_VerifyEmail_Success"				"Succes! Din e-mailadresse er blevet bekræftet."
	"Checkout_VerifyEmail_Thanks"				"Tak, fordi du hjælper os med at vedligeholde din kontos sikkerhed! Du kan nu fortsætte dit køb."

	"Checkout_PaymentStep_ShippingInfo"	"Forsendelsesinformation"
	"Checkout_PaymentStep_Method"	"BETALINGSINFO"
	"Checkout_PaymentStep_Review"	"Kurv + Køb"
	"Checkout_PaymentStep_GiftDelivery"	"Gavelevering"
	"Checkout_PaymentStep_GiftNote"	"Gavekort"

	"Checkout_Continue"							"Fortsæt"
	"Checkout_Processing"						"Arbejder"
	"Checkout_WaitExternalAuth"					"Venter på {s:payment_method}-autorisering gennem browser"
	"Checkout_Error"							"Der opstod en fejl. Prøv venligst igen."
	"Checkout_YourWallet"						"Din tegnebog"
	"Checkout_WalletCredit"						"Vil blive føjet til din Steam-tegnebog"

	"Checkout_GiftRecipient_Title"				"Gavelevering"
	"Checkout_GiftRecipient_HowToSend"			"Hvordan vil du sende din gave?"
	"Checkout_GiftRecipient_EmailGift"			"Send gaven via e-mail"
	"Checkout_GiftRecipient_EmailGiftAddress"			"E-mailadresse"
	"Checkout_GiftRecipient_SendToFriend"		"Send gaven direkte via Steam"
	"Checkout_GiftRecipient_SendToInventory"	"Opbevar gaven i mit inventar til at sende senere"
	"Checkout_GiftRecipient_EmailInstructions"	"Send min ven en e-mailbesked om gaven, inklusiv al den info, de får brug for, for at få Steam op at køre."
	"Checkout_GiftRecipient_EmailHeader"		"Modtagerens e-mailadresse"
	"Checkout_GiftRecipient_FriendInstructions"	"Vælg en ven fra listen nedenfor for at sende dit køb som en gave direkte til vedkommendes Steam-konto."
	"Checkout_GiftRecipient_FriendWishes"		"Ønsker sig {s:wish_for_games}"
	"Checkout_GiftRecipient_FriendOwns"			"Ejer allerede {s:already_owns_games}"
	"Checkout_GiftRecipient_Inventoryinstructions"	"Din gave vil blive på din konto til senere aflevering eller byttehandel. Du kan administrere dine gaver fra Steam-klienten eller ved at se dit Steam-inventar på din fællesskabsprofil."
	"Checkout_Sentiment_BestWishes"				"De bedste ønsker"
	"Checkout_Sentiment_BuckleUp"				"Spænd dig fast"
	"Checkout_Sentiment_Enjoy"					"Nyd det"
	"Checkout_Sentiment_GameOn"					"Spillet er i gang"
	"Checkout_Sentiment_HaveFun"				"God fornøjelse"
	"Checkout_Sentiment_KerBlam"				"Kaboom"
	"Checkout_Sentiment_OverOut"				"Skifter, slut"
	"Checkout_Sentiment_YouOweMe"				"Du skylder mig"
	"Checkout_Sentiment_YourTurn"				"Din tur"
	"Checkout_Sentiment_XOXO"					"XOXOXO"

	"Checkout_GiftNote_Title"					"Gavekort"
	"Checkout_GiftNote_Instructions"			"Gør din gave personlig med en lille hilsen"
	"Checkout_GiftNote_RecipientName"			"Modtagerens fornavn"
	"Checkout_GiftNote_Message"					"Gave-besked"
	"Checkout_GiftNote_MessageRemaining"		"({i:message_remaining} tegn tilbage)"
	"Checkout_GiftNote_Sentiment"				"Din hilsen"
	"Checkout_GiftNote_Signature"				"Din underskrift"

	"Checkout_PaymentMethod_Title"				"Betalingsmetode"
	"Checkout_PaymentMethod_Instructions"		"Vælg venligst en betalingsmetode"
	"Checkout_PaymentMethod_Secondary"			"Sekundær metode"
	"Checkout_PaymentMethod_CartNumber"			"Kortnummer"
	"Checkout_PaymentMethod_ExpirationDate"		"Udløbsdato"
	"Checkout_PaymentMethod_SecurityCode"		"Sikkerhedskode"
	"Checkout_PaymentMethod_SaveInfo"			"Gem mine betalingsoplysninger"
	"Checkout_PaymentMethod_MustSaveInfo"			"Dine betalingsoplysninger vil blive gemt, fordi din kurv indeholder et fornyende abonnement"
	"Checkout_PaymentMethod_ContainsRecurringSubscription"			"Dit køb indeholder ét eller flere emner, som opkræves i bestemte intervaller fremover. Steam vil bruge enhver gemt betalingsmetode til at opkræve pengene ved hver fornyelsesperiode. Hvis du ikke har nogen gemte betalingsmetoder på fornyelsestidspunktet, bruges pengene i din Steam-tegnebog til at betale."
	"Checkout_PaymentMethod_UpdatePayPal"	"For din egen sikkerheds skyld skal du godkende dit køb med PayPal igen."
	"Checkout_PaymentMethod_PayPalInstructions"	"PayPal-transaktioner godkendes gennem PayPal-websiden."
	"Checkout_PaymentMethod_ClickAndBuyInstructions" "ClickandBuy-transaktioner godkendes gennem ClickandBuy-websiden. Tryk på fortsæt for at åbne et nyt vindue der vil påbegynde transaktionen."
	"Checkout_PaymentMethod_ClickAndBuySaved"	"Oplysningerne om din ClickandBuy-konto blev gemt tidligere og vil blive anvendt igen for dette køb."
	"Checkout_PaymentMethod_PayPalSaved"	"Denne transaktionen bliver opkrævet på din PayPal-konto: {s:paypal_saved_account}"
	"Checkout_PaymentMethod_LogoHeader"			"Vi accepterer følgende sikre betalingsmetoder"
	"Checkout_PaymentMethod_VerifyCountry"		"Jeg bekræfter, at jeg bor i {s:country}"
	"Checkout_PaymentMethod_WalletLow"			"Din Steam-tegnebogssaldo er for lav til at dække denne transaktion!\n\nVælg venligst en betalingsmetode til at dække de resterende {s:purchase_balance}."
	"Checkout_PaymentMethod_ClickandBuy"		"ClickandBuy"
	"Checkout_PaymentMethod_BankName"           "Vælg en bank:"

	"Checkout_BillingInfo_Title"				"Faktureringsadresse"
	"Checkout_BillingInfo_FirstName"			"Fornavn"
	"Checkout_BillingInfo_LastName"				"Efternavn"
	"Checkout_BillingInfo_Address1"				"Faktureringsadresse"
	"Checkout_BillingInfo_Address2"				"Faktureringsadresse, linje 2"
	"Checkout_BillingInfo_Country"				"Land"
	"Checkout_BillingInfo_LiveInCountry"		"Jeg bor i øjeblikket i det land, der er valgt ovenfor"
	"Checkout_BillingInfo_City"					"By"
	"Checkout_BillingInfo_State"				"Stat"
	"Checkout_BillingInfo_PostCode"				"Postnummer"
	"Checkout_BillingInfo_PhoneNumber"			"Telefonnummer"
	"Checkout_BillingInfo_SelectState"			"Vælg stat"

	"Checkout_ShippingInfo_Title"				"Forsendelsesadresse"
	"Checkout_ShippingInfo_Address1"				"Forsendelsesadresse"
	"Checkout_ShippingInfo_Address2"				"Forsendelsesadresse, linje 2"
	"Checkout_ShippingInfo_ShippingRestrictions"	"Forsendelse af fysiske varer kan ikke leveres til postbokse, APO-, FPO- eller DPO-adresser og kan kun leveres til {s:country}. Sørg venligst for, at din adresse kun indeholder latinske tegn."
	"Checkout_ShippingInfo_ShippingRestrictions_US"	"Forsendelse af fysiske varer kan ikke leveres til postbokse, APO-, FPO- eller DPO-adresser og kan kun leveres til de 48 delstater i det kontinentale USA. Sørg venligst for, at din adresse kun indeholder latinske tegn."
	"Checkout_VerifyShippingInfo_Title" "Forslag til forsendelsesadresse"
	"Checkout_ShippingInfo_ShippingAddressSuggestion" "Vi har fundet et forslag til din forsendelsesadresse"
	"Checkout_ShippingInfo_OurSuggestion" "Vores forslag:"
	"Checkout_ShippingInfo_YouEntered" "Du indtastede:"
	"Checkout_ShippingInfo_OurSuggestionButton" "Brug vores forslag"
	"Checkout_ShippingInfo_YouEnteredButton" "Brug hvad du indtastede"
	"Checkout_ShippingInfo_cannot_ship" "Vi kan ikke sende din købsordre til adressen, du har angivet."
	"Checkout_ShippingInfo_cannot_ship_fields_too_long" "Vi kan ikke sende din købsordre til adressen, du har angivet, fordi nogle dele af din adresse er for lange. Dit fulde navn og hvert adressefelt kan kun være op til 35 tegn langt."
	"Checkout_ShippingInfo_cannot_ship_missing_fields" "Vi kan ikke sende din købsordre til adressen, du har angivet, fordi nogle dele af din adresse mangler eller ser ugyldige ud."
	"Checkout_ShippingInfo_cannot_ship_no_apo_fpo_po" "Vi kan ikke sende din købsordre til postbokse, APO-, FPO- eller DPO-adresser."
	"Checkout_ShippingInfo_cannot_ship_invalid_characters" "Vi kan ikke sende din købsordre til adressen, du har angivet, fordi den indeholder ikke-latinske tegn."
	"Checkout_ShippingInfo_cannot_ship_us_territories" "Vi kan ikke sende din ordre, fordi det angivne postnummer hører til en region uden for de 48 delstater i det kontinentale USA."
	"Checkout_ShippingInfo_cannot_ship_unsupported_postal_code" "Vi kan ikke sende din købsordre til adressen, du har angivet, fordi det ser ud til, at dit postnummer er i en særlig region, hvor vi ikke kan sende til."


	"Checkout_Review_Title"						"Gennemse og køb"
	"Checkout_Review_Purchase"					"Køb"
	"Checkout_Review_EditPayment"				"Rediger betalingsmetode"
	"Checkout_Review_AgreeTerms"				"Jeg erklærer mig enig i vilkårene i Steam-abonnentaftalen (sidst opdateret d. 16. marts 2015.)"
	"Checkout_Review_AgreeTerms2"				"Jeg accepterer betingelserne i Steam-abonnentaftalen (sidst opdateret {s:ssa_last_update}.)"
	"Checkout_Review_PaymentMethod"				"Betalingsmetode"
	"Checkout_Review_GiftOptions"				"Gavemuligheder"
	"Checkout_Review_BillingAddress"			"Faktureringsadresse"
	"Checkout_Review_ShippingAddress"			"Forsendelsesadresse"
	"Checkout_Review_Phone"						"Telefon"
	"Checkout_Review_Subtotal"					"Subtotal"
	"Checkout_Review_Shipping"			"Forsendelse og håndtering"
	"Checkout_Review_Tax"						"Skat"
	"Checkout_Review_Total"						"I alt"
	"Checkout_Review_NoGift"					"Ingen. Dette køb er til din egen konto."
	"Checkout_Review_CreditCard"				"{s:card_type} slutter på {s