								"Knap"
	"SettingsController_Save"										"GEM"
	"SettingsController_ExitAndClearButtons"					"RYD OG AFSLUT"
	"SettingsController_ButtonBind"								"Knap {i:button}"
	"SettingsController_AxisBind"								"Akse {i:axis}"
	"SettingsController_HatBind"								"Hat {i:hat}.{i:mask}"
	"SettingsController_NeedMoreBinds"					"Du skal binde følgende knapper: {s:missingbuttons}"
	"SettingsController_SaveBeforeExit"					"Afslut uden at gemme ændringer?"
	"SettingsController_LeftStickX"							"Venstre styrepind x"
	"SettingsController_LeftStickY"							"Venstre styrepind Y"
	"SettingsController_RightStickX"						"Højre styrepind X"
	"SettingsController_RightStickY"						"Højre styrepind Y"
	"SettingsController_TriggerLeft"						"Venstre aftrækker"
	"SettingsController_TriggerRight"						"Højre aftrækker"
	"SettingsController_A"											"Primær handling"
	"SettingsController_B"											"Gå tilbage"
	"SettingsController_X"											"Sekundær handling"
	"SettingsController_Y"											"Tertiær handling"
	"SettingsController_Start"									"Start"
	"SettingsController_Back"										"Back"
	"SettingsController_Guide"									"Guide"
	"SettingsController_LeftStick"							"Klik med venstre styrepind"
	"SettingsController_RightStick"							"Klik med højre styrepind"
	"SettingsController_LeftShoulder"						"Venstre skulder"
	"SettingsController_RightShoulder"					"Højre skulder"
	"SettingsController_Up"											"Retningsknap, op"
	"SettingsController_Down"										"Retningsknap, ned"
	"SettingsController_Left"										"Retningsknap, venstre"
	"SettingsController_Right"									"Retningsknap, højre"
	"SettingsController_ShareTitle"							"Del denne controller-definition?"
	"SettingsController_Share"									"Hjælp venligst med at understøtte denne controller for andre brugere ved at give den et navn"
	"SettingsController_ShareExample"						"For eksempel, \"Logitech A710\""
	"SettingsController_ControllerType"						"\nVælg typen af controller:"
	"SettingsController_CommitUpload"						"Ja. Upload!"
	"SettingsController_CommitCancel"						"Nej tak."
	"SettingsController_NoneDetected"						"Ingen kontroller registreret."
	"SettingsController_XInputController"				"XInput-controller"
	"SettingsController_ResetButtons"						"NULSTIL"
	"SettingsController_TurnOffOnQuit"					"Sluk når Big Picture lukkes"
	"SettingsController_PS4Support"						"Konfigurationssupport til PlayStation"
	"SettingsController_XBoxSupport"					"Xbox-konfigurationssupport"
	"SettingsController_XBoxDriver"						"  Udvidet funktionsunderstøttelse til Xbox"
	"SettingsController_XBoxDriverInstall"				"          Installer Xbox-funktionsdriver"
	"SettingsController_XBoxDriverUpdate"				"          Opdater Xbox-funktionsdriver"
	"SettingsController_XBoxDriverUninstall"			"          Afinstaller Xbox-funktionsdriver"
	"SettingsController_XboxDriverInstall_Title"		"Installation af Xbox-driver"
	"SettingsController_XboxDriverInstall_Success"		"Driveren er installeret. Vil du genstarte for at aktivere den nu?"
	"SettingsController_XboxDriverInstall_ErrorPendingReboot"	"Du skal genstarte din computer og vende tilbage bagefter for at installere driveren. Genstart nu?"
	"SettingsController_XboxDriverInstall_ServiceFailure"		"Driverinstallationen mislykkedes. Kører du Steam som en almindelig bruger, og har Steam-tjenesten de seneste opdateringer?"
	"SettingsController_XboxDriverInstall_Failure"		"Installation af driveren mislykkedes. Fejlkode: {d:error}"
	"SettingsController_XboxDriverUninstall_Title"		"Afinstallation af Xbox-driver"
	"SettingsController_XboxDriverUninstall_Success"	"Driveren blev slettet. Vil du genstarte nu for at deaktivere den?"
	"SettingsController_XboxDriverUninstall_ServiceFailure"	"Sletning af driveren mislykkedes. Fungerer Steam-tjenesten, og har den de seneste opdateringer?"
	"SettingsController_XboxDriverUninstall_Failure"	"Sletning af driveren mislykkedes. Fejlkode: {s:error}"
	"SettingsController_XboxDriverRestart_Now"			"GENSTART"
	"SettingsController_XboxDriverRestart_Later"		"SENERE"
	"SettingsController_SwitchSupport"					"Switch Pro-konfigurationssupport"
	"SettingsController_NintendoLayout"					" Brug Nintendos knaplayout"
	"SettingsController_GenericGamepadSupport"			"Generisk gamepad-konfigurationsunderstøttelse"
	"SettingsController_CheckGuideButton"				"Guide-knappen sætter Steam i fokus"
	"SettingsController_PreviewWaterMark"				"FORHÅNDSVIS"
	"SettingsController_BindListenWaterMarkTitle"		"VENTER PÅ BINDING"
	"SettingsController_BindListenWaterMark"			"Tryk på muse-, tastatur- eller gamepadinput for at binde pågældende, eller hold enten Escape-tasten eller B-knappen nede for at afslutte tilstand"
	"SettingsController_Support"						"SUPPORT"
	"SettingsController_Calibrate"						"KALIBRER"
	"SettingsController_EnableBindingMode"				"DEFINER LAYOUT"
	"SettingsController_Accounts_None"					"Ingen"
	"SettingsController_Accounts_DeregAYSTitle"			"Er du sikker?"
	"SettingsController_Accounts_DeregAYSDesc"			"Hvis du afregistrerer denne konto, vil dine konfigurationer ikke længere følge med din controller, når du logger på kontoen."
	"SettingsController_Deregister"						"AFREGISTRER KONTO"
	"SettingsController_SwitchControllerAccount"		"SKIFT TIL DENNE KONTO"
	"SettingsController_AutoCalibrateDuringUse"			"KALIBRER GYRO AUTOMATISK UNDER BRUG"
	"Controller_Registration_TurnOnSound"				"Lyd ved opstart:"
	"Controller_Registration_TurnOffSound"				"Lyd ved nedlukning:"
	"Controller_Registration_PlayerSlotLED"				"LED-lys for spillernummer:"
	"SettingController_HapticSound_Default"				"Standardlyd"
	"SettingController_HapticSound_0"					"Varm og glad"
	"SettingController_HapticSound_1"					"Angriber"
	"SettingController_HapticSound_2"					"Controller bekræftet"
	"SettingController_HapticSound_3"					"Sejr!"
	"SettingController_HapticSound_4"					"Så står vi op"
	"SettingController_HapticSound_5"					"Stump"
	"SettingController_HapticSound_6"					"Varm opstart"
	"SettingController_HapticSound_7"					"Næste level"
	"SettingController_HapticSound_8"					"Ryst det af"
	"SettingController_HapticSound_9"					"Adgang nægtet"
	"SettingController_HapticSound_10"					"Deaktiver"
	"SettingController_HapticSound_11"					"Opdagelse"
	"SettingController_HapticSound_12"					"Triumf"
	"SettingController_HapticSound_13"					"Mann'en"
	"Controller_Registration_Rumble"					"Rumle-præference:"
	"Controller_Registration_RumbleSC"					"[Eksperimentelt] Rumleemulering:"
	"Controller_Registration_Haptics"					"Haptik-præference:"


	"Settings_SteamControllerSupport"					"Steam Controller-support"
	"Settings_SteamControllerSupport_ExitNotification"	"Tryk og hold B-knappen for at afslutte"
	"Settings_SteamControllerSupport_SuccessNotification"	"Controller-test gennemført"
	"SettingsControllerSupport_SerialNumber"			"Serienummer: {s:serialnum}"
	"SettingsControllerSupport_BoardRev"				"Printplade-revision: {s:boardrev}"
	"SettingsControllerSupport_FirmwareRev"				"Firmware-revision: {s:fwrev}"
	"SettingsControllerSupport_FirmwareDate"			"Firmware-dato: {s:fwdate}"
	"SettingsControllerSupport_BootloaderRev"			"Bootloader-revision: {s:blrev}"
	"SettingsControllerSupport_BootloaderDate"			"Bootloader-dato: {s:bldate}"
	"SettingsControllerSupport_RadioRev"				"Radio-firmwarerevision: {s:radiorev}"
	"SettingsControllerSupport_RadioDate"				"Radio-firmwaredato: {s:radiodate}"
	"SettingsControllerSupport_LeftTriggerRangeTesting"		"Tryk den venstre aftrækker helt ned:"
	"SettingsControllerSupport_RightTriggerRangeTesting"	"Tryk den højre aftrækker helt ned:"
	"SettingsControllerSupport_LeftPadTesting"				"Rør hele overfladen på den venstre trackpad:"
	"SettingsControllerSupport_RightPadTesting"				"Rør hele overfladen på den højre trackpad:"
	"SettingsControllerSupport_JoystickRangeTesting"		"Bevæg joysticket i en fuld cirkel:"
	"SettingsControllerSupport_ButtonsTesting"				"Tryk på alle controller-knapperne:"
	"SettingsControllerSupport_LeftHapticsTesting"			"Pulserer den venstre haptik (Tryk på A-knappen for at fortsætte):"
	"SettingsControllerSupport_RightHapticsTesting"			"Pulserer den højre haptik (Tryk på A-knappen for at fortsætte):"
	"SettingsControllerSupport_TestingComplete"				"Test gennemført!"
	"SettingsController_FirmwareRecovery_Title"		"Firmware trin for gendannelsesproces"
	"SettingsController_FirmwareRecovery_Body"		"1) Træk alle Steam-controller stik ud på din computer.\n2) Fjern batterierne fra enheden, som skal gendannes.\n3) Hold den højre aftrækker nede indtil totrins-knappen er trykket og tilslut enheden igen. \nDette kan generere et pop-vindue.\n4) Tryk på START-knappen"
	"SettingsController_FirmwareRecoveryWarning_Title"	"Firmware-gendannelsesproces"
	"SettingsController_FirmwareRecoveryWarning_Body"	"Denne proces er kun til gendannelse af enheder, der ikke kunne opdateres eller specificeres af Steam. Hvis din enhed vises i Steam og ikke udløser en firmware opdateringsprompt, bruger den den nyeste firmware."
	"Settings_Store"				"Butik"
	"SettingsStore_FilterToggle"	"Lad mig se alt indhold uden hensyn til min opsætning"
	"SettingsStore_Description1"	"Din visning af Steam-butikken er lavet for at vise dig de emner, du kan spille på denne maskine."
	"SettingsStore_Description2"	"Dit operativsystem, din inputenhed og andre aktive Remote Play-forbindelser bruges til at bestemme, hvilket indhold der er kompatibelt med din nuværende opsætning."
	"SettingsStore_Description3"	"Du ser i øjeblikket Steam-butiksindholdet lavet til"
	"SettingsStore_Description4"	"Følgende avancerede indstilling tilføjer en menu til butiksvisninger, hvilket lader dig skifte nemt mellem at få vist lokalt spilbare titler og alt indhold, som er tilgængeligt på Steam. Der kan være bemærkninger på visse genstande, som angiver særlige krav såsom et keyboard og en mus eller en Remote Play-forbindelse."

	"SettingsStore_OSConfig_Win" "Windows (denne maskine)"
	"SettingsStore_OSConfig_OSX" "OS X (denne maskine)"
	"SettingsStore_OSConfig_SteamOS" "SteamOS (denne maskine)"
	"SettingsStore_OSConfig_Linux" "Linux (denne maskine)"
	"SettingsStore_XInputConfig" "Controller"
	"SettingsStore_SteampadConfig" "Steam Controller"
	"SettingsStore_KeyboardConfig"	"Tastatur og mus"
	"SettingsStore_RemoteOSConfig_Win" "Windows (din Remote Play-enhed)"
	"SettingsStore_RemoteOSConfig_OSX" "OS X (din Remote Play-enhed)"
	"SettingsStore_RemoteOSConfig_Linux" "SteamOS eller Linux (din Remote Play-enhed)"

	"Settings_ComingSoon"			"Denne funktion er ikke klar endnu, men kommer snart!"

	"SupportMessages_Title"			"Support-besked"
	"SupportMessages_Text"			"Du har en besked fra Steam Support."
	"SupportMessages_View"			"Vis besked"

	"Search_Header"                 "Søg"
	"Search_NoResultsFound"			"Ingen resultater fundet"

	"Search_NoInputEntered"			"Indtast søgetekst"
	"Search_SearchError"			"Der opstod en fejl under søgningen"
	"Search_GamesICanPlay"			"Spil jeg spiller ({d:game_count})"
	"Search_GamepadGames"			"Spil med controller ({d:game_count})"
	"Search_OtherGames"				"Andre ({d:game_count})"

	"Debugger_PaintInfo"			"Vis farveinfo"
	"Debugger_Style"				"Stil"
	"Debugger_Computed"				"Beregnet"
	"Debugger_Measurements"			"Målinger:"
	"Debugger_Misc"					"Diverse:"
	"Debugger_Properties"			"Egenskaber:"
	"Debugger_StyleFileLink"		"{s:stylefile}"
	"Debugger_LayoutFileLink"		"{s:layoutfile}"
	"Debugger_LayoutFileLink_Code"	"Fra XML/kode"
	"Debugger_InheritedStyleHeader"	"Arvet fra"
	"Debugger_Save"					"Gem alle ændringer"
	"Debugger_Revert"				"Annuller alle ændringer"
	"Debugger_PanelStyleInvalid"	"Stile ændret under redigering! Tryk F5 for at genindlæse viste stile."
	"Debugger_AnimationHeader"		"Animations-keyframes"
	"Debugger_DevInfo"				"Vis udviklerinfo"

	"Store_Cart"					"KURV"
	"Store_Search"					"SØG"
	"Store_Search_ViewResults"			"VIS RESULTATER"
	"Store_AppName"					"{s:appname}"
	"Store_AvailableNow"			"Tilgængelig nu"
	"Store_AvailableNowPackage"		"Tilgængelig nu og inkluderer det følgende"
	"Store_ComingSoon"				"Kommer snart"
	"Store_ComingSoon_Date"			"Kommer snart - {s:release_date}"
	"Store_Available_Date"			"Tilgængelig den {s:release_date}"
	"Store_Purchase"				"KØB"
	"Store_Description"				"BESKRIVELSE"
	"Store_DescriptionOverview"		"Historie & funktioner"
	"Store_DescriptionReadFull"		"Læs den fulde beskrivelse"
	"Store_Details"					"OPLYSNINGER"
	"Store_Note"					"BEMÆRK"
	"Store_RequiresOverview_StreamingAndController" "Kræver yderligere streaming-opsætning og -enheder"
	"Store_RequiresOverview_Streaming" "Kræver streaming-opsætning"
	"Store_RequiresOverview_Controller" "Kræver input"
	"Store_RequiresOverview_EarlyAccess" "Tidlig adgang"
	"Store_Requires_Streaming" "Dette spil kræver en Steam Remote Play-forbindelse for at kunne spilles her"
	"Store_Requires_Controller" "Dette spil kræver en Steam Controller eller et tastatur og en mus for at kunne spilles her"
	"Store_LearnMore"			"Lær mere"
	"Store_Reviews"					"ANMELDELSER"
	"Store_ReviewsOverview"			"Point + Anmeldelser"
	"Store_ViewSystemRequirements"	"Vis systemkrav"
	"Store_SupportedLanguages"		"Understøttede sprog"
	"Store_ViewLegal"				"Læs juridiske og DRM-bemærkninger"
	"Store_Genres"					"Genre"
	"Store_Metacritic"				"Metacritic"
	"Store_MetacriticScore"			"{i:metacritic_score}"
	"Store_MetacriticScorePossible"	"/100"
	"Store_ErrorWhileLoadingApp"	"Steam kunne ikke hente data for denne titel. Prøv venligst igen."
	"Store_ScreenshotDescription"	"{s:appname}-skærmbilleder"
	"Store_SlideshowDescription"	"{s:item_name}"
	"Store_GenreTitle"				"Genrer"
	"Store_FullAppDescriptionTitle"	"Beskrivelse"
	"Store_SystemRequirementsTitle"	"Systemkrav"
	"Store_PCRequirementsHeader"	"<span class=\"Header\">PC-krav</span>"
	"Store_MacRequirementsHeader"	"<span class=\"Header\">Mac-krav</span>"
	"Store_LinuxRequirementsHeader"	"<span class=\"Header\">Linux-krav</span>"
	"Store_Minimum"					"<strong>Minimum</strong>"
	"Store_Recommended"				"<strong>Anbefalet</strong>"
	"Store_FullLegalTitle"			"Juridisk og Digital Rights Management"
	"Store_DRMHeader"				"<span class=\"Header\">DRM-bemærkning</span><br>"
	"Store_LegalHeader"				"<span class=\"Header\">Juridisk bemærkning</span><br>"
	"Store_EnterBirthday"			"Indtast venligst din fødselsdato for at fortsætte"
	"Store_AgeRestricted"			"Beklager, men du har ikke tilladelse til at se dette materiale på nuværende tidspunkt."
	"Store_Unavailable"				"Steam-butikken er utilgængelig på nuværende tidspunkt. Prøv venligst igen senere."
	"Store_FeaturedDiscount"		"{i:featured_discount_pct}%"
	"Store_EarlyAccess"				"Dette er en titel med tidlig adgang, hvilket betyder, at den stadig er under udvikling"

	"Store_Filter_AllGames"			"Alle produkter"
	"Store_Filter_GamesICanPlay"	"Alle jeg kan spille"
	"Store_Filter_GamepadGames"		"Spil med controller"

	"Store_Platform_Windows"		"Windows"
	"Store_Platform_Mac"			"Mac"
	"Store_Platform_Linux"			"SteamOS + Linux"
	"Store_Platform_StreamingVideo"		"Steam-video"
	"Store_Category_FullController" 	"Controller-understøttelse"
	"Store_Category_Controller"		"Bagudkompatibel understøttelse"
	"Store_Category_SteamController"	"Indbygget understøttelse"
	"Store_Category_LegacyController"	"Bagudkompatibel understøttelse"
	"Store_Category_Achievements"	"Præstationer"
	"Store_Category_Cloud"			"Steam Cloud"
	"Store_Category_Singleplayer"	"Singleplayer"
	"Store_Category_Multiplayer"	"Multiplayer"
	"Store_Category_Coop"			"Co-op"
	"Store_Category_Leaderboards"	"Førertavler"

	"Store_Friends"					"Fællesskab"
	"Store_AchievementsGame"		"{i:achievements_game_count} præstationer"
	"Store_FriendsPlayGame"			"{i:friend_play_count} venner ejer dette spil"
	"Store_FriendPlaysGame"			"{i:friend_play_count} ven ejer dette spil"
	"Store_FriendsWantGame"			"{i:friend_want_count} venner ønsker sig dette spil"
	"Store_FriendWantsGame"			"{i:friend_want_count} ven vil have dette spil"
	"Store_FriendRecommended"		"Anbefalet af venner ({i:friend_recommend_count})"
	"Store_FriendCommunityGroups"	"Find fællesskabsgrupper"
	"Store_FriendVisitForums"		"Vis fællesskabsdiskussioner"
	"Store_FriendsOfficialWebsite"	"Besøg officielt websted"

	"Store_PackagePurchaseSection_IndividualPrice"	"Prisen på de individuelle spil"
	"Store_PackagePurchaseSection_Bundle"			"Bundt-pris"
	"Store_PackagePurchaseSection_BundleSavings"	"Med dette bundt sparer du"

	"Store_AppPurchaseSection_Options"			"Købsmuligheder({i:purchase_option_count})"
	"Store_NotAvailableForPurchase"				"Ikke tilgængeligt til køb"
	"Store_AppPurchaseSection_PurchaseDLC"		"Gennemse tilgængelig DLC ({i:purchase_dlc_count})"
	"Store_AppPurchaseSection_Demo"				"Download gratis demo"
	"Store_AppPurchaseSection_AddToWishlist"	"Føj til ønskeliste"
	"Store_AppPurchaseSection_AddingToWishlist"	"Føjer til ønskeliste"
	"Store_AppPurchaseSection_ViewWishlist"		"Vis i ønskeliste"
	"Store_AppPurchaseSection_DLC"				"Indhold, der kan downloades"
	"Store_AppPurchaseSection_RequiresBase"		"Kræver grundspillet {s:base_game} på Steam for at kunne spilles."
	"Store_AppPurchaseSection_ViewBaseGame"		"Vis grundspil"
	"Store_AppPurchaseSection_ViewInLibrary"	"Vis i bibliotek"
	"Store_AppPurchaseSection_AddToAccount"		"Føj til bibliotek"

	"Steam_Error"					"Fejl"
	"Steam_AddToAccount_Error"			"Beklager, der opstod en fejl i forsøget på at tilføje produktet til din konto."

	"Steam_Success"					"Succes"
	"Steam_AddToAccount_Success"				"Pakken er blevet tilføjet til din konto."
	"Steam_AddToAccount_ViewGame"				"VIS I BIBLIOTEK"
	"Steam_AddToAccount_ViewAllGames"			"VIS ALLE SPIL"

	"Store_AppPurchaseOptions_Title"			"{i:purchase_option_count} købsmuligheder"
	"Store_AppPurchaseOptions_TitleNoCount"			"Købsindstillinger"
	"Store_AppPurchaseOptions_AddToCart"		"Læg i kurv"
	"Store_AppPurchaseOptions_InCart"			"I kurven"
	"Store_AppPurchaseOptions_PackageDetails"	"Vis pakkeoplysninger"
	"Store_AppPurchaseOptions_AppDetails"		"Vis spiloplysninger"
	"Store_AppPurchaseOptions_VideoDetails"		"Vis videodetaljer"
	"Store_AppPurchaseOptions_PackageOneItem"	"Inkluderer"
	"Store_AppPurchaseOptions_PackageMultiple"	"Indeholder {i:package_item_count} emner"
	"Store_AppPurchaseOptions_LoadingError"		"Der opstod en fejl under indlæsningen af købsmuligheder. Prøv venligst igen."

	"Store_AppDlc_Title"						"DLC