ion roterer trackballen i kort tid, efter den svirpes, og stopper hurtigt op."
	"ControllerBinding_FrictionMouseJoystick_None" "Trackball-friktion - Ingen"
	"ControllerBinding_FrictionMouseJoystick_None_Description" "Uden friktion vil trackballen, uden indgriben, rulle for evigt, efter den er blevet sat i gang."
	"ControllerBinding_VerticalFrictionMouseJoystick" "Lodret friktion"
	"ControllerBinding_VerticalFrictionMouseJoystick_Description" "Lodret friktion bestemmer, hvor hurtigt den lodrette bevægelse stopper i forhold til den vandrette bevægelse. Ved 50% på slideren stopper de lige hurtigt. Hvis den er mindre end halvvejs, stopper bevægelsen langsommere. Hvis den er over halvvejs, stopper den hurtigere. I spil, hvor du styrer kameraet, er det normalt hensigtsmæssigt at have høj lodret friktion, så svirp primært bruges til at dreje kameraet langs den vandrette akse."
	"ControllerBinding_VerticalSensitivityMouseJoystick" "Lodret følsomhed"
	"ControllerBinding_VerticalSensitivityMouseJoystick_Description" "Lodret følsomhed bestemmer, hvor meget lodret bevægelse der forekommer i forhold til vandret bevægelse. Ved 50% på slideren er der lige meget bevægelse. Hvis den er mindre end halvvejs, er lodret bevægelse langsommere end vandret bevægelse. Hvis den er mere end halvvejs, er lodret bevægelse hurtigere end vandret bevægelse."
	"ControllerBinding_SmoothingMouseJoystick" "Udjævning"
	"ControllerBinding_SmoothingMouseJoystick_Description" "Udjævning hjælper med at fjerne støj og rysten fra musen. Mindre værdier resulterer i mindre filtrering, mens højere værdier betyder mere filtrering og udjævning."
	"ControllerBinding_AccelerationMouseJoystick" "Acceleration"
	"ControllerBinding_AccelerationMouseJoystick_Description" "Acceleration vil få hurtigere bevægelser til at forårsage mere musebevægelse i forhold til langsomme bevægelser ved samme plads tilbagelagt på fladen."
	"ControllerBinding_AccelerationMouseJoystick_Off" "Acceleration - Fra"
	"ControllerBinding_AccelerationMouseJoystick_Off_Description" "Uden acceleration vil bevægelse altid være i forholdet 1:1, hvor afstanden tilbagelagt på fladen altid resulterer i det samme output i spillet, uanset hastigheden."
	"ControllerBinding_AccelerationMouseJoystick_Low" "Acceleration - Lav"
	"ControllerBinding_AccelerationMouseJoystick_Low_Description" "Med lav acceleration vil bevægelse være lidt accelereret, hvor hurtigere bevægelser gør output i spil lidt større ved højere hastigheder ved samme afstand dækket på den fysiske flade."
	"ControllerBinding_AccelerationMouseJoystick_Medium" "Acceleration - Medium"
	"ControllerBinding_AccelerationMouseJoystick_Medium_Description" "Med medium acceleration vil bevægelse være rimelig accelereret, hvor hurtigere bevægelser gør output i spil en del større ved højere hastigheder ved samme afstand dækket på den fysiske flade."
	"ControllerBinding_AccelerationMouseJoystick_High" "Acceleration - Høj"
	"ControllerBinding_AccelerationMouseJoystick_High_Description" "Med høj acceleration vil bevægelse være meget accelereret, hvor hurtigere bevægelser gør output i spil ekstremt stort ved højere hastigheder ved samme afstand dækket på den fysiske flade."
	"ControllerBinding_AccelerationGyroMouseJoystick" "Acceleration"
	"ControllerBinding_AccelerationGyroMouseJoystick_Description" "Acceleration vil få hurtigere bevægelser til at forårsage mere musebevægelse i forhold til langsomme bevægelser ved samme plads tilbagelagt på fladen."
	"ControllerBinding_AccelerationGyroMouseJoystick_Off" "Acceleration - Fra"
	"ControllerBinding_AccelerationGyroMouseJoystick_Off_Description" "Uden acceleration vil bevægelse altid være i forholdet 1:1, hvor afstanden tilbagelagt på fladen altid resulterer i det samme output i spillet, uanset hastigheden."
	"ControllerBinding_AccelerationGyroMouseJoystick_Low" "Acceleration - Lav"
	"ControllerBinding_AccelerationGyroMouseJoystick_Low_Description" "Med lav acceleration vil bevægelse være lidt accelereret, hvor hurtigere bevægelser gør output i spil lidt større ved højere hastigheder ved samme afstand dækket på den fysiske flade."
	"ControllerBinding_AccelerationGyroMouseJoystick_Medium" "Acceleration - Medium"
	"ControllerBinding_AccelerationGyroMouseJoystick_Medium_Description" "Med medium acceleration vil bevægelse være rimelig accelereret, hvor hurtigere bevægelser gør output i spil en del større ved højere hastigheder ved samme afstand dækket på den fysiske flade."
	"ControllerBinding_AccelerationGyroMouseJoystick_High" "Acceleration - Høj"
	"ControllerBinding_AccelerationGyroMouseJoystick_High_Description" "Med høj acceleration vil bevægelse være meget accelereret, hvor hurtigere bevægelser gør output i spil ekstremt stort ved højere hastigheder ved samme afstand dækket på den fysiske flade."
	"ControllerBinding_DoubleTapMouseJoystick" "Binding for dobbelttap"
	"ControllerBinding_DoubleTapMouseJoystick_Description" "En knap kan sendes, når du dobbelttrykker på knappen. Et tryk kræver ikke et helt klik, bare et hurtigt dobbelttryk på knappen."
	"ControllerBinding_DoubleTapDurationMouseJoystick" "Varighed for dobbelttap"
	"ControllerBinding_DoubleTapDurationMouseJoystick_Description" "\"Varighed for dobbelttap\" angiver tiden mellem berøringer, der kræves for at registrere et dobbelttap. Lavere værdier kræver et meget hurtigt dobbelttap, alt imens højere værdier tillader lang pause mellem berøringerne."
	"ControllerBinding_DoubleTapBeepMouseJoystick" "Bip ved dobbelttap"
	"ControllerBinding_DoubleTapBeepMouseJoystick_Description" "\"Bip ved dobbelttap\" får controlleren til at bippe, når der sendes et dobbelttap."
	"ControllerBinding_DoubleTapBeepMouseJoystick_On" "Bip ved dobbelttap - Til"
	"ControllerBinding_DoubleTapBeepMouseJoystick_On_Description" "\"Bip ved dobbelttap\" får controlleren til at bippe, når der sendes et dobbelttap."
	"ControllerBinding_DoubleTapBeepMouseJoystick_Off" "Bip ved dobbelttap - Fra"
	"ControllerBinding_DoubleTapBeepMouseJoystick_Off_Description" "Der sendes ikke et bip, når controlleren dobbelttappes."
	"ControllerBinding_MouseTriggerClampMouseJoystick" "Musedæmpning ved aftrækkertryk"
	"ControllerBinding_MouseTriggerClampMouseJoystick_Description" "Musens bevægelser kan dæmpes, mens aftrækkeren holdes nede. Dette kan hjælpe med at korrigere utilsigtet bevægelse, mens aftrækkeren holdes nede."
	"ControllerBinding_EdgeSpinRadiusMouseJoystick" "Radius for fortsat bevægelse"
	"ControllerBinding_EdgeSpinRadiusMouseJoystick_Description" "Hvis der er angivet en hastighed for fortsat bevægelse, så vil musen fortsætte med at sende input med konstant hastighed i den angivne retning, hvis man holder uden for fladens radius. Slideren kan visualiseres som at forlænge en radius fra centrum og udad, hvor helt til venstre betyder, at der altid er fortsat bevægelse, og helt til højre betyder, at bevægelse kun fortsætter, når man holder helt ude i kanten."
	"ControllerBinding_EdgeSpinScaleMouseJoystick" "Hastighed for fortsat bevægelse"
	"ControllerBinding_EdgeSpinScaleMouseJoystick_Description" "Hvis der er angivet en hastighed for fortsat bevægelse, så vil musen fortsætte med at sende input med konstant hastighed i den angivne retning, hvis man holder uden for fladens radius."
	"ControllerBinding_InvertXMouseMouseJoystick" "Inverter vandret akse"
	"ControllerBinding_InvertXMouseMouseJoystick_Description" "Hvis slået til vil musen bevæge sig til højre, når du bevæger til venstre på fladen. Omvendt vil musen bevæge sig til venstre, når du bevæger til højre på fladen. Bemærk at spilindstillinger ofte også har denne indstilling, så du skal sikre dig, at de ikke ophæver hinanden."
	"ControllerBinding_InvertXMouseMouseJoystick_On" "Inverter vandret akse - Til"
	"ControllerBinding_InvertXMouseMouseJoystick_On_Description" "Hvis slået til vil musen bevæge sig til højre, når du bevæger til venstre på fladen. Omvendt vil musen bevæge sig til venstre, når du bevæger til højre på fladen. Bemærk at spilindstillinger ofte også har denne indstilling, så du skal sikre dig, at de ikke ophæver hinanden."
	"ControllerBinding_InvertXMouseMouseJoystick_Off" "Inverter vandret akse - Fra"
	"ControllerBinding_InvertXMouseMouseJoystick_Off_Description" "Musens vandrette akse vil fungere normalt med bevægelse venstre på fladen svarende til bevægelse venstre med musen."
	"ControllerBinding_InvertMouseYMouseJoystick" "Inverter lodret akse"
	"ControllerBinding_InvertMouseYMouseJoystick_Description" "Hvis slået til vil musen bevæge sig nedad, når du bevæger opad på fladen. Omvendt vil musen bevæge sig opad, når du bevæger nedad på fladen. Bemærk at spilindstillinger ofte også har denne indstilling, så du skal sikre dig, at de ikke ophæver hinanden."
	"ControllerBinding_InvertMouseYMouseJoystick_On" "Inverter lodret akse - Til"
	"ControllerBinding_InvertMouseYMouseJoystick_On_Description" "Hvis slået til vil musen bevæge sig nedad, når du bevæger opad på fladen. Omvendt vil musen bevæge sig opad, når du bevæger nedad på fladen. Bemærk at spilindstillinger ofte også har denne indstilling, så du skal sikre dig, at de ikke ophæver hinanden."
	"ControllerBinding_InvertMouseYMouseJoystick_Off" "Inverter lodret akse - Fra"
	"ControllerBinding_InvertMouseYMouseJoystick_Off_Description" "Musens lodrette akse vil fungere normalt med bevægelse opad på fladen svarende til bevægelse opad med musen."
	"ControllerBinding_MouseMoveThresholdMouseJoystick" "Tærskel for bevægelse"
	"ControllerBinding_MouseMoveThresholdMouseJoystick_Description" "Musen vil opsamle bevægelse indtil tærsklen passeres og kun derefter sende bevægelse. Indstillingen er påtænkt brug med applikationer, der udviser aggressiv filtrering/fastklemning af musen, hvilket kan få små bevægelser til at gå tabt, men bør generelt ikke kræves. Ideelt set bør dette være så lille en værdi som muligt, samtidig med at der ikke tabes input fra små bevægelser."
	"ControllerBinding_GyroButtonMouseJoystick" "Gyro: Aktiveringsknap"
	"ControllerBinding_GyroButtonMouseJoystick_Description" "Gyroinputtet kan kun aktiveres, når der trykkes på en knap."
	"ControllerBinding_GyroButtonMouseJoystick_GyroNone" "Gyro: Aktiveringsknap - Altid til"
	"ControllerBinding_GyroButtonMouseJoystick_GyroNone_Description" "Gyroinputtet er altid aktivt."
	"ControllerBinding_GyroButtonMouseJoystick_GyroTouchRight" "Gyro: Aktiveringsknap - Berøring af højre touchpad"
	"ControllerBinding_GyroButtonMouseJoystick_GyroTouchRight_Description" "Gyroinputtet er kun aktivt, når højre touchpad berøres."
	"ControllerBinding_GyroButtonMouseJoystick_GyroTouchLeft" "Gyro: Aktiveringsknap - Berøring af venstre touchpad"
	"ControllerBinding_GyroButtonMouseJoystick_GyroTouchLeft_Description" "Gyroinputtet er kun aktivt, når venstre touchpad berøres."
	"ControllerBinding_GyroButtonMouseJoystick_GyroTouchCenter" "Gyro: Aktiveringsknap – ensartet berøring af touchpad"
	"ControllerBinding_GyroButtonMouseJoystick_GyroTouchCenter_Description" "Gyroinputtet er aktivt, når en vilkårlig del af touchpaden berøres."
	"ControllerBinding_GyroButtonMouseJoystick_GyroClickRight" "Gyro: Aktiveringsknap - Klik med højre touchpad"
	"ControllerBinding_GyroButtonMouseJoystick_GyroClickRight_Description" "Gyroinputtet er kun aktivt, når der klikkes på højre touchpad."
	"ControllerBinding_GyroButtonMouseJoystick_GyroClickLeft" "Gyro: Aktiveringsknap - Klik med venstre touchpad"
	"ControllerBinding_GyroButtonMouseJoystick_GyroClickLeft_Description" "Gyroinputtet er kun aktivt, når der klikkes på venstre touchpad."
	"ControllerBinding_GyroButtonMouseJoystick_GyroBumperRight" "Gyro: Aktiveringsknap - Højre skulderknap"
	"ControllerBinding_GyroButtonMouseJoystick_GyroBumperRight_Description" "Gyroinputtet er kun aktivt, når der trykkes på højre skulderknap."
	"ControllerBinding_GyroButtonMouseJoystick_GyroBumperLeft" "Gyro: Aktiveringsknap - Venstre skulderknap"
	"ControllerBinding_GyroButtonMouseJoystick_GyroBumperLeft_Description" "Gyroinputtet er kun aktivt, når der trykkes på venstre skulderknap."
	"ControllerBinding_GyroButtonMouseJoystick_GyroGripRight" "Gyro: Aktiveringsknap - Højre greb"
	"ControllerBinding_GyroButtonMouseJoystick_GyroGripRight_Description" "Gyroinputtet er kun aktivt, når der trykkes på højre grebknap."
	"ControllerBinding_GyroButtonMouseJoystick_GyroGripLeft" "Gyro: Aktiveringsknap - Venstre greb"
	"ControllerBinding_GyroButtonMouseJoystick_GyroGripLeft_Description" "Gyroinputtet er kun aktivt, når der trykkes på venstre grebknap."
	"ControllerBinding_GyroButtonMouseJoystick_GyroLeftTrigger" "Gyro: Aktiveringsknap - Fuldt tryk på venstre aftrækker"
	"ControllerBinding_GyroButtonMouseJoystick_GyroLeftTrigger_Description" "Gyroinputtet er kun aktivt, når venstre aftrækker trykkes i bund."
	"ControllerBinding_GyroButtonMouseJoystick_GyroRightTrigger" "Gyro: Aktiveringsknap - Fuldt tryk på højre aftrækker"
	"ControllerBinding_GyroButtonMouseJoystick_GyroRightTrigger_Description" "Gyroinputtet er kun aktivt, når højre aftrækker trykkes i bund."
	"ControllerBinding_GyroButtonMouseJoystick_GyroLeftTriggerThreshold" "Gyro: Aktiveringsknap - Blødt tryk på venstre aftrækker"
	"ControllerBinding_GyroButtonMouseJoystick_Gyro