 når der klikkes på venstre touchpad."
	"ControllerBinding_GyroButtonJoystickCamera_GyroBumperRight" "Gyro: Aktiveringsknap - Højre skulderknap"
	"ControllerBinding_GyroButtonJoystickCamera_GyroBumperRight_Description" "Gyroinputtet er kun aktivt, når der trykkes på højre skulderknap."
	"ControllerBinding_GyroButtonJoystickCamera_GyroBumperLeft" "Gyro: Aktiveringsknap - Venstre skulderknap"
	"ControllerBinding_GyroButtonJoystickCamera_GyroBumperLeft_Description" "Gyroinputtet er kun aktivt, når der trykkes på venstre skulderknap."
	"ControllerBinding_GyroButtonJoystickCamera_GyroGripRight" "Gyro: Aktiveringsknap - Højre greb"
	"ControllerBinding_GyroButtonJoystickCamera_GyroGripRight_Description" "Gyroinputtet er kun aktivt, når der trykkes på højre grebknap."
	"ControllerBinding_GyroButtonJoystickCamera_GyroGripLeft" "Gyro: Aktiveringsknap - Venstre greb"
	"ControllerBinding_GyroButtonJoystickCamera_GyroGripLeft_Description" "Gyroinputtet er kun aktivt, når der trykkes på venstre grebknap."
	"ControllerBinding_GyroButtonJoystickCamera_GyroLeftTrigger" "Gyro: Aktiveringsknap - Fuldt tryk på venstre aftrækker"
	"ControllerBinding_GyroButtonJoystickCamera_GyroLeftTrigger_Description" "Gyroinputtet er kun aktivt, når venstre aftrækker trykkes i bund."
	"ControllerBinding_GyroButtonJoystickCamera_GyroRightTrigger" "Gyro: Aktiveringsknap - Fuldt tryk på højre aftrækker"
	"ControllerBinding_GyroButtonJoystickCamera_GyroRightTrigger_Description" "Gyroinputtet er kun aktivt, når højre aftrækker trykkes i bund."
	"ControllerBinding_GyroButtonJoystickCamera_GyroLeftTriggerThreshold" "Gyro: Aktiveringsknap - Blødt tryk på venstre aftrækker"
	"ControllerBinding_GyroButtonJoystickCamera_GyroLeftTriggerThreshold_Description" "Gyroinputtet er kun aktivt, når der næsten ikke trykkes på venstre aftrækker."
	"ControllerBinding_GyroButtonJoystickCamera_GyroRightTriggerThreshold" "Gyro: Aktiveringsknap - Blødt tryk på højre aftrækker"
	"ControllerBinding_GyroButtonJoystickCamera_GyroRightTriggerThreshold_Description" "Gyroinputtet er kun aktivt, når der næsten ikke trykkes på højre aftrækker."
	"ControllerBinding_GyroButtonJoystickCamera_GyroA" "Gyro: Aktiveringsknap - A"
	"ControllerBinding_GyroButtonJoystickCamera_GyroA_Description" "Gyroinputtet er kun aktivt, når der trykkes på A-knappen."
	"ControllerBinding_GyroButtonJoystickCamera_GyroB" "Gyro: Aktiveringsknap - B"
	"ControllerBinding_GyroButtonJoystickCamera_GyroB_Description" "Gyroinputtet er kun aktivt, når der trykkes på B-knappen."
	"ControllerBinding_GyroButtonJoystickCamera_GyroX" "Gyro: Aktiveringsknap - X"
	"ControllerBinding_GyroButtonJoystickCamera_GyroX_Description" "Gyroinputtet er kun aktivt, når der trykkes på X-knappen."
	"ControllerBinding_GyroButtonJoystickCamera_GyroY" "Gyro: Aktiveringsknap - Y"
	"ControllerBinding_GyroButtonJoystickCamera_GyroY_Description" "Gyroinputtet er kun aktivt, når der trykkes på Y-knappen."
	"ControllerBinding_GyroButtonJoystickCamera_GyroCross" "Gyro: Aktiveringsknap - Kryds"
	"ControllerBinding_GyroButtonJoystickCamera_GyroCross_Description" "Gyroinputtet er kun aktivt, når der trykkes på krydsknappen."
	"ControllerBinding_GyroButtonJoystickCamera_GyroCircle" "Gyro: Aktiveringsknap - Cirkel"
	"ControllerBinding_GyroButtonJoystickCamera_GyroCircle_Description" "Gyroinputtet er kun aktivt, når der trykkes på cirkelknappen."
	"ControllerBinding_GyroButtonJoystickCamera_GyroSquare" "Gyro: Aktiveringsknap - Kvadrat"
	"ControllerBinding_GyroButtonJoystickCamera_GyroSquare_Description" "Gyroinputtet er kun aktivt, når der trykkes på kvadratknappen."
	"ControllerBinding_GyroButtonJoystickCamera_GyroTriangle" "Gyro: Aktiveringsknap -  Trekant"
	"ControllerBinding_GyroButtonJoystickCamera_GyroTriangle_Description" "Gyroinputtet er kun aktivt, når der trykkes på trekantknappen."
	"ControllerBinding_GyroButtonJoystickCamera_GyroLStick" "Gyro: Aktiveringsknap - Klik med venstre styrepind"
	"ControllerBinding_GyroButtonJoystickCamera_GyroLStick_Description" "Gyroinputtet er kun aktivt, når der klikkes med venstre styrepind."
	"ControllerBinding_GyroButtonJoystickCamera_GyroRStick" "Gyro: Aktiveringsknap - Klik med højre styrepind"
	"ControllerBinding_GyroButtonJoystickCamera_GyroRStick_Description" "Gyroinputtet er kun aktivt, når der klikkes med højre styrepind."	
	"ControllerBinding_GyroButtonJoystickCamera_GyroCapture" "Gyro: Aktiveringsknap - Klik med capture-knap"
	"ControllerBinding_GyroButtonJoystickCamera_GyroCapture_Description" "Gyroinputtet er kun aktivt, når der trykkes på capture-knappen."	
	"ControllerBinding_GyroButtonJoystickCamera_GyroRightTriggerNoQualifier" "Gyro: Aktiveringsknap - Højre aftrækker"
	"ControllerBinding_GyroButtonJoystickCamera_GyroRightTriggerNoQualifier_Description" "Gyroinputtet er kun aktivt, når der klikkes med højre aftrækker."	
	"ControllerBinding_GyroButtonJoystickCamera_GyroLeftTriggerNoQualifier" "Gyro: Aktiveringsknap - Venstre aftrækker"
	"ControllerBinding_GyroButtonJoystickCamera_GyroLeftTriggerNoQualifier_Description" "Gyroinputtet er kun aktivt, når der klikkes med venstre aftrækker."	
	"ControllerBinding_InvertXJoystickCamera" "Inverter vandret akse"
	"ControllerBinding_InvertXJoystickCamera_Description" "Hvis slået til vil joysticket bevæge sig til højre, når du bevæger til venstre. Omvendt vil joysticket bevæge sig til venstre, når du bevæger til højre. Bemærk at spilindstillinger ofte også har denne indstilling, så du skal sikre dig, at de ikke ophæver hinanden."
	"ControllerBinding_InvertXJoystickCamera_On" "Inverter vandret akse - Til"
	"ControllerBinding_InvertXJoystickCamera_On_Description" "Hvis slået til vil joysticket bevæge sig til højre, når du bevæger til venstre. Omvendt vil joysticket bevæge sig til venstre, når du bevæger til højre. Bemærk at spilindstillinger ofte også har denne indstilling, så du skal sikre dig, at de ikke ophæver hinanden."
	"ControllerBinding_InvertXJoystickCamera_Off" "Inverter vandret akse - Fra"
	"ControllerBinding_InvertXJoystickCamera_Off_Description" "Joystickets vandrette akse vil fungere normalt med bevægelse venstre på fladen svarende til bevægelse venstre på joysticket."
	"ControllerBinding_InvertYJoystickCamera" "Inverter lodret akse"
	"ControllerBinding_InvertYJoystickCamera_Description" "Hvis slået til vil joysticket bevæge sig nedad, når du bevæger opad på fladen. Omvendt vil joysticket bevæge sig opad, når du bevæger nedad på fladen. Bemærk at spilindstillinger ofte også har denne indstilling, så du skal sikre dig, at de ikke ophæver hinanden."
	"ControllerBinding_InvertYJoystickCamera_On" "Inverter lodret akse - Til"
	"ControllerBinding_InvertYJoystickCamera_On_Description" "Hvis slået til vil joysticket bevæge sig nedad, når du bevæger opad på fladen. Omvendt vil joysticket bevæge sig opad, når du bevæger nedad på fladen. Bemærk at spilindstillinger ofte også har denne indstilling, så du skal sikre dig, at de ikke ophæver hinanden."
	"ControllerBinding_InvertYJoystickCamera_Off" "Inverter lodret akse - Fra"
	"ControllerBinding_InvertYJoystickCamera_Off_Description" "Joystickets lodrette akse vil fungere normalt med bevægelse opad på fladen svarende til bevægelse opad på joysticket."
	"ControllerBinding_VerticalSensitivityJoystickCamera" "Skala for lodret følsomhed"
	"ControllerBinding_VerticalSensitivityJoystickCamera_Description" "Skala for lodret følsomhed bestemmer, hvor meget lodret bevægelse der forekommer i forhold til vandret bevægelse. Ved 50% på slideren er der lige meget bevægelse. Hvis den er mindre end halvvejs, er lodret bevægelse langsommere end vandret bevægelse. Hvis den er mere end halvvejs, er lodret bevægelse hurtigere end vandret bevægelse."
	"ControllerBinding_JoystickSmoothingCameraMode" "Udjævn joystick"
	"ControllerBinding_JoystickSmoothingCameraMode_Description" "Udjævning returnerer styrepinden til sin neutrale position, som var den styret af en fysisk fjeder, i stedet for at returnere den i samme øjeblik, du holder op med at røre fladen."
	"ControllerBinding_JoystickSmoothingCameraMode_On" "Udjævn joystick - Til"
	"ControllerBinding_JoystickSmoothingCameraMode_On_Description" "Udjævning returnerer styrepinden til sin neutrale position, som var den styret af en fysisk fjeder, i stedet for at returnere den i samme øjeblik, du holder op med at røre fladen."
	"ControllerBinding_JoystickSmoothingCameraMode_Off" "Udjævn joystick - Fra"
	"ControllerBinding_JoystickSmoothingCameraMode_Off_Description" "Returner øjeblikkeligt til nul ved stop."
	"ControllerBinding_JoystickCameraMouseSensitivity" "Musefølsomhed"
	"ControllerBinding_JoystickCameraMouseSensitivity_Description" "Musemarkørens følsomhed når det virtuelle joysticks output er sat til mus."
	"ControllerBinding_AntiDeadZoneJoystickCamera" "Anti-dødszone"
	"ControllerBinding_AntiDeadZoneJoystickCamera_Description" "De fleste spil påfører deres egne dødszoner til controller-outputtet. Hvis styringen føles \"klunset\" med et fysisk bevægelsesområde, hvor der ikke sendes noget input til spillet, så er det højst sandsynligt forårsaget af spillets dødszone. Du kan fjerne den ved at bruge indstillingen for anti-dødszone. Dette ophæver dødszonen og giver mere præcis styring i den tilbageværende sektion. Jo højere slideren sættes, jo mere tilføjes der til den mindste outputværdi. Bemærk at hvis al dødszone fjernes fuldstændigt, så vil alle positioner resultere i input. Du kan bruge buffer for anti-dødszone til at anbringe et mindre område, hvor der ikke sendes input, selv hvis anti-dødszonen er større end spillets dødszone."
	"ControllerBinding_AntiDeadZoneBufferJoystickCamera" "Buffer for anti-dødszone"
	"ControllerBinding_AntiDeadZoneBufferJoystickCamera_Description" "Hvis der er påført anti-dødszone, så er der muligvis ingen egentlig dødszone, som påføres af spillet, hvilket betyder, at berøring hvor som helst vil resultere i bevægelse. For at tillade et mere sikkert bufferområde, hvor der ikke sendes noget input, så fungerer buffer for anti-dødszone som styringens nye dødszone. Den kan visualiseres som en radius fra centrum af fladen, hvori der ikke sendes noget input."
	"ControllerBinding_AbsMouseMouseSensitivity" "Musefølsomhed"
	"ControllerBinding_AntiDeadZoneAbsMouse" "Anti-Dødszone"
	"ControllerBinding_AntiDeadZoneAbsMouse_Description" "De fleste spil påfører deres egne dødszoner til controller-outputtet. Hvis styringen føles \"kluntet\" med et fysisk bevægelsesområde, hvor der ikke sendes noget input til spillet, så er det højst sandsynligt forårsaget af spillets dødszone. Du kan fjerne den ved at bruge indstillingen for anti-dødszone. Dette ophæver dødszonen og giver mere præcis styring i den tilbageværende sektion. Jo højere slideren sættes, des mere tilføjes der til den mindste outputværdi. Bemærk at hvis al dødszone fjernes fuldstændigt, vil alle positioner resultere i input. Du kan bruge anti-dødszone buffer til at tillade et mindre område, hvor der ikke sendes input, selv hvis anti-dødszonen er større end spillets dødszone."
	"ControllerBinding_AntiDeadZoneBufferAbsMouse" "Anti-Dødszone Buffer"
	"ControllerBinding_AntiDeadZoneBufferAbsMouse_Description" "Hvis der er påført anti-dødszone, så er der muligvis ingen egentlig dødszone, som påføres af spillet, hvilket betyder, at berøring hvor som helst vil resultere i bevægelse. For at tillade et mere sikkert bufferområde, hvor der ikke sendes noget input, så fungerer buffer for anti-dødszone som styringens nye dødszone. Den kan visualiseres som en radius fra centrum af fladen, hvori der ikke sendes noget input."
	"ControllerBinding_GyroButtonAbsMouse" "Gyro: Aktiveringsknap"
	"ControllerBinding_GyroButtonAbsMouse_Description" "Gyroinputtet kan kun aktiveres, når der trykkes på en knap."
	"ControllerBinding_GyroButtonAbsMouse_GyroNone" "Gyro: Aktiveringsknap - Altid til"
	"ControllerBinding_GyroButtonAbsMouse_GyroNone_Description" "Gyroinputtet er altid aktivt."
	"ControllerBinding_GyroButtonAbsMouse_GyroTouchRight" "Gyro: Aktiveringsknap - Berøring af højre touchpad"
	"ControllerBinding_GyroButtonAbsMouse_GyroTouchRight_Description" "Gyroinputtet er kun aktivt, når højre touchpad berøres."
	"ControllerBinding_GyroButtonAbsMouse_GyroTouchLeft" "Gyro: Aktiveringsknap - Berøring af venstre touchpad"
	"ControllerBinding_GyroButtonAbsMouse_GyroTouchLeft_Description" "Gyroinputtet er kun aktivt, når venstre touchpad berøres."
	"ControllerBinding_GyroButtonAbsMouse_GyroTouchCenter" "Gyro: Aktiveringsknap – ensartet berøring af touchpad"
	"ControllerBinding_GyroButtonAbsMouse_GyroTouchCenter_Description" "Gyroinputtet er aktivt, når en vilkårlig del af touchpaden berøres."
	"ControllerBinding_GyroButtonAbsMouse_GyroClickRight" "Gyro: Aktiveringsknap - Klik med højre touchpad"
	"ControllerBinding_GyroButtonAbsMouse_GyroClickRight_Description" "Gyroinputtet er kun aktivt, når der klikkes på højre touchpad."
	"ControllerBinding_GyroButtonAbsMouse_GyroClickLeft" "Gyro: Aktiveringsknap - Klik med venstre touchpad"
	"ControllerBinding_GyroButtonAbsMouse_GyroClickLeft_Description" "Gyroinputtet er kun aktivt, når der klikkes på venstre touchpad."
	"ControllerBinding_GyroButtonAbsMouse_GyroBumperRight" "Gyro: Aktiveringsknap - Højre skulderknap"
	"ControllerBinding_GyroButtonAbsMouse_GyroBumperRight_Description" "Gyroinputtet er kun aktivt, når der trykkes på højre skulderknap."
	"ControllerBinding_GyroButtonAbsMouse_GyroBumperLeft" "Gyro: Aktiveringsknap - Venstre skulderknap"
	"ControllerBinding_GyroButtonAbsMouse_GyroBumperLeft_Description" "Gyroinputtet er kun aktivt, når der trykkes på venstre skulderknap."
	"ControllerBinding_GyroButtonAbsMouse_GyroGripRight" "Gyro: Aktiveringsknap - Højre greb"
	"ControllerBinding_GyroButtonAbsMouse_GyroGripRight_Description" "Gyroinputtet er kun aktivt, når der trykkes på højre grebknap."
	"ControllerBinding_GyroButtonAbsMouse_GyroGripLeft" "Gyro: Aktiveringsknap - Venstre greb"
	"ControllerBinding_GyroButtonAbsMouse_GyroGripLeft_Description" "Gyroinputtet er kun aktivt, når der trykkes på venstre grebknap."
	"ControllerBinding_GyroButtonAbsMouse_GyroLeftTrigger" "Gyro: Aktiveringsknap - Fuldt tryk på venstre aftrækker"
	"ControllerBinding_GyroButtonAbsMouse_GyroLeftTrigger_Description" "Gyroinputtet er kun aktivt, når venstre aftrækker trykkes i bund."
	"ControllerBinding_GyroButtonAbsMouse_GyroRightTrigger" "Gyro: Aktiveringsknap - Fuldt tryk på højre aftrækker"
	"ControllerBinding_GyroButtonAbsMouse_GyroRightTrigger_Description" "Gyroinputtet er kun aktivt, når højre aftrækker trykkes i bund."
	"ControllerBinding_GyroButtonAbsMouse_GyroLeftTriggerThreshold" "Gyro: Aktiveringsknap - Blødt tryk på venstre aftrækker"
	"ControllerBinding_GyroButtonAbsMouse_GyroLeftTriggerThreshold_Description" "Gyroinputtet er kun aktivt, når der næsten ikke trykkes på venstre aftrækker."
	"ControllerBinding_GyroButtonAbsMouse_GyroRightTriggerThreshold" "Gyro: Aktiveringsknap - Blødt tryk på højre aftrækker"
	"ControllerBinding_GyroButtonAbsMouse_GyroRightTriggerThreshold_Description" "Gyroinputtet er kun aktivt, når der næsten ikke trykkes på højre aftrækker."
	"ControllerBinding_GyroButtonAbsMouse_GyroA" "Gyro: Aktiveringsknap - A"
	"ControllerBinding_GyroButtonAbsMouse_GyroA_Description" "Gyroinputtet er kun aktivt, når der trykkes på A-knappen."
	"ControllerBinding_GyroButtonAbsMouse_GyroB" "Gyro: Aktiveringsknap - B"
	"ControllerBinding_GyroButtonAbsMouse_GyroB_Description" "Gyroinputtet er kun aktivt, når der trykkes på B-knappen."
	"ControllerBinding_GyroButtonAbsMouse_GyroX" "Gyro: Aktiveringsknap - X"
	"ControllerBinding_GyroButtonAbsMouse_GyroX_Description" "Gyroinputtet er kun aktivt, når der trykkes på X-knappen."
	"ControllerBinding_GyroButtonAbsMouse_GyroY" "Gyro: Aktiveringsknap - Y"
	"ControllerBinding_GyroButtonAbsMouse_GyroY_Description" "Gyroinputtet er kun aktivt, når der trykkes på Y-knappen."
	"ControllerBinding_GyroButtonAbsMouse_GyroCross" "Gyro: Aktiveringsknap - Kryds"
	"ControllerBinding_GyroButtonAbsMouse_GyroCross_Description" "Gyroinputtet er kun aktivt, når der trykkes på krydsknappen."
	"ControllerBinding_GyroButtonAbsMouse_GyroCircle" "Gyro: Aktiveringsknap - Cirkel"
	"ControllerBinding_GyroButtonAbsMouse_GyroCircle_Description" "Gyroinputtet er kun aktivt, når der trykkes på cirkelknappen."
	"ControllerBinding_GyroButtonAbsMouse_GyroSquare" "Gyro: Aktiveringsknap - Kvadrat"
	"ControllerBinding_GyroButtonAbsMouse_GyroSquare_Description" "Gyroinputtet er kun aktivt, når der trykkes på kvadratknappen."
	"ControllerBinding_GyroButtonAbsMouse_GyroTriangle" "Gyro: Aktiveringsknap - Trekant"
	"ControllerBinding_GyroButtonAbsMouse_GyroTriangle_Description" "Gyroinputtet er kun aktivt, når der trykkes på trekantknappen."
	"ControllerBinding_GyroButtonAbsMouse_GyroLStick" "Gyro: Aktiveringsknap - Klik med venstre styrepind"
	"ControllerBinding_GyroButtonAbsMouse_GyroLStick_Description" "Gyroinputtet er kun aktivt, når der klikkes med venstre styrepind."
	"ControllerBinding_GyroButtonAbsMouse_GyroRStick" "Gyro: Aktiveringsknap - Klik med højre styrepind"
	"ControllerBinding_GyroButtonAbsMouse_GyroRStick_Description" "Gyroinputtet er kun aktivt, når der klikkes med højre styrepind."	
	"ControllerBinding_GyroButtonAbsMouse_GyroCapture" "Gyro: Aktiveringsknap - Klik med capture-knap"
	"ControllerBinding_GyroButtonAbsMouse_GyroCapture_Description" "Gyroinputtet er kun aktivt, når der trykkes på capture-knappen."	
	"ControllerBinding_GyroButtonAbsMouse_GyroRightTriggerNoQualifier" "Gyro: Aktiveringsknap - Højre aftrækker"
	"ControllerBinding_GyroButtonAbsMouse_GyroRightTriggerNoQualifier_Description" "Gyroinputtet er kun aktivt, når der klikkes med højre aftrækker."	
	"ControllerBinding_GyroButtonAbsMouse_GyroLeftTriggerNoQualifier" "Gyro: Aktiveringsknap - Venstre aftrækker"
	"ControllerBinding_GyroButtonAbsMouse_GyroLeftTriggerNoQualifier_Description" "Gyroinputtet er kun aktivt, når der klikkes med venstre aftrækker."	
	"ControllerBinding_AbsMouseMouseSensitivity_Description" "Musemarkørens følsomhed når det virtuelle joysticks output er sat til mus."
	// Absolute Mouse
	"ControllerBinding_ModeDropDown_AbsoluteMouse" "Inputtype - Mus"
	"ControllerBinding_ModeDropDown_AbsoluteMouse_Description" "Dette input vil fungere som en mus. Den styrer enhver musebaseret grænseflade såsom en markør eller et kamera i et spil."
	"ControllerBinding_AbsMouseClick" "Klikhandling"
	"ControllerBinding_AbsMouseClick_Description" "Denne handling udføres, når du klikker på fladen."
	"ControllerBinding_AbsMouseGyroLeft" "Handling ved hældning til venstre"
	"ControllerBinding_AbsMouseGyroLeft_Description" "Denne handling udføres, når du hælder controlleren mod venstre."
	"ControllerBinding_AbsMouseGyroRight" "Handling ved hældning til højre"
	"ControllerBinding_AbsMouseGyroRight_Description" "Denne handling udføres, når du hælder controlleren mod højre."
	"ControllerBinding_Trackball" "Trackball-tilstand"
	"ControllerBinding_Trackball_Description" "Trackball-tilstand får fladen til at fungere som en trackball i stedet for en mus. Den har momentum og friktion, hvilket lader dig svirpe den som en trackball."
	"ControllerBinding_Trackball_On" "Trackball-tilstand - Til"
	"ControllerBinding_Trackball_On_Description" "Musen vil bevæge sig som en trackball. Den har momentum og friktion og kan svirpes som en trackball."
	"ControllerBinding_Trackball_Off" "Trackball-tilstand - Fra"
	"ControllerBinding_Trackball_Off_Description" "Musen vil bevæge sig som en normal mus. Den har hverken momentum eller friktion."
	"ControllerBinding_Sensitivity" "Følsomhed"
	"ControllerBinding_Sensitivity_Description" "Angiver denne styrings følsomhed. At sænke følsomheden i spillet, og i stedet øge denne hardware-følsomhed, vil give spillet mere nøjagtighed at arbejde med for det mest udjævnede resultat."
	"ControllerBinding_Sensitivity2DScroll" "Følsomhed"
	"ControllerBinding_Sensitivity2DScroll_Description" "Angiver følsomheden for denne styr