n er låst på fjerncomputeren."
	"SteamUI_StreamLaunch_Broadcasting"	"Fjerncomputeren bruger i øjeblikket Steam-broadcasting, så den kan ikke starte en session med Remote Play."
	"SteamUI_StreamLaunch_OtherGameRunning"	"Der kører allerede et andet spil på den fjerne computer."
	"SteamUI_StreamLaunch_Timeout"		"Timede ud under venten på Stream-opstart."
	"SteamUI_StreamLaunch_InstallRequiresUI" "Installation af dette spil kræver brugerindgreb.\n\nInstaller manuelt på den fjerne computer."
	"SteamUI_StreamLaunch_Failed"		"Kunne ikke starte stream."
	"SteamUI_StreamLaunch_InstallDrivers"	"Streaming kræver installation af en ekstra driver.\n\nFølg venligst klarmeldingen på fjerncomputeren."
	"SteamUI_StreamLaunch_TransportUnavailable"	"Streaming uden for hjemmet er ikke muligt i øjeblikket. Prøv igen senere."

	"Steam_InstallAudioCaptureDriver_Title"	"Lyddriveropdatering"
	"Steam_InstallAudioCaptureDriver_Text"	"Steam skal opdatere sin lyddriver, hvilket kan kræve en genstart af systemet."
	"Steam_InstallGamepadInputDriver_Title"	"Gamepad-driveropdatering"
	"Steam_InstallGamepadInputDriver_Text"	"Steam skal opdatere sin gamepad-driver, hvilket kan kræve en genstart af systemet."
	"Steam_InstallGamepadInputDriver_RestartText"	"Du skal genstarte Steam efter at have installeret gamepad-driveren."

	"SteamUI_RemoteDeviceAuthorization_Title"		"Godkend enhed"
	"SteamUI_RemoteDeviceAuthorization_Text"		"Indtast venligst godkendelseskoden for at tillade {s:devicename} at tilslutte og spille spil."

	"Steam_OtherSessionPlaying_Title" "Fejl - Steam"
	"Steam_OtherSessionPlaying_Text" "Du er logget ind på en anden computer, der allerede spiller \"{s:existing_app}\"\nHvis du starter \"{s:launching_app}\" her, vil du afbryde den anden session fra Steam."
	
	"SteamUI_JoinDialog_KickSessions_Error" "Kunne ikke afbryde den anden session, der spiller  \"{s:existing_app}\"."

	"Steam_VideoPlayer_Title"	"Fejl - Videoafspiller"
	"Steam_VideoPlayer_LaunchError"	"Der opstod en fejl ved start af Steam-videoafspilleren"

	"Steam_Video360Player_Title"	"Fejl - Steam 360-videoafspiller"
	"Steam_Video360Player_LaunchError"	"Afspilning af en 360-video kræver installering af Steam 360-videoafspilleren.\n\nDu skal afslutte Big Picture-tilstand, og derefter fra værktøjsmenuen i dit Steam-bibliotek, dobbeltklikke på Steam 360-videoafspilleren for at begynde installationen."

	"Steam_Video360PlayerInstall_Title"	"Steam 360-videoafspiller"
	"Steam_Video360PlayerInstall_Message"	"Afspilning af en 360-video kræver en engangsinstallation af Steam 360-videoafspilleren.\n\nFuldfør installationen og klik derefter på \"Se\"-knappen på en 360-video for at begynde afspilningen."

	"Settings_SteamController"		"Steam Controller"
	"SettingsSteamController_ResetSettings"		"Nulstil til standarder"
	"SettingsSteamController_ResetSettingsTitle" "Nulstil Steam Controller-indstillinger"
	"SettingsSteamController_ResetSettingsConfirm" "Dette vil nulstille indstillingerne på denne side til deres standardværdier.\nDine gemte bindinger bliver ikke påvirket."
	"SettingsSteamController_DoubleTapBeepEnabled" "Aktiver bip ved dobbelttap"
	"SettingsSteamController_TrackballRotationAngle" "Angiv vinkel på trackpads"
	"SettingsSteamController_MouseSensitivity" "Musefølsomhed"
	"SettingsSteamController_MouseAcceleration" "Muse-acceleration"

	"Settings_RemoteControl"				"Fjernkontrol"
	"SettingsRemoteControl_Title"			"Fjernkontrol-adgang"
	"SettingsRemoteControl_Text"			"For at fjernstyre Steam skal den tilknyttes med en enhed. Forneden ses en liste over tilknyttede eller blokerede enheder. Du kan også fjerne tilknytningen eller blokeringen af enhederne på denne liste."
	"SettingsRemoteControl_DevicesHeader"	"ENHEDER"
	"SettingsRemoteControl_Enable"			"Slå fjernkontrol til"
	"SettingsRemoteControl_Name"			"ENHEDSNAVN"
	"SettingsRemoteControl_NameUnknown"		"Unavngivet enhed"
	"SettingsRemoteControl_Access"			"ADGANG"
	"SettingsRemoteControl_Time"			"SIDST TILGÅET"
	"SettingsRemoteControl_Time_Entry"		"{t:l:access_date}"
	"SettingsRemoteControl_TimeUnknown"		"Ukendt"
	"SettingsRemoteControl_Paired"			"TILKNYTTET"
	"SettingsRemoteControl_Blocked"			"BLOKERET"
	"SettingsRemoteControl_Unpair"			"FJERN TILKNYTNING TIL DENNE ENHED"
	"SettingsRemoteControl_Unblock"			"FJERN BLOKERING FRA DENNE ENHED"
	"SettingsAudio_Steam"	"Steam-lydindstillinger"
	"SettingsAudio_Hardware"	"System-lydindstillinger"

	"Settings_Broadcast" "Broadcasting"
	"Settings_Broadcast_Disabled" "Broadcasting slået fra"
	"Settings_Broadcast_InviteOnly" "Kun venner, jeg inviterer, kan se på"
	"Settings_Broadcast_FriendsApprove" "Venner kan anmode om at se på"
	"Settings_Broadcast_FriendsAllowed" "Venner kan se på"
	"Settings_Broadcast_FriendsPublic" "Enhver kan se på"
	"Settings_Broadcast_Bitrate3500" "3500 kbit/s"
	"Settings_Broadcast_Bitrate3000" "3000 kbit/s"
	"Settings_Broadcast_Bitrate2500" "2500 kbit/s"
	"Settings_Broadcast_Bitrate2000" "2000 kbit/s"
	"Settings_Broadcast_Bitrate1500" "1500 kbit/s"
	"Settings_Broadcast_Bitrate1000" "1000 kbit/s"
	"Settings_Broadcast_Bitrate750" "750 kbit/s"
	"Settings_Broadcast_1080p" "1920x1080 (1080p)"
	"Settings_Broadcast_720p" "1280x720 (720p)"
	"Settings_Broadcast_480p" "854x480 (480p)"
	"Settings_Broadcast_360p" "640x360 (360p)"
	"Settings_Broadcast_IncludeDesktop" "Optag mit skrivebord når jeg ikke er i spil"
	"Settings_Broadcast_RecordMic" "Optag og broadcast min mikrofon"
	"Settings_Broadcast_ShowDebugInfo" "Vis upload-statistikker"
	"Settings_Broadcast_ShowChat" "Vis seers chat i spil"
	"Settings_Broadcast_PermissionsHeader" "Indstilling for synlighed"
	"Settings_Broadcast_BitrateHeader" "Maksimal bitrate"
	"Settings_Broadcast_DimensionsHeader" "Videodimensioner"
	"Settings_Broadcast_ShowChat_Off" "Fra"
	"Settings_Broadcast_ShowChat_LeftTop" "Øverst til venstre"
	"Settings_Broadcast_ShowChat_RightTop" "Øverst til højre"
	"Settings_Broadcast_ShowChat_RightBottom" "Nederst til højre"
	"Settings_Broadcast_ShowChat_LeftBottom" "Nederst til venstre"
	"Settings_Broadcast_Disabled_System" "Steam-broadcasting er ikke understøtte på dette operativsystem på nuværende tidspunkt."
	"Settings_Broadcast_Disabled_System_Windows_Compat_Enabled" "Steam-broadcasting kræver Windows 7 eller højere.\n\n Fjern venligst alle Windows-kompatibilitetsindstillinger for alle brugere\n under filegenskaber for Steam.exe og genstart Steam."
	"Settings_Broadcast_Disabled_User" "Din konto har ikke de nødvendige rettigheder til at broadcaste livestreaminger."

	"Broadcast_Playback"		"DIREKTE"
	"Broadcast_SpectatorCount"	"{d:NumViewers}"
	"Broadcast_RequestCount"	"{d:NumRequests}"

	"Broadcast_Notification_Header"	  "SEERANMODNINGER"
	"Broadcast_Notification_Joined_Public"	"En bruger har sluttet sig til din offentlige broadcast"
	"Broadcast_Notification_Stopped_Public"	"Alle brugere er stoppet med at se din offentlige broadcast"
	"Broadcast_Notification_Is_Watching"	"ser din broadcast"
	"Broadcast_Notification_Viewer_Request"	"vil gerne se dig spille"
	"Broadcast_Notification_Viewer_Request_Overlay" "{s:friend}"
	"Broadcast_Notification_Accept_Request" "Accepter"
	"Broadcast_Notification_Ignore_Request" "Ignorer" 
	"Broadcast_Notification_AvailableToWatch_Title" "Broadcasting er slået til!"
	"Broadcast_Notification_AvailableToWatch_Friends" "Dine venner kan slutte sig til din broadcast på ethvert tidspunkt."
	"Broadcast_Notification_AvailableToWatch_Public" "Enhver Steam-bruger kan slutte sig til din broadcast på ethvert tidspunkt."

	"Broadcast_FirstTime_Title" "Steam-broadcasting"
	"Broadcast_FirstTime_Header" "Med Steam-broadcasting kan du broadcaste dine spil og se andre spille spil."
	"Broadcast_FirstTime_PermissionHeader" "Din ven, {s:persona}, vil gerne se dig spille. Hvad er dine broadcast-præferencer?"
	"Broadcast_FirstTime_DesktopOnly" "Som standard vil kun dit spil kunne ses. Dit skrivebord bliver ikke broadcastet."
	"Broadcast_FirstTime_FAQ" "Læs de ofte stillede spørgsmål om Steam-broadcasting"
	"Broadcast_FirstTime_OK" "OK"
	"Broadcast_FirstTime_Cancel" "Annuller"
	"Broadcast_FirstTime_ViewerRequest" "{s:friend} vil gerne se dig spille {s:gamename}"

	"StreamingOverlay_Title"		"REMOTE PLAY"
	"StreamingOverlay_Status"		"Streamer i øjeblikket fra: \n{s:hostname}"
	"StreamingOverlay_FooterButton" "VIS STATUS FOR REMOTE PLAY"

	"StreamingDetails_Title"		"Status for Remote Play"
	"StreamingDetails_Status"		"Vært: {s:hostname}\nKlient: {s:clientname}\n{s:streamres} med {s:streamfps} FPS\n{s:streamrate} kilobit/sek\n\nIndkodningsforsinkelse: {s:latencyencode}\nNetværksforsinkelse: {s:latencynetwork} +/- {s:latencynetworkstddev}\nAfkodningsforsinkelse: {s:latencydecode}\n\nNetværkskvalitet: {s:networkquality}"
	"StreamingDetails_ButtonModifySettings"	"REDIGER INDSTILLINGER"

	"SettingsVoice_VoiceOutputtoInput"	"Brug også som stemme-output"

	"SettingsAudioConfig_BeginWizard"	"Genkonfigurer lyd"

	"SettingsAudio_Port"				"Lydoutput-port"

	"SettingsAudio_Card"				"Internt lydkort og -port"
	"SettingsAudio_Card_Information"	"Denne indstilling bestemmer hvilket lydkort og fysiske port i din PC eller konsol, som skal bruges til lydbehandling. Der er som regel et indbygget lydkort i bundkortet, men nogle systemer har et ekstra separat lydkort som kan foretage denne funktion."
	"SettingsAudio_Card_ToDo"			"Vælg venligst hvilken enhed du vil bruge:"

	"SettingsAudio_Profile"				"Lydpræsentation"
	"SettingsAudio_Profile_Information"	"Denne indstilling lader dig vælge, hvordan du vil have lyden præsenteret. Som regel har man lyden afspillet i mono, stereo eller forskellige slags surround sound."
	"SettingsAudio_Profile_ToDo"		"Vælg venligst en lydpræstation fra listen nedenfor:"

	"SettingsAudio_Codec"	"Digitale Passthrough Codecs "
	"SettingsAudio_Codec_Information"	"Hvis dit lydsystem kan håndtere ukomprimerede digitale codecs, så kan du vælge, at de ukomprimerede codecs ikke skal konverteres. De digitale streaminger, indkodet i formaterne, du valgte nedenfor, konverteres ikke af systemet. Dette bruges i medieapplikationer. For at bestemme disse indstillinger bør du læse manualerne for dine medieapplikationer."
	"SettingsAudio_Codec_NoDigital"		"Der er ikke valgt et digitalt output. Gå venligst tilbage og vælg et digitalt output for at slå disse codecs til."
	"SettingsAudio_Codec_ToDo"			"Angiv venligst hvilke codecs, som skal passere uden konvertering:"


	"SettingsVoice_InputPort" "Stemmeoptagelsesport"

	"SettingsAudio_AC3"		"AC3 Pass-through"
	"SettingsAudio_EAC3"	"EAC3 Pass-through "
	"SettingsAudio_DTS"		"DTS Pass-through"
	"SettingsAudio_Failed"	"Lydindstillinger utilgængelige. Kunne ikke forbinde til lydtjeneste."

	"Settings_AlienFX"	"Alien FX"
	"Settings_AlienFXDescription" "Vælg effekterne som skal anvendes i lys-zonerne på dit Alienware-kabinet."
	"Settings_AlienFXHeader"	"Alien FX"
	"Settings_AlienFXBrightness"	"Lysstyrke"

	"Community_PostStatusFailure"	"Beklager, der opstod en fejl i forsøget på at slå din status op."
	"Community_Notifications"		"Kommentarnotifikationer"
	"Community_Achievements"		"Præstationer"
	"Community_FriendsWhoPlay"	"Venner, der spiller"

	"SteamUI_AddController_Title"					"Søger efter Steam Controllere..."
	"SteamUI_AddController_HowToPair"	"Tilknyt en ny Steam Controller ved at holde X nede mens du tænder for din Steam Controller."

	"BigPicture_YouHaveNPendingInvites"	"Vis {d:InviteCount} afventende venneinvitationer"

	"Screenshots_Screenshots" 	"SKÆRMBILLEDER"
	"Screenshots_Screenshots_lwr" 	"Skærmbilleder"
	"Screenshots_TimeTaken"		"{t:l:timetaken}"
	"Screenshots_AllGames"		"Alle spil"
	"Screenshots_SizeOnDisk"	"{s:sizeondisk}"
	"Screenshots_NoScreenshots" "Du har ingen gemte skærmbilleder. Når du er i et spil kan du trykke på genvejstasten nedenfor for at tage et skærmbillede. Derefter kan du udgive det til Steam-fællesskabet såvel som Facebook, Twitter og andre netværk."
	"Screenshots_KeyboardHeader" "Tastaturgenvej"
	"Screenshots_ControllerHeader" "Controllergenvej"
	"Screenshots_ViewFullscreen" "VIS I FULDSKÆRM"

	"Store_LoadingError"		"Steam kunne ikke indlæse den anmodede butikssektion. Prøv venligst igen."

	"SteamUI_UpdateControllerFirmware_Cancel"	"IKKE NU"
	"SteamUI_UpdateControllerFirmware_Continue"	"OPDATÉR"
	"SteamUI_UpdateControllerFirmware_Done"		"OK"
	"SteamUI_UpdateControllerFirmware_Title"	"Firmware-opdatering"
	"SteamUI_UpdateControllerFirmwareComplete_Title"	"Firmware-opdatering gennemført"
	"SteamUI_UpdateControllerFirmware_Intro"	"Der er ny firmware tilgængelig til din Steam Controller. Opdateringen vil tage op til et par minutter."
	"SteamUI_UpdateControllerFirmware_Install"	"Ny firmware bliver installeret på controlleren.\nAfbryd venligst ikke controlleren.\nOpdateringen kan tage op til et par minutter."
	"SteamUI_UpdateControllerFirmware_InstallW"	"Ny firmware bliver installeret på controlleren.\nSluk ikke for controlleren.\nOpdateringen kan tage op til ét minut."
	"SteamUI_UpdateControllerFirmware_InstallAuto"	"Forsøger firmware-opdatering igen...\nHvis problemet fortsætter så prøv at flytte controlleren tættere på modtageren eller forbind den med et USB-kabel."
	"SteamUI_UpdateControllerFirmware_Finished"	"Din Steam Controller-firmware er blevet opdateret."
	"SteamUI_UpdateControllerFirmware_Fallback"	"Initierer firmware-opdatering."
	"SteamUI_UpdateControllerFirmware_SearchForVolume"	"Søger efter lager-bootloader. Dette kan tage op til et minut i nogle systemer."
	"SteamUI_UpdateControllerFirmware_Fallback_Finished" "Din firmware er nu blevet opdateret. Træk USB-kablet ud for at fortsætte."
	"SteamUI_UpdateControllerFirmware_Failure_fiowrite"			"Firmware-opdatering mislykkedes: ERROR-fiowrite. Kontakt venligst Steam Support."
	"SteamUI_UpdateControllerFirmware_Failure_bin"				"Firmware-opdatering mislykkedes: ERROR-bin. Kontakt venligst Steam Support."
	"SteamUI_UpdateControllerFirmware_Failure_empty"			"Firmware-opdatering mislykkedes: ERROR-empty. Kontakt venligst Steam Support."
	"SteamUI_UpdateControllerFirmware_Failure_platform"			"Firmware-opdatering mislykkedes: Din platform understøttes på nuværende tidspunkt ikke."
	"SteamUI_UpdateControllerFirmware_Failure_NoVolume"			"Kunne ikke finde lager-bootloader. Tjek venligst din enheds usb-forbindelse"
	"SteamUI_UpdateControllerFirmware_Disconnect"	"Din Steam Controller blev afbrudt under firmware-opdateringsprocessen. Du har mulighed for at opdatere firmwaren, når controlleren forbindes igen."
	"SteamUI_UpdateControllerFirmware_WiredUpdate"	"Din controller kræver en engangsopdatering med ledning.\n\nForbind controlleren med USB-kablet og så starter opdateringen automatisk.\n"
	"SteamUI_UpdateControllerFirmware_UpdateTitle" "Controller-firmwareopdatering"
	"SteamUI_UpdateControllerFirmware_HardFailure" "Advarsel: En af dine Steam Controllers er blevet deaktiveret og vil ikke blive rekonfigureret eller programmeret til spil, fordi dens firmware er forældet og fordi Steam ikke kunne hente oplysninger om opdateret firmware."
	"SteamUI_UpdateDongleFirmware_OutofDate"	"FEJL: Du bruger en controller-dongle, der er for gammel. Kom hen og få en ny fra vores Controller Team."
	"SteamUI_UpdateDongleFirmware_OutofDateHeader" "Forældet controller-dongle"

	"SteamUI_SystemResetConfirmation_Title"	"Genstart system"
	"SteamUI_SystemResetConfirmation_Intro"	"Er du sikker på, at du vil gøre dette?"
	"SteamUI_StreamingSystemResetConfirmation_Intro"	"Er du sikker på, at du vil gøre dette?\nHvis Steam ikke starter og logger ind automatisk ved start, er du nødt til at logge på Steam, efter din computer genstarter."
	"SteamUI_SystemSuspendConfirmation_Title"	"Suspender system"
	"SteamUI_SystemSuspendConfirmation_Intro"	"Er du sikker på, at du vil gøre dette?"
	"SteamUI_StreamingSystemSuspendConfirmation_Intro"	"Er du sikker på, at du vil gøre dette?\nHvis din computer ikke understøtter \"Wake On LAN\" eller er på et andet subnet, er du nødt til at vække din computer manuelt."
	"SteamUI_SystemShutdownConfirmation_Title"	"Slå system fra"
	"SteamUI_SystemShutdownConfirmation_Intro"	"Er du sikker på, at du vil gøre dette?"
	"SteamUI_StreamingSystemShutdownConfirmation_Intro"	"Er du sikker på, at du vil gøre dette?\nHvis din computer ikke understøtter \"Wake On LAN\" eller er på et andet subnet, er du nødt til at vække din computer manuelt og sikre, at du er logget på Steam."
	"SteamUI_SystemPowerConfirmation_Confirm" "Bekræft"
	"SteamUI_SystemPowerConfirmation_Cancel" "Annuller"
	"SteamUI_QuitBigPicture_Title" "Kan ikke afslutte – spil kører stadig"
	"SteamUI_QuitBigPicture_Intro" "Afslut alle spil, før du lukker Big Picture-tilstand. Hvis du gennemtvinger lukning af Big Picture-tilstand, stopper Steam-funktioner såsom controller-understøttelse med at virke i spil, der kører lige nu."
	"SteamUI_QuitBigPicture_ForceQuit" "Gennemtving lukning"

	"SteamUI_ConfirmPassword_Select" "VÆLG"
	"SteamUI_ConfirmPassword_EnterPassword" "Indtast din adgangskode for at fortsætte"
	"SteamUI_ConfirmPassword_Password"	"SEND"
	"SteamUI_ConfirmPassword_FailureTitle" "FORKERT ADGANGSKODE"
	"SteamUI_ConfirmPassword_Failure" "Den adgangskode er forkert. Prøv venligst igen."

	"LostAuthenticator_Title"					"Nulstil authenticator"
	"LostAuthenticator_SendingSms_Description"	"Idet din konto har en telefon tilknyttet, så sender vi en bekræftende SMS-kode til din telefon."

	"LostAuthenticator_Password_Description"	"Før vi kan nulstille din Steam Guard-authenticator, har vi brug for din kontos adgangskode. Indtast den venligst nedenfor."
	"LostAuthenticator_Password"				"Adgangskode"
	"LostAuthenticator_ShowPassword"			"Vis adgangskode"
	"LostAuthenticator_SmsOrRecoveryCode"		"Hvis du kan huske koden, du modtog da du tilmeldte dig Steam Guard-authenticator (den består af et R efterfulgt af nogle cifre), så kan du bruge den til at nulstille din authenticator.\n\nEllers kan vi sende en SMS til telefonen, som er registreret på din konto."
	"LostAuthenticator_UseRCode"				"Jeg kan huske min tilmeldingskode"
	"LostAuthenticator_UseSms"					"Send min telefon en SMS-kode"
	"LostAuthenticator_EnterRecoveryCode_Description"	"Indtast venligst authenticator-tilmeldingskoden nedenfor (den består af et R efterfulgt af nogle cifre)."
	"LostAuthenticator_EnterSmsCode_Description"		"Indtast venligst SMS-koden, vi lige har sendt til din telefon."
	"LostAuthenticator_RCode"					"Gendannelseskode (ser sådan ud R......)"
	"LostAuthenticator_SmsCode"					"SMS-kode"
	"LostAuthenticator_Working"					"Vent venligst..."
	"LostAuthenticator_Success_Description"		"Succes! Du har fjernet din Steam Guard-authenticator fra din konto.\n\nDu bør nu kunne logge på uden din authenticator."
	"LostAuthenticator_Error_Description"		"Beklager, der opstod en fejl ved nulstillingen af din authenticator."
	"LostAuthenticator_IncorrectPassword"		"Beklager, adgangskoden er ikke korrekt. Prøv venligst igen."

	"AccountRecovery_SmsError_Title"			"Ups!"
	"AccountRecovery_SmsError_Desciption"		"Beklager, der opstod et problem med at sende SMS'en til din telefon."
	"AccountRecovery_SmsError_RateLimit"		"Vi har sendt for mange beskeder til din telefon eller din konto. Vent venligst lidt tid før du prøver igen."

//	"LostAuthenticator_GetCodes_Description"	"Next we need the code that we just sent you in email, and the code that you were given to write down when you signed up for the authenticator (it starts with R and ends in some digits)."
//	"LostAuthenticator_BadCodesError"			"Bad email code or sign-up code, please try again."
//	"LostAuthenticator_Description"				"We need some information to remove the Steam Guard authenticator from your account, starting with your account name and current password."
//	"LostAuthenticator_NextField"				"Next"
//	"LostAuthenticator_ValidationCode"			"Email code"
//	"LostAuthenticator_Working"					"Working"

	"You_Are_Offline"						"Du er i offline-tilstand"
	"You_Are_Offline2"						"Dette indhold er ikke tilgængeligt i offline-tilstand. For at afslutte offline-tilstand og se dette indhold, så vend tilbage til hovedmenuen og vælg knappen \"Offline\" i øverste række."
	"Community_Offline2"					"Fællesskabsindhold er ikke tilgængeligt i offline-tilstand. For at afslutte offline-tilstand og se fællesskabsindhold, så vend tilbage til hovedmenuen og vælg knappen \"Offline\" i øverste række."
	"Profile_Offline2"						"Dit profilindhold er ikke tilgængeligt i offline-tilstand. For at afslutte offline-tilstand, og se fællesskabsindhold, skal du vende tilbage til hovedmenuen og vælge Offline-knappen øverst."

	"Panel_Download_Error"					"En fejl opstod"
	"Panel_Download_Error2"					"En uforventet fejl opstod under hentningen af oplysninger fra Steam."

	"Broadcast_ChatJoined"					"{s:persona} sluttede sig til chatten"
	"Broadcast_ChatLeft"					"{s:persona} forlod chatten"
	"Broadcast_ChatMuted"					"{s:persona} dæmpet"

	"SettingsInterface_DeleteAllCookies"	"Slet alle browsercookies"
	"SettingsInterface_DeleteTitle"	"Slet cookies"
	"SettingsInterface_DeleteMsg"	"Ryd al data for Steam-browser-cookies?"

	"SettingsInterface_ClearWebCache"		"Ryd browser-cache"
	"SettingsInterface_ClearWebCacheTitle"	"Ryd browser-cache"
	"SettingsInterface_ClearWebCacheMsg"	"Slet alle filer i den indbyggede webbrowser-cache?"

	"SettingsDiskManagement_UnknownApp" "Ukendt navn"
	"Settings_DiskManagement"	"Diskhåndtering"
	"Settings_DiskManagement_Intro" "Følgende emner er installeret på din lokale harddisk. For at frigøre diskplads kan du vælge at slette lokalt indhold. Bemærk, at slettede emner forbliver i dit Steam-bibliotek, men for at kunne spille dem fremover er du nødt til at downloade indholdet igen."
	"Settings_DiskManagement_Folder" "Vælg biblioteksmappe "
	"Settings_DiskManagement_App"	"EMNE"
	"Settings_DiskManagement_Size"	"STØRRELSE PÅ DISK"
	"Settings_DiskManagement_AppName" "{s:appname}"
	"SettingsDiskManagement_Delete_Title" "Slet dette emne?"
	"SettingsDiskManagement_Delete_Description" "Er du sikker på, du vil slette {s:appname}? For at spille det fremover er du nødt til at downloade det igen."
	"SettingsDiskManagement_ViewInLibrary" "VIS I BIBLIOTEK"
	"SettingsDiskManagement_DeleteApp" "SLET"
	"SettingsDiskManagement_MakeDefaultFolder" "GØR TIL STANDARDMAPPE"
	"SettingsDiskManagement_UnknownDisk" "Uk