e indstilling er aktiveret, lukker menuen af sig selv, når en handling er blevet udført."
	"ControllerBinding_HotbarDismissAfterActivation_Off"	"Luk efter aktivering – Fra"
	"ControllerBinding_HotbarDismissAfterActivation_Off_Description"	"Når denne indstilling er deaktiveret, forbliver menuen synlig, når en handling er blevet udført."
	"ControllerBinding_HotbarRecenterEachTime"	"Centrer hver gang"
	"ControllerBinding_HotbarRecenterEachTime_Description"	"Med denne indstilling kan menuen enten huske det forrige valgte element eller nulstille til det midterste element."
	"ControllerBinding_HotbarRecenterEachTime_On"	"Centrer hver gang – Til"
	"ControllerBinding_HotbarRecenterEachTime_On_Description"	"Når denne indstilling er aktiveret, åbnes menuen på den midterste binding hver gang."
	"ControllerBinding_HotbarRecenterEachTime_Off"	"Centrer hver gang – Fra"
	"ControllerBinding_HotbarRecenterEachTime_Off_Description"	"Når denne indstilling er deaktiveret, husker menuen den valgte binding fra sidste gang, den var åben."
	"ControllerBinding_HotbarScrollWrap"	"Fortløbende rulning"
	"ControllerBinding_HotbarScrollWrap_Description"	"Når menuen kommer til slutningen af bindingslisten, kan den enten fortsætte til den anden side eller stoppe med at rulle."
	"ControllerBinding_HotbarScrollWrap_On"	"Fortløbende rulning – Til"
	"ControllerBinding_HotbarScrollWrap_On_Description"	"Når denne indstilling er aktiveret, fortsætter menuen til den anden side, når du ruller til slutningen af bindingslisten."
	"ControllerBinding_HotbarScrollWrap_Off"	"Fortløbende rulning – Fra"
	"ControllerBinding_HotbarScrollWrap_Off_Description"	"Når denne indstilling er deaktiveret, stopper menuen med at rulle, når den kommer til slutningen af bindingslisten."

	//MouseRegion
	"ControllerBinding_ModeDropDown_MouseRegion" "Inputtype - Museregion"
	"ControllerBinding_ModeDropDown_MouseRegion_Description" "Dette input vil fungere som en museregion. En museregion sender museinput til et spil, men betragter fladen som 1:1-afbildning af skærmområdet, så hvis du rører et bestemt sted på fladen, vil det altid anbringe markøren samme sted på skærmen. Udover at dette virker godt i spil, der styres fra oven, kan regioner begrænses til visse områder på skærmen, skaleres, strækkes og tilstandsskiftes, så der kan vælges elementer såsom kort, værktøjslinjer, inventarer osv."
	"ControllerBinding_MouseRegionClick" "Klikhandling"
	"ControllerBinding_MouseRegionClick_Description" "Denne handling udføres, når du klikker med fladen/styrepinden."
	"ControllerBinding_ScaleMouseRegion" "Regionsstørrelse"
	"ControllerBinding_ScaleMouseRegion_Description" "Dette vil skalere størrelsen af regionen, som er afbildet til det ydre område af fladen/styrepinden."
	"ControllerBinding_PositionXMouse" "Vandret position for region"
	"ControllerBinding_PositionXMouse_Description" "Dette er den vandrette position på skærmen, som regionen bliver centreret omkring."
	"ControllerBinding_PositionYMouse" "Lodret position for region"
	"ControllerBinding_PositionYMouse_Description" "Dette er den lodrette position på skærmen, som regionen bliver centreret omkring."
	"ControllerBinding_TeleportStart" "Flyt mus ved tilstandsaktivering"
	"ControllerBinding_TeleportStart_On" "Flyt mus ved tilstandsaktivering"
	"ControllerBinding_TeleportStart_Off" "Flyt mus ved tilstandsaktivering"
	"ControllerBinding_TeleportStart_Description" "Når tilstanden aktiveres, skal musen da flyttes til centrum af regionen?"
	"ControllerBinding_TeleportStart_On_Description"	"Flyt museposition til midten af regionen ved tilstandsaktivering"
	"ControllerBinding_TeleportStart_Off_Description"	"Bevar nuværende museposition"
	"ControllerBinding_TeleportStop" "Nulstil mus ved stop/slut på tilstandsskift"
	"ControllerBinding_TeleportStop_Description" "Når du stopper med at røre, eller slår tilstandsskift fra, skal musen da flyttes tilbage til positionen, den var i, før tilstandsskift blev slået til?"
	"ControllerBinding_TeleportStop_On" "Snapback - Til"
	"ControllerBinding_TeleportStop_On_Description" "Dette vil få musen til at springe tilbage til en tidligere position, når touchpaden frigives eller ved slutningen af tilstandskiftet."
	"ControllerBinding_TeleportStop_Off" "Snapback - Fra"
	"ControllerBinding_TeleportStop_Off_Description" "Dette vil efterlade musepositionen, hvor den er, når touchpaden frigives eller ved slutningen af tilstandskiftet."
	"ControllerBinding_HorizontalSensitivityMouseRegion" "Vandret skala"
	"ControllerBinding_HorizontalSensitivityMouseRegion_Description" "Skalerer den vandrette region. Du kan bruge dette til at ændre regionen på skærmen fra en cirkel til en ellipse eller en linje."
	"ControllerBinding_VerticalSensitivityMouseRegion" "Lodret skala"
	"ControllerBinding_VerticalSensitivityMouseRegion_Description" "Skalerer den lodrette region. Du kan bruge dette til at ændre regionen på skærmen fra en cirkel til en ellipse eller en linje."
	"ControllerBinding_MouseRegionTouch" "Berøringsbinding"
	"ControllerBinding_MouseRegionTouch_Description" "En handling kan sendes, når fladen berøres. Denne knap bliver sluppet, når du stopper med at røre."
	// Radial Menu
	"ControllerBinding_ModeDropDown_RadialMenu" "Inputtype - Cirkelmenu"
	"ControllerBinding_ModeDropDown_RadialMenu_Description" "Dette input vil fungere som en cirkelmenu. Cirkelmenuer vises på skærmen, når din finger berører touchpaden. Når du klikker på én af de viste knapper, udføres den tildelte handling. Cirkelmenuer kan have flere slags knapper, layout, størrelse, gennemsigtighed og kan desuden bruge ikoner."
	"ControllerBinding_RadialMenuPosX" "Cirkelmenuens vandrette position"
	"ControllerBinding_RadialMenuPosX_Description" "Dette bestemmer, hvor cirkelmenuen bliver vist på skærmen. Juster denne slider for at ændre den vandrette position."
	"ControllerBinding_RadialMenuPosY" "Cirkelmenuens lodrette position"
	"ControllerBinding_RadialMenuPosY_Description" "Dette bestemmer, hvor cirkelmenuen bliver vist på skærmen. Juster denne slider for at ændre den lodrette position."
	"ControllerBinding_RadialMenuButtonType" "Aktiveringsstil for touch-menu"
	"ControllerBinding_RadialMenuButtonType_Description" "Denne indstilling styrer, hvilket slags input der aktiverer menupunktet."
	"ControllerBinding_RadialMenuButton0" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton0_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton1" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton1_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton2" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton2_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton3" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton3_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton4" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton4_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton5" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton5_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton6" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton6_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton7" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton7_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton8" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton8_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton9" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton9_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton10" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton10_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton11" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton11_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton12" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton12_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton13" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton13_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton14" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton14_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton15" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton15_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton16" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton16_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton17" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton17_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton18" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton18_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton19" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton19_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialMenuButton20" "Cirkelmenuknap"
	"ControllerBinding_RadialMenuButton20_Description" "Du kan binde handlinger til denne skærmknap."
	"ControllerBinding_RadialClick" "Cirkelmenuknap"
	"ControllerBinding_RadialClick_Description" "Du kan binde handlinger, til når der klikkes på dette input. Dette er især brugbart, når det kombineres med menuaktiveringstypen \"Altid til\"."
	"ControllerBinding_RadialMenuOpacity" "Cirkelmenuens gennemsigtighed"
	"ControllerBinding_RadialMenuOpacity_Description" "Denne slider angiver, hvor gennemsigtig cirkelmenuen er på skærmen."
	"ControllerBinding_RadialMenuScale" "Cirkelmenuens størrelse"
	"ControllerBinding_RadialMenuScale_Description" "Denne slider angiver cirkelmenuens størrelse på skærmen."
	"ControllerBinding_RadialMenuShowLabels" "Visning af bindingsmærke på cirkelmenu"
	"ControllerBinding_RadialMenuShowLabels_Description" "Cirkelmenuknapper kan vise et stykke tekst for at præcisere, hvad der er bundet til dem på den egentlige knap. Hvis der bruges et ikon, vises denne tekst i det øvre venstre hjørne. Hvis teksten er slået fra, bruges ikonet eller en blank knap."
	"ControllerBinding_RadialMenuButtonType_ButtonClick" "Knapklik"
	"ControllerBinding_RadialMenuButtonType_ButtonClick_Description" "Dette aktiverer menupunktet, når knappen klikkes."
	"ControllerBinding_RadialMenuButtonType_ButtonRelease" "Slip af knap"
	"ControllerBinding_RadialMenuButtonType_ButtonRelease_Description" "Dette aktiverer menupunktet, når knappen frigives."
	"ControllerBinding_RadialMenuButtonType_TouchRelease" "Ophør af berøring/tilstandsskift ender"
	"ControllerBinding_RadialMenuButtonType_TouchRelease_Description" "Dette aktiverer menupunktet, når trackpaden ikke længere berøres eller når tilstandsknappen frigives. For joysticks betragtes alle positioner uden for dødszonen for at være berørt."
	"ControllerBinding_RadialMenuButtonType_TouchAlways" "Altid"
	"ControllerBinding_RadialMenuButtonType_TouchAlways_Description" "Dette aktiverer menupunktet kontinuerligt, så længe trackpaden/styrepinden berøres. For joysticks, betragtes alle positioner uden for dødszonen for at være berørt."
	"ControllerBinding_RadialMenuShowLabels_On" "Vis bindingsmærke på knap - Til"
	"ControllerBinding_RadialMenuShowLabels_On_Description" "Dette aktiverer visning af bindingsmærket på knappen. Hvis der bruges et ikon, vises denne tekst i knappens øvre venstre hjørne."
	"ControllerBinding_RadialMenuShowLabels_Off" "Vis bindingsmærke på knap - Fra"
	"ControllerBinding_RadialMenuShowLabels_Off_Description" "Dette deaktiverer visning af bindingsmærket på knappen og viser i stedet ikonet eller en blank knap."
	
	"ControllerBinding_RecommendedTemplate" "Anbefalet"
	"ControllerBinding_SavedCopyPasta_Title" "Tilpasset controller-konfiguration uploadet!"
	"ControllerBinding_SavedCopyPasta" "Din controller-konfiguration blev uploadet, og et link er blevet kopieret til din udklipsholder.\nID: {s:fileid}"
	"ControllerBinding_PrivateUploadSuccess" "Succes!"
	"ControllerBinding_PrivateUploadSuccess_Description" "Din controller-konfiguration er blevet uploadet."

	"ControllerBinding_Official" "Officiel udviklerkonfiguration"
	"ControllerBinding_OfficialDescription" "Denne konfiguration blev skabt af udviklerne af dette spil."
	"ControllerBinding_HeaderLoad" "Controller-konfigurationer - Importer"
	"ControllerBinding_HeaderSave" "Controller-konfigurationer - Eksporter"
	"ControllerBinding_Explanation_template" "Generelle konfiguration-layouts. Gode startpunkter til at bygge en konfiguration."
	"ControllerBinding_Explanation_personal" "Konfigurationer du har eksporteret til dette spil."
	"ControllerBinding_Explanation_community" "Fællesskabsskabte konfigurationer til dette spil."
	"ControllerBinding_Explanation_recommended" "Anbefalede konfigurationer til dette spil."
	"ControllerBinding_Explanation_entirelibrary" "Alle dine personlige konfigurationer du har eksporteret fra alle spil."
	"ControllerBinding_Explanation_friends" "Konfigurationer lavet af dine venner."
	"ControllerBinding_Missing_template" "Der er ingen passende skabeloner til dette spil."
	"ControllerBinding_Missing_personal" "Du har ikke gemt nogen konfigurationer til dette spil."
	"ControllerBinding_Missing_community" "Der er ingen fællesskabsskabte konfigurationer til dette spil.\nMåske kunne du være den første, der udgiver en?"
	"ControllerBinding_Missing_recommended" "Udvikleren af dette spil har endnu ikke anbefalet en konfiguration."
	"ControllerBinding_Missing_friends" "Ingen af dine venner har eksporteret en konfiguration til fællesskabet"
	"ControllerBinding_NonMigrated_config"	"[Lokal konfiguration]"
	"ControllerBinding_Autosave_config"		"[Lokal, auto-gemt oprin