ivator til start af tryk aktiverer, når der trykkes på en knap. Den deaktiverer med det samme, selv hvis knappen fortsat holdes nede. Dette er især brugbart, når det bruges med en aktivator til slip af tryk, da den dermed kan lave en til/fra-funktion om til en hold nede-funktion, såsom at dukke sig."
	"ControllerBinding_ActivatorDropDown_Release" "Aktivator - Slip af tryk"
	"ControllerBinding_ActivatorDropDown_Release_Description" "En aktivator til slip af tryk aktiverer og deaktiverer, når der gives slip på knappen."
	"ControllerBinding_ActivatorDropDown_Chord" "Aktivator - Genvejsknap"
	"ControllerBinding_ActivatorDropDown_Chord_Description" "Aktivatoren til genvejsknappen slås til, når der trykkes på knappen, der er tilknyttet aktivatoren, og genvejsknappen samtidigt."

	"ControllerBinding_FullPress_Binding" "Binding"
	"ControllerBinding_FullPress_Binding_Description" "Du kan binde én eller flere handlinger til denne aktivator, såsom tastatur-, muse- eller gamepad-knapper eller indbyggede handlinger."
	"ControllerBinding_FullPress_ActivateStickOrTrackpad" "Aktiver analogpind/trackpad"
	"ControllerBinding_FullPress_ActivateStickOrTrackpad_Description" "Virtuelle controllere kan oprette en virtuel styrepind eller trackpad under en knap, mens der trykkes på den. Dette kan f.eks. bruges til maskingeværer, hvor man sigter med den samme finger, som holder aftrækkeren nede."
	"ControllerBinding_FullPress_ActivateStickOrTrackpad_Off" "Ingen analogpind/trackpad"
	"ControllerBinding_FullPress_ActivateStickOrTrackpad_Off_Description" "Denne aktivator fungerer normalt og aktiverer ikke en virtuel analogpind eller trackpad."
	"ControllerBinding_FullPress_ActivateStickOrTrackpad_LeftJoystick" "Aktiver venstre analogpind"
	"ControllerBinding_FullPress_ActivateStickOrTrackpad_LeftJoystick_Description" "Mens denne knap holdes nede, vil samme finger også styre den virtuelle venstre analogpind."
	"ControllerBinding_FullPress_ActivateStickOrTrackpad_RightJoystick" "Aktiver højre analogpind"
	"ControllerBinding_FullPress_ActivateStickOrTrackpad_RightJoystick_Description" "Mens denne knap holdes nede, vil samme finger også styre den virtuelle højre analogpind."
	"ControllerBinding_FullPress_ActivateStickOrTrackpad_Trackpad" "Aktiver midtertrackpad"
	"ControllerBinding_FullPress_ActivateStickOrTrackpad_Trackpad_Description" "Mens denne knap holdes nede, vil samme finger også styre den virtuelle midtertrackpad."
	"ControllerBinding_FullPress_ActivateStickOrTrackpad_LeftTrackpad" "Aktiver venstre trackpad"
	"ControllerBinding_FullPress_ActivateStickOrTrackpad_LeftTrackpad_Description" "Når denne knap holdes nede, vil samme finger også styre den virtuelle venstre trackpad."	
	"ControllerBinding_FullPress_ActivateStickOrTrackpad_RightTrackpad" "Aktiver højre trackpad"
	"ControllerBinding_FullPress_ActivateStickOrTrackpad_RightTrackpad_Description" "Når denne knap holdes nede, vil samme finger også styre den virtuelle højre trackpad."
	"ControllerBinding_FullPress_Toggle" "Slå til/fra"
	"ControllerBinding_FullPress_Toggle_Description" "\"Slå til\" får denne aktivator til at forblive aktiv, efter der gives slip på den, og indtil den trykkes på igen."
	"ControllerBinding_FullPress_Toggle_On" "Slå til"
	"ControllerBinding_FullPress_Toggle_On_Description" "Denne aktivator fortsætter med at være aktiv, efter der gives slip, indtil der trykkes på den igen."
	"ControllerBinding_FullPress_Toggle_Off" "Slå fra"
	"ControllerBinding_FullPress_Toggle_Off_Description" "Denne aktivator vil fungere som en traditionel knap, hvor den forbliver aktiveret, indtil knappen slippes."
	"ControllerBinding_FullPress_Interruptable" "Afbrydelig"
	"ControllerBinding_FullPress_Interruptable_Description" "Afbrydelige aktivatorer kan sættes på pause eller stoppes af andre aktivatorer. For eksempel kan en aktivator til et langt tryk afbryde en aktivator til et fuldt tryk, så det fulde tryk kun udføres, hvis det lange tryk ikke gør. Hvis aktivatoren ikke sættes som afbrydelig, ignorerer den andre aktivatorer i sin udførsel."
	"ControllerBinding_FullPress_Interruptable_On" "Afbrydelig - Til"
	"ControllerBinding_FullPress_Interruptable_On_Description" "Denne aktivator sættes på pause eller aktiveres ikke overhovedet, hvis andre aktivatorer er i gang. Langt tryk, dobbelttryk osv. får den til at vente på, at dens betingelser opfyldes, før aktivatoren kan aktivere sig selv. Hvis de andre aktivatorer aktiverer, gør denne ikke."
	"ControllerBinding_FullPress_Interruptable_Off" "Afbrydelig - Fra"
	"ControllerBinding_FullPress_Interruptable_Off_Description" "Denne aktivator vil ignorere andre aktivatorer og aktiverer/deaktiverer altid, som hvis den var den eneste."
	"ControllerBinding_FullPress_StartDelay" "Aktiveringsforsinkelse"
	"ControllerBinding_FullPress_StartDelay_Description" "Efter der trykkes på knappen, vil aktivatoren vente i denne mængde tid, før den aktiverer. Denne forsinkelse vil forskyde hele perioden, knappen holdes nede, så hvis der ikke er angivet nogen deaktiveringsforsinkelse, så er den samlede varighed, knappen holdes nede, uændret men blot forsinket."
	"ControllerBinding_FullPress_EndDelay" "Deaktiveringsforsinkelse"
	"ControllerBinding_FullPress_EndDelay_Description" "Efter der gives slip på knappen, vil aktivatoren vente i denne mængde tid, før den deaktiverer. Deaktiveringsforsinkelsen får en knap til at forblive aktiv i længere tid, end den fysisk holdes nede."
	"ControllerBinding_FullPress_HapticIntensity" "Haptisk styrke"
	"ControllerBinding_FullPress_HapticIntensity_Description" "Dette indstiller styrken af haptik ved aktivering og deaktivering af aktivatoren."
	"ControllerBinding_FullPress_HapticIntensity_Off" "Haptisk styrke - Fra"
	"ControllerBinding_FullPress_HapticIntensity_Off_Description" "Ingen haptik."
	"ControllerBinding_FullPress_HapticIntensity_Low" "Haptisk styrke - Lav"
	"ControllerBinding_FullPress_HapticIntensity_Low_Description" "Lav haptik ved aktivering og deaktivering af aktivatoren."
	"ControllerBinding_FullPress_HapticIntensity_Medium" "Haptisk styrke - Medium"
	"ControllerBinding_FullPress_HapticIntensity_Medium_Description" "Medium haptik ved aktivering og deaktivering af aktivatoren."
	"ControllerBinding_FullPress_HapticIntensity_High" "Haptisk styrke - Høj"
	"ControllerBinding_FullPress_HapticIntensity_High_Description" "Høj haptik ved aktivering og deaktivering af aktivatoren."
	"ControllerBinding_FullPress_CycleBindings" "Bindinger i rækkefølge"
	"ControllerBinding_FullPress_CycleBindings_Description" "Bindinger i rækkefølge får denne aktivator til at udføre hver af sine bindinger i den angivne rækkefølge, hver gang den aktiveres. Rækkefølgen afhænger af, i hvilken rækkefølge bindingerne blev valgt."
	"ControllerBinding_FullPress_CycleBindings_On" "Bindinger i rækkefølge - Til"
	"ControllerBinding_FullPress_CycleBindings_On_Description" "Når det er slået til, får det denne aktivator til at udføre hver binding i den angivne rækkefølge, hver gang den aktiveres."
	"ControllerBinding_FullPress_CycleBindings_Off" "Bindinger i rækkefølge - Fra"
	"ControllerBinding_FullPress_CycleBindings_Off_Description" "Når det er slået fra, udføres alle bindinger på samme tid."
	"ControllerBinding_FullPress_HoldRepeats" "Hold nede for at gentage (Turbo)"
	"ControllerBinding_FullPress_HoldRepeats_Description" "Turbo får denne aktivator til at aktivere og deaktivere meget hurtigt, mens den holdes nede. Kan bruges sammen med funktionen \"Bindinger i rækkefølge\"."
	"ControllerBinding_FullPress_HoldRepeats_On" "Hold nede for at gentage (Turbo) - Til"
	"ControllerBinding_FullPress_HoldRepeats_On_Description" "Turbo får denne aktivator til at aktivere og deaktivere meget hurtigt, mens den holdes nede. Kan bruges sammen med funktionen \"Bindinger i rækkefølge\"."
	"ControllerBinding_FullPress_HoldRepeats_Off" "Hold nede for at gentage (Turbo) - Fra"
	"ControllerBinding_FullPress_HoldRepeats_Off_Description" "Når den er slået fra, udløses gentagelse ikke, når knappen holdes nede."
	"ControllerBinding_FullPress_RepeatRate" "Gentagelseshastighed"
	"ControllerBinding_FullPress_RepeatRate_Description" "Denne slider angiver turbofunktionens hastighed."

	"ControllerBinding_DoublePress_Binding" "Binding"
	"ControllerBinding_DoublePress_Binding_Description" "Du kan binde én eller flere handlinger til denne aktivator, såsom tastatur-, muse- eller gamepad-knapper eller indbyggede handlinger."
	"ControllerBinding_DoublePress_Toggle" "Skift"
	"ControllerBinding_DoublePress_Toggle_Description" "\"Slå til\" får denne aktivator til at forblive aktiv, efter der gives slip på den, og indtil den trykkes på igen."
	"ControllerBinding_DoublePress_Toggle_On" "Slå til"
	"ControllerBinding_DoublePress_Toggle_On_Description" "Denne aktivator fortsætter med at være aktiv, efter der gives slip, indtil den trykkes på igen."
	"ControllerBinding_DoublePress_Toggle_Off" "Slå fra"
	"ControllerBinding_DoublePress_Toggle_Off_Description" "Denne aktivator vil fungere som en traditionel knap, hvor den forbliver aktiveret, indtil knappen slippes."
	"ControllerBinding_DoublePress_DoubleTapTime" "Tid før dobbelttryk"
	"ControllerBinding_DoublePress_DoubleTapTime_Description" "Bestemmer hvor hurtigt du skal dobbelttrykke for at aktivere aktivatoren. Alle andre afbrydelige aktivator på dette input vil ikke aktivere, før den valgte tid er gået."
	"ControllerBinding_DoublePress_ActivateStickOrTrackpad" "Aktiver analogpind/trackpad"
	"ControllerBinding_DoublePress_ActivateStickOrTrackpad_Description" "Virtuelle controllere kan oprette en virtuel styrepind eller trackpad under en knap, mens der trykkes på den. Dette kan f.eks. bruges til maskingeværer, hvor man sigter med den samme finger, som holder aftrækkeren nede."
	"ControllerBinding_DoublePress_ActivateStickOrTrackpad_Off" "Ingen analogpind/trackpad"
	"ControllerBinding_DoublePress_ActivateStickOrTrackpad_Off_Description" "Denne aktivator fungerer normalt og aktiverer ikke en virtuel analogpind eller trackpad."
	"ControllerBinding_DoublePress_ActivateStickOrTrackpad_LeftJoystick" "Aktiver venstre analogpind"
	"ControllerBinding_DoublePress_ActivateStickOrTrackpad_LeftJoystick_Description" "Mens denne knap holdes nede, vil samme finger også styre den virtuelle venstre analogpind."
	"ControllerBinding_DoublePress_ActivateStickOrTrackpad_RightJoystick" "Aktiver højre analogpind"
	"ControllerBinding_DoublePress_ActivateStickOrTrackpad_RightJoystick_Description" "Mens denne knap holdes nede, vil samme finger også styre den virtuelle højre analogpind."
	"ControllerBinding_DoublePress_ActivateStickOrTrackpad_Trackpad" "Aktiver midtertrackpad"
	"ControllerBinding_DoublePress_ActivateStickOrTrackpad_Trackpad_Description" "Mens denne knap holdes nede, vil samme finger også styre den virtuelle midtertrackpad."
	"ControllerBinding_DoublePress_ActivateStickOrTrackpad_LeftTrackpad" "Aktiver venstre trackpad"
	"ControllerBinding_DoublePress_ActivateStickOrTrackpad_LeftTrackpad_Description" "Når denne knap holdes nede, vil samme finger også styre den virtuelle venstre trackpad."
	"ControllerBinding_DoublePress_ActivateStickOrTrackpad_RightTrackpad" "Aktiver højre trackpad"
	"ControllerBinding_DoublePress_ActivateStickOrTrackpad_RightTrackpad_Description" "Når denne knap holdes nede, vil samme finger også styre den virtuelle højre trackpad."
	"ControllerBinding_DoublePress_StartDelay" "Aktiveringsforsinkelse"
	"ControllerBinding_DoublePress_StartDelay_Description" "Efter der trykkes på knappen, vil aktivatoren vente i denne mængde tid, før den aktiverer. Denne forsinkelse vil forskyde hele perioden, knappen holdes nede, så hvis der ikke er angivet nogen deaktiveringsforsinkelse, så er den samlede varighed, knappen holdes nede, uændret men blot forsinket."
	"ControllerBinding_DoublePress_EndDelay" "Deaktiveringsforsinkelse"
	"ControllerBinding_DoublePress_EndDelay_Description" "Efter der gives slip på knappen, vil aktivatoren vente i denne mængde tid, før den deaktiverer. Deaktiveringsforsinkelsen får en knap til at forblive aktiv i længere tid, end den fysisk holdes nede."
	"ControllerBinding_DoublePress_HapticIntensity" "Haptisk styrke"
	"ControllerBinding_DoublePress_HapticIntensity_Description" "Dette indstiller styrken af haptik ved aktivering og deaktivering af aktivatoren."
	"ControllerBinding_DoublePress_HapticIntensity_Off" "Haptisk styrke - Fra"
	"ControllerBinding_DoublePress_HapticIntensity_Off_Description" "Ingen haptik."
	"ControllerBinding_DoublePress_HapticIntensity_Low" "Haptisk styrke - Lav"
	"ControllerBinding_DoublePress_HapticIntensity_Low_Description" "Lav haptik ved aktivering og deaktivering af aktivatoren."
	"ControllerBinding_DoublePress_HapticIntensity_Medium" "Haptisk styrke - Medium"
	"ControllerBinding_DoublePress_HapticIntensity_Medium_Description" "Medium haptik ved aktivering og deaktivering af aktivatoren."
	"ControllerBinding_DoublePress_HapticIntensity_High" "Haptisk styrke - Høj"
	"ControllerBinding_DoublePress_HapticIntensity_High_Description" "Høj haptik ved aktivering og deaktivering af aktivatoren."
	"ControllerBinding_DoublePress_CycleBindings" "Bindinger i rækkefølge"
	"ControllerBinding_DoublePress_CycleBindings_Description" "Bindinger i rækkefølge får denne aktivator til at udføre hver af sine bindinger i den angivne rækkefølge, hver gang den aktiveres. Rækkefølgen afhænger af, i hvilken rækkefølge bindingerne blev valgt."
	"ControllerBinding_DoublePress_CycleBindings_On" "Bindinger i rækkefølge - Til"
	"ControllerBinding_DoublePress_CycleBindings_On_Description" "Når det er slået til, får det denne aktivator til at udføre hver binding i den angivne rækkefølge, hver gang den aktiveres."
	"ControllerBinding_DoublePress_CycleBindings_Off" "Bindinger i rækkefølge - Fra"
	"ControllerBinding_DoublePress_CycleBindings_Off_Description" "Når det er slået fra, udføres alle bindinger på samme tid."
	"ControllerBinding_DoublePress_HoldRepeats" "Hold nede for at gentage (Turbo)"
	"ControllerBinding_DoublePress_HoldRepeats_Description" "Turbo får denne aktivator til at aktivere og deaktivere meget hurtigt, mens den holdes nede. Kan bruges sammen med funktionen \"Bindinger i rækkefølge\"."
	"ControllerBinding_DoublePress_HoldRepeats_On" "Hold nede for at gentage (Turbo) - Til"
	"ControllerBinding_DoublePress_HoldRepeats_On_Description" "Turbo får denne aktivator til at aktivere og deaktivere meget hurtigt, mens den holdes nede. Kan bruges sammen med funktionen \"Bindinger i rækkefølge\"."
	"ControllerBinding_DoublePress_HoldRepeats_Off" "Hold nede for at gentage (Turbo) - Fra"
	"ControllerBinding_DoublePress_HoldRepeats_Off_Description" "Når den er slået fra, udløses gentagelse ikke, når knappen holdes nede."
	"ControllerBinding_DoublePress_RepeatRate" "Gentagelseshastighed"
	"ControllerBinding_DoublePress_RepeatRate_Description" "Denne slider angiver turbofunktionens hastighed."

	"ControllerBinding_LongPress_Binding" "Binding"
	"ControllerBinding_LongPress_Binding_Description" "Du kan binde én eller flere handlinger til denne aktivator, såsom tastatur-, muse- eller gamepad-knapper eller indbyggede handlinger."
	"ControllerBinding_LongPress_Toggle" "Skift"
	"ControllerBinding_LongPress_Toggle_Description" "\"Slå til\" får denne aktivator til at forblive aktiv, efter der gives slip på den, og indtil den trykkes på igen."
	"ControllerBinding_LongPress_Toggle_On" "Slå til"
	"ControllerBinding_LongPress_Toggle_On_Description" "Denne aktivator fortsætter med at være aktiv, efter der gives slip, indtil den trykkes på igen."
	"ControllerBinding_LongPress_Toggle_Off" "Slå fra"
	"ControllerBinding_LongPress_Toggle_Off_Description" "Denne aktivator vil fungere som en traditionel knap, hvor den forbliver aktiveret, indtil knappen slippes."
	"ControllerBinding_LongPress_LongPressTime" "Tid før langt tryk"
	"ControllerBinding_LongPress_LongPressTime_Description" "Bestemmer hvor lang tid du skal holde knappen nede for at aktivere aktivatoren. Alle andre afbrydelige aktivator på dette input vil ikke aktivere, medmindre der gives slip på knappen før denne tid er gået, og de aktiverer slet ikke, hvis det lange tryk aktiveres."
	"ControllerBinding_LongPress_ActivateStickOrTrackpad" "Aktiver analogpind/trackpad"
	"ControllerBinding_LongPress_ActivateStickOrTrackpad_Description" "Virtuelle controllere kan oprette en virtuel styrepind eller trackpad under en knap, mens der trykkes på den. Dette kan f.eks. bruges til maskingeværer, hvor man sigter med den samme finger, som holder aftrækkeren nede."
	"ControllerBinding_LongPress_ActivateStickOrTrackpad_Off" "Ingen analogpind/trackpad"
	"ControllerBinding_LongPress_ActivateStickOrTrackpad_Off_Description" "Denne aktivator fungerer normalt og aktiverer ikke en virtuel analogpind eller trackpad."
	"ControllerBinding_LongPress_ActivateStickOrTrackpad_LeftJoystick" "Aktiver venstre analogpind"
	"ControllerBinding_LongPress_ActivateStickOrTrackpad_LeftJoystick_Description" "Mens denne knap holdes nede, vil samme finger også styre den virtuelle venstre analogpind."
	"ControllerBinding_LongPress_ActivateStickOrTrackpad_RightJoystick" "Aktiver højre analogpind"
	"ControllerBinding_LongPress_ActivateStickOrTrackpad_RightJoystick_Description" "Mens denne knap holdes nede, vil samme finger også styre den virtuelle højre analogpind."
	"ControllerBinding_LongPress_ActivateStickOrTrackpad_Trackpad" "Aktiver midtertrackpad"
	"ControllerBinding_LongPress_ActivateStickOrTrackpad_Trackpad_Description" "Mens denne knap holdes nede, vil samme finger også styre den virtuelle midtertrackpad."
	"ControllerBinding_LongPress_ActivateStickOrTrackpad_LeftTrackpad" "Aktiver venstre trackpad"
	"ControllerBinding_LongPress_ActivateStickOrTrackpad_LeftTrackpad_Description" "Når denne knap holdes nede, vil samme finger også styre den virtuelle venstre trackpad."	
	"ControllerBinding_LongPress_ActivateStickOrTrackpad_RightTrackpad" "Aktiver højre trackpad"
	"ControllerBinding_LongPress_ActivateStickOrTrackpad_RightTrackpad_Description" "Når denne knap holdes nede, vil samme finger også styre den virtuelle højre trackpad."
	"ControllerBinding_LongPress_StartDelay" "Aktiveringsforsinkelse"
	"ControllerBinding_LongPress_StartDelay_Description" "Efter der trykkes på knappen, vil aktivatoren vente i denne mængde tid, før den aktiverer. Denne forsinkelse vil forskyde hele perioden, knappen holdes nede, så hvis der ikke er angivet nogen deaktiveringsforsinkelse, så er den samlede varighed, knappen holdes nede, uændret men blot forsinket."
	"ControllerBi