oButtonInvert_joystick_move_Description" "Knapadfærden for gyroinputtet kan vendes. Hvis dette er slået fra, vil gyroen slå fra, når knappen er trykket ned."
	"ControllerBinding_GyroButtonInvert_joystick_move_On" "Gyro: Omvendt knapadfærd - Til"
	"ControllerBinding_GyroButtonInvert_joystick_move_On_Description" "Hvis dette er aktiveret, vil enhedens gyro tænde, når der trykkes på knappen."
	"ControllerBinding_GyroButtonInvert_joystick_move_Off" "Gyro: Omvendt knapadfærd - Fra"
	"ControllerBinding_GyroButtonInvert_joystick_move_Off_Description" "Hvis dette er aktiveret, vil enhedens gyro slukke, når der trykkes på knappen."
	"ControllerBinding_GyroButtonInvert_joystick_move_Toggle" "Gyro: Omvendt knapadfærd - til/fra"
	"ControllerBinding_GyroButtonInvert_joystick_move_Toggle_Description" "Hvis dette er aktiveret, vil gyroen skifte tilstand, hver gang der trykkes på knappen."
	"ControllerBinding_MouseSensitivity_joystick_move" "Musefølsomhed"
	"ControllerBinding_MouseSensitivity_joystick_move_Description" "Musemarkørens følsomhed når det virtuelle joysticks output er sat til mus."
	"ControllerBinding_HorizontalSensitivity_joystick_move" "Vandret skala"
	"ControllerBinding_HorizontalSensitivity_joystick_move_Description" "Skalerer den vandrette følsomhed. Dette ændrer bevægelsen på den vandrette akse relativt til den lodrette."
	"ControllerBinding_VerticalSensitivity_joystick_move" "Lodret skala"
	"ControllerBinding_VerticalSensitivity_joystick_move_Description" "Skalerer den lodrette følsomhed. Dette ændrer bevægelsen på den lodrette akse relativt til den vandrette."
	"ControllerBinding_GyroNeutralAngle_joystick_move" "Gyro: Neutral hældningsvinkel"
	"ControllerBinding_GyroNeutralAngle_joystick_move_description" "Dette er standardpositionen for et centreret joystick. Ved at ændre denne indstilling, kan du ændre den neutralt centrerede position til at hælde frem eller tilbage alt efter, hvad der er behageligt for din spilleposition. Bemærk at for at bruge det som et rat, anbefales det at deaktivere den lodrette position fuldstændigt og udelukkende bruge den vandrette akse, hvor denne vinkel ikke kommer i spil."
	"ControllerBinding_GyroLockExtents_joystick_move" "Gyro - lås ved kanter"
	"ControllerBinding_GyroLockExtents_joystick_move_description" "Hvis indstillet, vil controller-fladen låse til kanterne, hvis den roteres forbi yderkanten. Hvis slået fra, kan den vende til modsatte side, når den ydre kant overskrides. Hvis du oplever problemer med at controlleren låser over tid, kan det være, at du skal deaktivere denne mulighed."
	"ControllerBinding_GyroLockExtents_joystick_move_on" "Gyro - lås ved kanter"
	"ControllerBinding_GyroLockExtents_joystick_move_on_description" "Når dette er slået til og controller-fladen roteres forbi den ydre dødzone, låses den til den kant, indtil den drejes forbi 180 grader. Hvis det er slået fra, kan den begynde at rotere i modsat retning, når den nærmer sig 180 graders rotation. Hvis du oplever problemer med, at controlleren låser over tid, skal du deaktivere denne indstilling."
	"ControllerBinding_GyroLockExtents_joystick_move_off" "Gyro - lås ved kanter"																															  
	"ControllerBinding_GyroLockExtents_joystick_move_off_description" "Når dette er slået til og controller-fladen roteres forbi den ydre dødzone, låses den til den kant, indtil den drejes forbi 180 grader. Hvis det er slået fra, kan den begynde at rotere i modsat retning, når den nærmer sig 180 graders rotation. Hvis du oplever problemer med, at controlleren låser over tid, skal du deaktivere denne indstilling."
	//Joystick Mouse
	"ControllerBinding_ModeDropDown_Joystick_Mouse" "Inputtype - Joystickmus"
	"ControllerBinding_ModeDropDown_Joystick_Mouse_Description" "Dette input kontrollerer en mus med et joystick. Dette er beregnet til brug af et joystick med musebaserede applikationer. Da outputtet er en mus, skal applikationen understøtte musebaseret output."
	"ControllerBinding_OutputJoystick_joystick_mouse" "Joystickoutput"
	"ControllerBinding_OutputJoystick_joystick_mouse_Description" "Når der sendes analoge joystickkommandoer til spillet, skal disse kommandoer så ses af spillet som værende fra et venstre eller højre joystick?"
	"ControllerBinding_OutputJoystick_joystick_mouse_LeftJoystick" "Joystickoutput - Venstre"
	"ControllerBinding_OutputJoystick_joystick_mouse_LeftJoystick_Description" "Når der sendes analoge joystickkommandoer til spillet, så send et venstreanalogt joystick."
	"ControllerBinding_OutputJoystick_joystick_mouse_RightJoystick" "Joystickoutput - Højre"
	"ControllerBinding_OutputJoystick_joystick_mouse_RightJoystick_Description" "Når der sendes analoge joystickkommandoer til spillet, så send et højreanalogt joystick."
	"ControllerBinding_OutputJoystick_joystick_mouse_AbsoluteMouse" "Absolut mus som output"
	"ControllerBinding_OutputJoystick_joystick_mouse_AbsoluteMouse_Description" "Det virtuelle joysticks position afbildes direkte til hele skærmen. Museregionstilstand giver samme funktionalitet, men har flere konfigurationsmuligheder til det aktive område."
	"ControllerBinding_OutputJoystick_joystick_mouse_RelativeMouse" "Relativ mus som output"
	"ControllerBinding_OutputJoystick_joystick_mouse_RelativeMouse_Description" "Bevæg musemarkøren med det virtuelle joystick."
	"ControllerBinding_AdaptiveCentering_joystick_mouse" "Selvjusterende centrering"
	"ControllerBinding_AdaptiveCentering_joystick_mouse_Description" "Selvjusterende centrering behandler det første rørte punkt på trackpaden som det nye \"centrum\" af joysticket, hvor du trækker ud fra dette punkt for at bevæge joysticket rundt. Dette giver mulighed for at tommelfingeren kan anbringes excentrisk uden at forårsage utilsigtede bevægelser."
	"ControllerBinding_AdaptiveCentering_joystick_mouse_On" "Selvjusterende centrering - Til"
	"ControllerBinding_AdaptiveCentering_joystick_mouse_On_Description" "Selvjusterende centrering behandler det første rørte punkt på trackpaden som det nye \"centrum\" af joysticket, hvor du trækker ud fra dette punkt for at bevæge joysticket rundt. Dette giver mulighed for at tommelfingeren kan anbringes excentrisk uden at forårsage utilsigtede bevægelser."
	"ControllerBinding_AdaptiveCentering_joystick_mouse_Off" "Selvjusterende centrering - Fra"
	"ControllerBinding_AdaptiveCentering_joystick_mouse_Off_Description" "Trackpaden behandler centrummet af fladen som centrummet af joysticket, så berøring af områder uden for centrum svarer til at skubbe styrepinden til samme position, som var det en fysisk styrepind."
	"ControllerBinding_HapticIntensity_joystick_mouse" "Haptisk styrke"
	"ControllerBinding_HapticIntensity_joystick_mouse_Description" "Dette angiver styrken af haptik."
	"ControllerBinding_HapticIntensity_joystick_mouse_Off" "Haptisk styrke - Fra"
	"ControllerBinding_HapticIntensity_joystick_mouse_Off_Description" "Brug ikke haptik til denne tilstand."
	"ControllerBinding_HapticIntensity_joystick_mouse_Low" "Haptisk styrke - Lav"
	"ControllerBinding_HapticIntensity_joystick_mouse_Low_Description" "Brug haptik med lav styrke."
	"ControllerBinding_HapticIntensity_joystick_mouse_Medium" "Haptisk styrke - Medium"
	"ControllerBinding_HapticIntensity_joystick_mouse_Medium_Description" "Brug haptik med medium styrke."
	"ControllerBinding_HapticIntensity_joystick_mouse_High" "Haptisk styrke - Høj"
	"ControllerBinding_HapticIntensity_joystick_mouse_High_Description" "Brug haptik med høj styrke."
	"ControllerBinding_Click_joystick_mouse" "Klikhandling"
	"ControllerBinding_Click_joystick_mouse_Description" "Denne handling udføres, når du klikker med styrepinden."
	"ControllerBinding_EdgeBindingRadius_joystick_mouse" "Bindingsradius for ydre ring"
	"ControllerBinding_EdgeBindingRadius_joystick_mouse_Description" "Når uden for joystickets radius, så sendes den tildelte knap eller tast. For eksempel kan knappen for \"Løb\" eller \"Sprint\" tildeles, så man udfører den handling, når man holder i kanterne. Slideren kan visualiseres som at forlænge en radius fra centrum og udad, hvor sliderens punkt bestemmer, hvor den ydre ring starter."
	"ControllerBinding_EdgeBinding_joystick_mouse" "Tilknytning for ydre ring"
	"ControllerBinding_EdgeBinding_joystick_mouse_Description" "Når uden for den angivne radius på joysticket, så sendes den tildelte knap eller tast. For eksempel kan knappen for \"Løb\" eller \"Sprint\" tildeles, så man udfører den handling, når man holder i kanterne."
	"ControllerBinding_EdgeBindingInvert_joystick_mouse" "Inverter binding for ydre ring"
	"ControllerBinding_EdgeBindingInvert_joystick_mouse_Description" "Hvis det er slået til, bliver bindingen udført, når man er inden for radiussen, fremfor når man er uden for den. For eksempel kan handlingen for \"Gå\" eller \"Snig\" tildeles, så man udfører den handling, når man er inden for en vis zone."
	"ControllerBinding_EdgeBindingInvert_joystick_mouse_On" "Inverter ydre ring - Til"
	"ControllerBinding_EdgeBindingInvert_joystick_mouse_On_Description" "Den tildelte knap eller tast sendes, hvis den er inden for den angivne bindingsradius for den ydre ring. For eksempel kan knappen for \"Gå\" eller \"Snig\" tildeles, så man udfører den handling, når man er inden for en vis zone."
	"ControllerBinding_EdgeBindingInvert_joystick_mouse_Off" "Inverter ydre ring - Fra"
	"ControllerBinding_EdgeBindingInvert_joystick_mouse_Off_Description" "Den tildelte knap eller tast sendes, hvis den er uden for den angivne bindingsradius for den ydre ring. For eksempel kan knappen for \"Løb\" eller \"Sprint\" tildeles, så man udfører den handling, når man er uden for en vis zone."
	"ControllerBinding_CurveExponent_joystick_mouse" "Responskurve for styrepind"
	"ControllerBinding_CustomCurveExponent_joystick_mouse" "Tilpasset responskurve"
	"ControllerBinding_CustomCurveExponent_joystick_mouse_Description"	"Denne slider justerer outputværdien i joystickets responskurve."
	"ControllerBinding_CurveExponent_joystick_mouse_Description" "Dette bestemmer afbildningen af analogt input til output. Som standard bruges en 1:1-afbilding. Denne kurve kan ændres, så der enten er mere eller mindre plads til finjusteringer."
	"ControllerBinding_CurveExponent_joystick_mouse_Linear" "Responskurve - Lineær"
	"ControllerBinding_CurveExponent_joystick_mouse_Linear_Description" "En lineær responskurve konfigurerer inputtet direkte til outputtet med et forhold på 1:1. Ved 50% skub sendes 50% af outputtet."
	"ControllerBinding_CurveExponent_joystick_mouse_1" "Responskurve - Aggressiv"
	"ControllerBinding_CurveExponent_joystick_mouse_1_Description" "En aggressiv responskurve når hurtigere op på 100% output. Dette giver langsomt område i kort tid og når hurtigt det øvre outputs område med hurtigere respons."
	"ControllerBinding_CurveExponent_joystick_mouse_2" "Responskurve - Afslappet"
	"ControllerBinding_CurveExponent_joystick_mouse_2_Description" "En afslappet responskurve når langsommere op på 100% output. Der er en smule mere langsomt bevægelighedsområde, som kan bruges til at finjustere, og det øvre, hurtige bevægelighedsområde er skubbet længere mod kanterne."
	"ControllerBinding_CurveExponent_joystick_mouse_3" "Responskurve - Bred"
	"ControllerBinding_CurveExponent_joystick_mouse_3_Description" "En bred responskurve når meget langsommere op på 100% output end normalt. Der er et bredt antal lave værdier, som hurtigt øges i de ydre kanter. Dette resulterer i et bredt antal lave værdier i det indre område, som øges til maksimum uden for dette område."
	"ControllerBinding_CurveExponent_joystick_mouse_4" "Responskurve - Ekstra bred"
	"ControllerBinding_CurveExponent_joystick_mouse_4_Description" "En ekstra bred responskurve giver et meget bredt antal lave værdier og når kun op på 100% i de helt yderste grænser."
	"ControllerBinding_CurveExponent_joystick_mouse_Custom" "Responskurve - Tilpasset kurve"
	"ControllerBinding_CurveExponent_joystick_mouse_Custom_Description" "Der kan angives en tilpasset kurve ved at bruge slideren til at justere responskurven."
	"ControllerBinding_DeadZoneInnerRadius_joystick_mouse" "Indre dødszone"
	"ControllerBinding_DeadZoneInnerRadius_joystick_mouse_Description" "Joystickhandlinger sendes ikke, hvis de er inden for denne dødszone. Slideren kan visualiseres som at forlænge en radius fra centrum og udad, hvor helt til venstre betyder ingen dødszone, og helt til højre betyder at hele radiussen har dødszone påført sig. Analoge outputværdiers maksimum mappes til zonen mellem den indre og ydre dødszone. At udvide den indre dødszone tillader et større område i formen på dødszonen, hvor der ikke sendes noget input."
	"ControllerBinding_DeadZoneOuterRadius_joystick_mouse" "Ydre dødszone"
	"ControllerBinding_DeadZoneOuterRadius_joystick_mouse_Description" "Joystickhandlinger når maksimum, når de rammer den ydre dødszone. Slideren kan visualiseres som at forlænge en radius fra centrum og udad. Analoge outputværdiers maksimum mappes til zonen mellem den indre og ydre dødszone. At trække den ydre dødszone indad får outputtet til at nå sin fulde værdi hurtigere."
	"ControllerBinding_DeadZoneShape_joystick_mouse" "Form på dødszone"
	"ControllerBinding_DeadZoneShape_joystick_mouse_Description" "Der kan ændres form på dødszoner, så de bedre passer med forskellige spilstile. For eksempel er en krydsformet dødszone ofte bedst til bevægelse, hvor \"fremad\" primært holdes nede, og sidebevægelse dermed er inden for dødszonen, så bevægelse forbliver 100% lige."
	"ControllerBinding_DeadZoneShape_joystick_mouse_Cross" "Form på dødszone - Kryds"
	"ControllerBinding_DeadZoneShape_joystick_mouse_Cross_Description" "Den krydsformede dødszone behandler hver akse separat, hvor den indre dødszone er et \"bånd\" langs den akse. Dette skaber et kryds af dødszone formet som et + langs aksen. Dette er ofte bedst til bevægelse, hvor \"fremad\" primært holdes nede, og sidebevægelse dermed er inden for dødszonen, så bevægelse forbliver 100% lige."
	"ControllerBinding_DeadZoneShape_joystick_mouse_Circle" "Form på dødszone - Cirkel"
	"ControllerBinding_DeadZoneShape_joystick_mouse_Circle_Description" "En simpel cirkelformet dødszone. Ethvert input, mellem den indre og ydre dødszone, mappes til sin relative afstand mellem de to zoner. Input i den indre dødszone sendes ikke, mens input uden for den ydre dødszone sendes fuldt i den retning."
	"ControllerBinding_DeadZoneShape_joystick_mouse_Square" "Form på dødszone - Firkant"
	"ControllerBinding_DeadZoneShape_joystick_mouse_Square_Description" "Den firkantede dødszone bruger et kryds til at bestemme den indre dødszone men mapper også outputtet fra en cirkel til en firkant. Dette får output i diagonalerne til at nærme sig deres maksimale værdier hurtigere."
	"ControllerBinding_AntiDeadZone_joystick_mouse" "Anti-dødszone"
	"ControllerBinding_AntiDeadZone_joystick_mouse_Description" "De fleste spil påfører deres egne dødszoner til controller-outputtet. Hvis styringen føles \"klunset\" med et fysisk bevægelsesområde, hvor der ikke sendes noget input til spillet, så er det højst sandsynligt forårsaget af spillets dødszone. Du kan fjerne den ved at bruge indstillingen for anti-dødszone. Dette ophæver dødszonen og giver mere præcis styring i den tilbageværende sektion. Jo højere slideren sættes, jo mere tilføjes der til den mindste outputværdi. Bemærk at hvis al dødszone fjernes fuldstændigt, så vil alle positioner resultere i input. Du kan bruge buffer for anti-dødszone til at anbringe et mindre område, hvor der ikke sendes input, selv hvis anti-dødszonen er større end spillets dødszone."
	"ControllerBinding_AntiDeadZoneBuffer_joystick_mouse" "Buffer for anti-dødszone"
	"ControllerBinding_AntiDeadZoneBuffer_joystick_mouse_Description" "Hvis der er påført anti-dødszone, så er der muligvis ingen egentlig dødszone, som påføres af spillet, hvilket betyder, at berøring hvor som helst vil resultere i bevægelse. For at ti